### ISSUE TITLE
internal/pkg/db/db.go should not be internal

### ISSUE THREAD

**Issue by vaind** [edgexfoundry/edgex-go#1053]
In order to extract MongoDB out of the EdgeX repository (and/or use other DB providers), the `db` package, specifically the types defined in `internal/pkg/db/db.go` need to be moved from `internal` to `pkg`.

This could be done fairly easily using an IDE refactoring/move feature so if you want, I can make a PR with the changed code.

**Comment by tsconn23** [comment]
We aren't looking to extract MongoDB out of the edgex repository at the moment, and most of the constants in the file are used internally by the Mongo implemenation so why would we move them out? As for the error types, if you're raising the flag that the current definitions need to be elsewhere so that the API controllers don't reference an internal package anymore when they do error handling, that's a valid call-out. But I personally don't think the timing is right since we are still evaluating options for 3rd party plugin/module integration.

**Comment by vaind** [comment]
a few reasons to move them out/refactor the coupling:

* types that are really used only by the mongo implementation should, I guess, be moved to the mongo implementation
* mongo/any-other-provider NewClient takes `db.Configuration` as an argument - this should either be something universal (e.g. `map[string]string`) or at least not a private type. The only way this works as it is now if you were to keep all the 3rd-party integrations in the EdgeX repository itself.
* the error types (e.g. `db.ErrNotFound` are used throughout the code - similar to the previous point
