### ISSUE TITLE
Remove Value Descriptor from core-data

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#1071]
If I'm not wrong, the main purpose of the value descriptor is to allow core-data to check if a received reading have a valid value or not. But the reality is core-data doesn't use the value descriptors, and value descriptors are a problem for the device services.
Let me expose what's currently happening:
1. core-data is not checking the readings values because by default ValidateCheck is disabled
2. If you enable ValidateCheck, then the expected Type value in core-data is different of the Type used in device services, so core-data always generates an error in this case
3. Value descriptors are generated by the device services, but they are never updated or removed. This means if a device profile is updated or removed, the related value descriptors are not updated or removed
4. Different device profiles will use the same value descriptor if the value in Parameter field is the same, although maybe they have different values in the PropertyValue
5. If core-data have more value descriptors than the number defined in ReadMaxLimit, then the device service fails to initialize
6. The device service only uses the value descriptor to get the Type field in the write operations.

If my proposal to remove the value descriptor is too much radical, maybe an alternative is to add a configuration parameter in the device service in order to enable/disable the creation of value descriptors in core-data; also remove the value descriptors cache from de device service in order to only use the device profile.

**Comment by iain-anderson** [comment]
Agree we should remove the ValueDescriptors, or at least make them entirely internal to core-data. The definitive model is the device profile in core-metadata; if it is useful for core-data (or any other microservice) to maintain a transformed version of that information then the best way to keep that version correct is to centralise its creation and updates within said microservice.

**Comment by tsconn23** [comment]
If we do this, we'll probably need to do this in stages and I think this will need to be discussed on some upcoming Device Services/Core working group calls. I don't want anyone thinking we're committing to this for Edinburgh. We have enough on our plate.

However, there are a couple bullets from Joan's list that I do think are high priority.
1.) The value descriptor `Type` field value differs from `DeviceResource.Properties.Value.Type`. This might actually be a bug on the [check for value descriptor validity](https://github.com/edgexfoundry/edgex-go/blob/e4a72439fdb74c5b97af3a313084b387d8b62a5c/internal/core/data/validate.go#L19) when an event is ingested rather than the data [added from the Device SDK](https://github.com/edgexfoundry/device-sdk-go/blob/d227676f586112b0ea387ecfcd7c45336698ee54/internal/provision/profiles.go#L138). So we might just need to fix the validity check.

2.) Proper maintenance of value descriptors when device profiles change, get removed, etc.

For example, these could be their own issues and allow us to clean things up incrementally as time permits. I also think these points are part of the basic functionality we want for EdgeX so they should work for Edinburgh.

As to the management of value descriptors as a decoupled model used only by core-data, I'm not opposed to that idea. If it's true that only core-data relies on value descriptors and the Device SDK creates them as a courtesy, then I agree that's a misplaced responsibility on the Device SDK. But as I said, I'm not going to commit to going all the way with this for Edinburgh. We need to discuss more.

**Comment by tonyespy** [comment]
As I understand it, the reason value descriptors belong in Core Data was that it allows clients of Core Data (or export services) to easily lookup a value descriptor via `Reading.Name`, and thus have available the type related metadata of the reading. Yes, a client of Core Data could go to Metadata and read all the device profiles in order to find the related type information, but that requires a client to use an additional client package, and the lookup is non-trivial (v.s. a hash lookup when using value descriptors).

**Comment by iain-anderson** [comment]
A problem we have with the valuedescriptors as they stand is that they put a requirement on device profile writers to avoid deviceResource name clashes with any other device profile that might be used. If we were to add the device profile name to `Event` it would disambiguate the Reading names and also allow services to directly obtain the relevant device profile.

**Comment by tsconn23** [comment]
Action Items for Daniel
1.) Synchronize handling of Value Descriptors with Device Profile mgmt
2.) Discuss scoping of value descriptors with Device Service team to avoid name collisions like Iain called out above
3.) Make mgmt of value descriptors more efficient through use of concurrency ( channels / goroutines ) rather than REST calls.

**Comment by tsconn23** [comment]
Closing. Superseded by https://github.com/edgexfoundry/edgex-go/issues/1471
