### ISSUE TITLE
Implement more resilient method of downloading cassandra for the snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1103]
Unfortunately cassandra download links are not persistent in that when a new patch release (such as 3.11.4) is released, the old patch release download link (such as for 3.11.3) is removed immediately. 

We should investigate a better way to handle this

**Comment by anonymouse64** [comment]
See for example failed build https://jenkins.edgexfoundry.org/job/edgex-go-snap-master-verify-snap/192/console

**Comment by tsconn23** [comment]
Where does Cassandra fit into the Snap deployment?

**Comment by anonymouse64** [comment]
The security services use Kong for the HTTPS proxy, and Kong uses it's own database for storing information about routes and things. Kong can either use postgres (which is what the docker scripts use) or it can use Cassandra. We would like to use postgres but it isn't fully compatible with snap because daemons in snaps always run as root, and postgres won't run as root.

If we were to switch to using postgres, then folks would have to add the postgres user outside of the snap as the snap isn't allowed to add users to the system itself. This complicates the install process and so we went with Cassandra which just works out of the box (but has it's own issues like this issue and the fact that's its Java based and slow to startup on less powerful machines)

**Comment by anonymouse64** [comment]
This is more of a problem than I anticipated because now the delhi and california snap builds are broken and so going forward for every support branch of EdgeX we would need to update the download URL for cassandra.
See for example https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-delhi-stage-snap/123/ and https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-california-stage-snap/254/

**Comment by anonymouse64** [comment]
While unfortunate I think the best thing to do is to build cassandra from source using the github source+tags: https://github.com/apache/cassandra

**Comment by bnevis-i** [comment]
It just got bit by this issue....  The following blog tipped me off to the real issue: https://www.gastongonzalez.com/tech-blog/2015/4/18/building-hybris-through-a-proxy.   Essentially the trouble is this caused by this section of the ant `build.xml` in Cassandra:

```
      <artifact:dependencies pomRefId="build-deps-pom"
                             filesetId="build-dependency-jars"
                             cacheDependencyRefs="true"
                             dependencyRefsBuildFile="${build.dir}/build-dependencies.xml"
                             settingsFile="/home/bnevis/.m2/settings.xml">
          <remoteRepository refid="central"/>
          <remoteRepository refid="apache"/>
      </artifact:dependencies>
```

It turns out that the presence of remoteRepository causes any proxy information anywhere in the system to be ignored.  Looking up the definition of remoteRepository, http://maven.apache.org/components/ant-tasks/reference.html#remoteRepository, you find that it takes a nested proxy element: http://maven.apache.org/ref/3.6.1/maven-settings/settings.html#class_proxy  which is exactly the same thing that you would normally put in your `~/.m2/settings.xml` file.

Obviously, we can't change Cassandra's `build.xml` but I confirmed the issue by commenting out remoteRepository and this step at least started working.

**Comment by anonymouse64** [comment]
@bnevis-i mentioned over slack we could go back to downloading cassandra using the archive link, i.e. `http://archive.apache.org/dist/cassandra/3.11.3/apache-cassandra-3.11.3-bin.tar.gz` for 3.11.3
