### ISSUE TITLE
Streamline the parsing of the output from the `docker` command being serviced by system-management.

### ISSUE THREAD

**Issue by akramtexas** [edgexfoundry/edgex-go#1129]
- Based on excellent PR feedback from @anonymouse64, the goal of this task will be to streamline the parsing of the output from the `docker` command.
- The details below are from the feedback from @anonymouse64 which appear in [PR-1122](https://github.com/edgexfoundry/edgex-go/pull/1122) :

> The `docker` command has a flag to make the output conform to JSON. While an easy way to parse that JSON would be to import the docker libraries where that JSON schema is defined in go, that's a heavy handed way and instead it's fine to simply just define the fields you care about from the JSON inside a struct with proper structures, and then when parsing specify to ignore unknown fields so the parsing doesn't fail. For example see:

```
$ docker ps -a --format '{{json .}}' | jq
{
  "Command": "\"date\"",
  "CreatedAt": "2019-02-22 08:49:12 +0100 CET",
  "ID": "e477204cc97d",
  "Image": "ubuntu",
  "Labels": "",
  "LocalVolumes": "0",
  "Mounts": "",
  "Names": "clever_edison",
  "Networks": "bridge",
  "Ports": "",
  "RunningFor": "6 seconds ago",
  "Size": "0B",
  "Status": "Created"
}
```

> Also note that docker outputs it's JSON as a stream, which means that independent JSON objects are output immediately after one another, rather than being put in a list. See https://golang.org/pkg/encoding/json/#example_Decoder_Decode_stream for an example of how to handle this with the standard JSON library.

**Comment by anonymouse64** [comment]
Just to add some more to this issue, I really think that this needs to be addressed before we release Edinburgh because this could at some point lead to a security vulnerability because the system-management-agent docker container is now effectively a "docker-in-docker" container, and as such it could be used for privilege escalation. This is because the docker socket can be used to run arbitrary code as root on the host system, and so we need to be very careful how we parse commands provided to this executable to ensure that we don't open up an avenue for an attacked to execute arbitrary commands on the docker socket.

Requiring that output be parsed in a fully expected way with JSON is one way to harden this executable

**Comment by anonymouse64** [comment]
@akramtexas any progress on this issue?

**Comment by akramtexas** [comment]
> @akramtexas any progress on this issue?

@anonymouse64 My apologies for the delayed response: Somehow, I missed this query from you... Glad you brought this up during the `Sys Mgmt WG` meeting today (I'll circle back with you, thanks) 👍
