### ISSUE TITLE
Service and code documentation moved to Github

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#117]
Move the EdgeX microservice, code and API documentation to Github.  Provide linkage between the Wiki site and Github documentation as necessary.  Remove the applicable documentation from the Wiki.

**Comment by drasko** [comment]
I would strongly advise here same approach like Hyperledger Fabric:
- All documentation is put into the Monorepo, under the directory `/doc`
- `ReadTheDocs` service is set-up to auto-generate all docs from this GitHub folder: https://hyperledger-fabric.readthedocs.io/en/release-1.1/

This way any PR sent to Monorepo `/doc` is automatically re-generated and visible on `ReadTheDocs`.

**Comment by andyf1967** [comment]
There are about 250 reStructuredText files, images and Sphinx build files in total. We were planning to put the EdgeX documentation in the Monorepo underneath /doc, but with the following structure below:
/doc
        /general
        /configuration
        /core
	        /command
	        /data
	        /metadata
        /device
	           /profile
	           /sdk
	           /virtual
        /export
	           /client
	           /distro
        /support
	             /notifications
	             /logging
	             /rulesengine
	             /scheduler
        /api
        /getting-started
        /examples

Some of the docs for the Java microservices (e.g. rulesengine, notifications) for which there is not yet a Go equivalent could go in their respective repositories. However, I think for simplification it’s probably better to keep the documentation together (open to comment on this).

In addition to using Sphinx to build the reST files, we also use ram2html to build the RAML files (converts them into HTML) and then via a script we integrate them into the web framework generated by Sphinx. Using ReadTheDocs to pull from our repository and build (and host) the Sphinx generated documentation is an definitely an option. Would have to look into how easy it is to incorporate the RAML build process with the ReadTheDocs Sphinx build, but assume this could be done.

**Comment by drasko** [comment]
@andyf1967 yes... I forgot the images :(. Maybe in that case it is better to put everything in separate `edgex-doc` repo?

**Comment by andyf1967** [comment]
@drasko @jpwhitemn I think that the because the migration to Go services and use of a Monorepo is the direction that we going I would lean towards putting the documentation in the same repository.

**Comment by drasko** [comment]
@andyf1967 +1 for Monorepo.

Generally - introduction of monorepo helped us follow much closer of what is happening on the project, react on PRs and review then quickly IMHO. Also it "unifies" the code style, making it more consistent.

So - I would put in monorepo as much as we can. Additional convenience of having doc in Monorepo is that developer can update/correct the doc in the same PR for the code - no need to fork two repos, then make two different PRs.

Drawback is that if somebody decides to put huge pictures and diagrams, then it would slow down the initial `git clone` procedure. Binary files Stay in the `git` history even when you remove them from the repo (because delta is the whole binary file :)).

**Comment by jpwhitemn** [comment]
@andyf1967 - I recommend we close this issue and open new ones for any remaining work items.

**Comment by andyf1967** [comment]
@jpwhitemn I agree.
