### ISSUE TITLE
Core-Data: CBOR Event Handling

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1216]
New events coming into core-data are handled by the POST section of `eventHandler` found in [router.go](https://github.com/edgexfoundry/edgex-go/blob/cd039ab618167a822852876435a45f7869f5901f/internal/core/data/router.go#L184). For this task we'll need to branch the logic according to the incoming `ContentType` header value. JSON is the default, but calling clients can also indicate CBOR. If the event is being passed in CBOR, we need to do the following:

1.) Unmarshal the incoming request body from CBOR to an Event and associated Readings using the `github.com/ugorji/go/codec` package
2.) Persist the event into the given database
3.) Publish the event to the message bus

Steps 2 and 3 above currently happen [here](https://github.com/edgexfoundry/edgex-go/blob/cd039ab618167a822852876435a45f7869f5901f/internal/core/data/event.go#L85)

There are a few points to how this should work
- When persisting an event originating as CBOR, the [BinaryValue](https://github.com/edgexfoundry/go-mod-core-contracts/blob/e53159cfbe2cc8832483252ada48f1a5475584f6/models/reading.go#L37) of a given reading should NOT be persisted to the database because of space considerations. This means that whatever custom logic we need to write to unmarshal an Event from CBOR should ignore the BinaryValue property.
- The bytes of the original CBOR request will therefore need to be retained as they constitute the only copy we will have of the binary data. This is important when we [publish the Event](https://github.com/edgexfoundry/edgex-go/blob/cd039ab618167a822852876435a45f7869f5901f/internal/core/data/event.go#L222).
- During the act of publishing the event, we need to indicate a ContentType of CBOR versus JSON. If JSON, the existing mechanism will work to re-marshal the given event. If CBOR, we should pass the original bytes.

**Comment by tsconn23** [comment]
Refer to PDFs on https://wiki.edgexfoundry.org/display/FA/Core+Working+Group for July 26, 2018

**Comment by AnthonyMBonafide** [comment]
I ran into a couple of hiccups while trying to implement these changes, and have some questions :

1. As per the [CBOR Flow PDF](https://wiki.edgexfoundry.org/display/FA/Core+Working+Group?preview=/329472/18907147/CBOR_flow_v2.pdf), the two pieces of functionality (DB persistence, and ZMQ publishing) which are expected to be handled concurrently seem to have to happen subsequently during a create request(POST). The reason is that when we publish the event to ZMQ we need to populate the event with the correct ID which we will not have until after the DB persistence has successfully completed. Furthermore, we cannot respond to the HTTP request since we will also need to respond with an Event ID, so this means we cannot even do the DB persistence asynchronously and respond to the request without having to wait. Are these points valid or am I incorrectly assuming something based on previous implementations? See relevant code [here](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/data/event.go#L113-L120)

2. The original CBOR contents from the request will not contain the actual event ID when creating a new event via a POST operation, and instead will be 0 due to the lack of an ID when POSTing the data. In this situation should we update the CBOR data so that it contains the correct Event ID?

**Comment by AnthonyMBonafide** [comment]
After some discussion, the route we would like to take on this issue is the following manner as proposed in the mailing list:

1. A CBOR event comes in.
2. We obtain a checksum value for the byte array
3. We store that checksum as part of the Event model in core-data
4. The CBOR byte array is published through the bus
5. The subscriber receives the byte array and also calculates the checksum
6. When the subscriber is done handling the event, it calls a PUT on core-data passing the checksum
    6a. This would entail a modification to the request type of the [existing API](https://github.com/edgexfoundry/edgex-go/blob/060bef2730d23130bdc1d5e463b323cfc8091a12/api/raml/core-data.raml#L31)
7. Core-data locates the event and marks it as "pushed"

To answer my own questions, we will now be able to perform the operations concurrently as per the original proposal. Also, we will not need to update the original CBOR content to contain the ID as it is only used for acking the pushed event to core-data, instead we are using  a checksum as the identifier.

**Comment by iain-anderson** [comment]
If we were to stipulate that the timestamps used to populate Event.Origin must be strictly ascending, an Event could be uniquely identified by { Device, Origin } without having to compute a checksum.
This would however require us to move to higher resolution timestamps.

**Comment by AnthonyMBonafide** [comment]
@iain-anderson, that is an interesting thought. We discussed introducing the checksum solution in a configurable way to allow the user to determine the desired trade-off of time vs. possible collisions by specifying the hashing algorithm to use(MD5, xxHash, etc.). The way I plan to structure these changes will allow us to pull this off rather easily by just providing another implementation to the "checksum" abstraction which would just use the information you are suggesting. We planned on providing functionality for `MD5` and `xxHash` for this first iteration, but if we can pull this off without changing the `Origin` information, I would not mind adding an implementation which does what you are suggesting.

**Comment by lenny-intel** [comment]
Hi Anthony,
   We discussed making the hash algo configurable. If we do this the subscriber will also need to know which hash algo to use. I propose we add hash algo type to the Message Envelope, so the subscribers don’t have to have it in their config.

The rest looks great!

Thanks!
  Lenny

**Comment by AnthonyMBonafide** [comment]
I originally included the hashing algorithm in the envelop. After talking it over with @tsconn23, we thought that it would be more efficient to publish the checksum value in the message envelope which can be used by consumers to ack the event message without having to recalculate the hash. Is there another reason for the consumer to know the hashing algorithm which I am missing?
