### ISSUE TITLE
Update Commands when DeviceProfile is Updated

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1269]
At this point, we are saving the DeviceProfile as its own document. It is a template serving to tell new devices assigned to the profile which commands they support. If the DeviceProfile is updated and the command definitions change, then all Devices associated to the profile need to also update their command definitions.

** I will add more details shortly **

**Comment by difince** [comment]
@tsconn23 

At this point, as you say, the DeviceProfile is saved in its document that include command definitions.
These command definitions serve as a template telling the device assigned to the profile which commands they support. 
The command definitions (from DeviceProfile) are currently simplified - they contain less parameters - just Name, Get and Put (from database point of view, the `contracts` are not changed). All other fields as timestamps (create, update, origins - still not mergerd) and Id are moved to the actual commands as well as they have references to the device they belong - deviceId and deviceName.

If the DeviceProfile is updated and the command definitions change, then all Devices associated to the profile need to also update their command definitions 
what does this mean: 

 Because the command definition does not have any id, the name could be used as a key. (therefore the name of the command will be forbidden for change. When we de-touch the device from the Profile, the  ProfileName will be also forbidden for changes).
There are three possibilities for change: To update already existing command, to add new command or to delete a command.

- Get all devices by profileName - Search by name, because we intend to de-touch the profile from the device. 
- Iterate over all changed command definitions and devices to  apply the appropriate changes. 

		- in case of Update
		getCommand ByName and DeviceId
		update the command (including the timestamps)

		- in case of Delete
		getCommand ByName and DeviceId
		delete the command

		- in case of Create
		createCommand for the specified device and command definition

Note: When updating the DeviceProfile, if the user intend to update the commands definitions , he needs to provide the entire list of them. If the user does not intend to do so, the commands should be skipped from the request body. 
What do you think about this approach ? 

Just thoughts: The update of deviceProfile will be rare operation. 
Use cases for updating deviceProfile.commands  could be ... fix of wrongly created one, or the hardware device have been upgraded to new version. Just thinking of ... what if we want someday to support multiple versions of a device, that have a slight difference in the command definitions... should we create for each version new device profile with new name respectively  (or new field for version will be added .. as part of compound key: profileName-version)

**Comment by tsconn23** [comment]
> Because the command definition does not have any id, the name could be used as a key.

So when we create a command for an individual device based on the device profile, it WILL receive an ID. However, to your point, that will not be of any use in trying to modify a command according to a Device Profile change. So I propose that the database model going into the metadata/commands collection should have both `DeviceID` and `DeviceProfileID` as properties. 

-`DeviceID` will allow fulfillment of the current core-command `GET /device/{id}` endpoint and others like it. Once we have the device then we go to the commands collection and pull its commands.
-`DeviceProfileID` will allow for easy retrieval of all commands associated to a device profile that may be modified or deleted. For an update/delete this should avoid the interim step of having to find all the related devices and THEN obtain their commands in a subsequent loop. An add would still require a device lookup so that the devices and new command can be associated correctly.

> what if we want someday to support multiple versions of a device

Let's not consider this for now because there really isn't a concept of this in EdgeX at all. This would be a larger effort that would affect multiple working groups.

**Comment by difince** [comment]
Hi, Trevor 
Is this issue still wanted to be implemented taking in consideration issue [1494](https://github.com/edgexfoundry/edgex-go/issues/1494)? 
If the device profile update operation is prohibited when the profile is in use - then no "device commands" need to be cleared, because they do not exist if no device is present .

**Comment by tsconn23** [comment]
@difince Yes, I think you're right. This issue can be closed then. Go ahead and close it if you agree.
