### ISSUE TITLE
Store CoreCommands as Denormalized Part of DeviceProfile

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1270]
When adding a DeviceProfile, the CoreCommands are stored in a manner similar to a relational database. Rather than remaining part of the DeviceProfile document, they are persisted into their own collection (Mongo) or index (Redis). We need to stop this behavior. CoreCommands should be stored on the DeviceProfile itself and then serve as a template for the commands supported by Devices that inherit from the DeviceProfile.

**MONGO**
Looking at the [AddDeviceProfile](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/pkg/db/mongo/metadata.go#L343) function, you can see that Commands are saved first before the DeviceProfile itself. This results in a list of DBRef entries that are associated to the [CoreCommands property](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/pkg/db/mongo/models/deviceprofile.go#L95) of the Mongo-specific data model, similar to a foreign key. Note that these commands are the only ones stored in this manner.

Eliminating this relationship will potentially allow us to remove code related to the [commandTransform](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/pkg/db/mongo/models/command.go#L24) interface and its implementation in the [metadata MongoClient](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/pkg/db/mongo/metadata.go#L885).

**REDIS**
A [similar approach](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/pkg/db/redis/metadata.go#L535) is taken in Redis, which simply follows the pattern established in Mongo.

In both cases what we should wind up with once this work is done, given a fresh database, is a DeviceProfile saved in JSON that has all of its related data stored in one document without the need for additional lookups based on a relationship. The current `command` collection (Mongo) or index (Redis) where commands are stored should be empty.

Finally, as a follow up, I believe [this lookup](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/core/command/device.go#L42) within the `commandByDeviceID` function can be removed. We are still at the point where a DeviceProfile is part of a Device. As you can see earlier in the function, the Device is loaded. All that needs to be done here is to find the CoreCommand entry corresponding to the `commandID string` parameter value.

**Comment by difince** [comment]
> Finally, as a follow up, I believe this lookup within the commandByDeviceID function can be removed. We are still at the point where a DeviceProfile is part of a Device. As you can see earlier in the function, the Device is loaded. All that needs to be done here is to find the CoreCommand entry corresponding to the commandID string parameter value.
Will we continue to generate ID for commands once they are part of the DeviceProfile itself? Why don't we use the command.Name and command.DeviceID/deviceName (we are going to add)  as a composed unique key  ?

**Comment by difince** [comment]
@tsconn23 I am writing in order to be sure that I understand exactly what I am supposed to implement.

In the current implementation as I see we have:
dbmodel struct for [Device ](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/mongo/models/device.go) that includes a DBRef to the Profile. 
While the db model struct for [DeviceProfile ](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/pkg/db/mongo/models/deviceprofile.go#L95) contains list of DBRefs for commands:
```
type DeviceProfile struct {
	....
	DeviceResources []DeviceResource  `bson:"deviceResources"`
	DeviceCommands  []ProfileResource `bson:"resources"`
	CoreCommands    []mgo.DBRef       `bson:"commands"`
}
```
As I understand I am supposed to replace 
`CoreCommands    []mgo.DBRef       `bson:"commands"``
with 
`CoreCommands    []Command         `bson:"commands"` `
As a result  the Commands will be saved in denormalized way (array of embedded command documents) that will contain uuid only (without -> Id bson.ObjectId `bson:"_id,omitempty"` ). 
This uuid will be used temporary (just from temporary backward compatibility). When all tasks are done ..this uuid could be removed. Correct ? But removing this we will break down [GetDeviceProfilesByCommandId](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/pkg/db/mongo/metadata.go#L393)(But is this function really needed?)
These commands as being embedded into the DeviceProfile struct itself will be maintained (created, updated, deleted) on restAddDeviceProfile/restUpdateDeviceProfile/restDeleteProfile_By_XXXX

Till now, I have been talking only for db structures - Device->Profile->Commands, which definitions come from the respected contracts models .  

If I understand correct what i need to do is: when adding new device I need to get its deviceProfile that is already saved into the DB, 
get its embedded(already denormalized) core-commands, and used them as a template for creating/saving absolutely new device.Commands along with saving the device itself. 
And these device.commands saved in the DB will contain all the information from the device.profile.commands plus information of the device they belong to (DeviceID and DeviceName).
This new collection of commands will be saved using DBRefs (in case of mongo), not in denormalized way ? Is that true? 

Once we have all this, all core-command service endpoints as: [restGetCommandsByDeviceName](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/command/restDevice.go#L190), [restGetCommandsByDeviceID  ](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/command/restDevice.go#L207), even [restGetAllCommands](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/command/restDevice.go#L224)... will read directly from this new "device.commands" collection (considering https://github.com/edgexfoundry/edgex-go/issues/1274)

Having these two collections for commands: _1.profile.commads_ used as template to create _2.device.commads_, if the profile.commads are updated this change needs to be propagated to all device.commands that use this profile. I suggest that the update/delete/create of the Commands should happen only through update of the DeviceProfile. Currently, as noted below, there are methods that manipulate the commands directly! (Btw, if we keep the device.profile.commands.uuid we could easily make reference between the device.commands and device.profile.commands? )

NOTE- in the current implementation there are endpoints for [adding ](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/metadata/rest_command.go#L45)and [updating ](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/metadata/rest_command.go#L69), deleting Commands directly. This could lead to commands present into the database  that does not have any reference to any device or deviceprofile?

**Comment by tsconn23** [comment]
Yes, this is correct. I can add an agenda item to the next Core WG meeting with regard to removing the  endpoints you call out. As you say, I don't think anyone is using `GetDeviceProfilesByCommandId` and I agree that there is no use for directly manipulating commands for a given device independently from the profile. We will want a decision to remove these APIs for Edinburgh soon, even if your work isn't completed yet.

**Comment by difince** [comment]
GetDeviceProfilesByCommandId is called only on  updateCommand and deleteCommandByID
- [restDeleteCommandById](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/metadata/rest_command.go#L188)(in isCommandStillInUse)
- [restUpdateCommand](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/core/metadata/rest_command.go#L88)
- in [2 tests](https://github.com/edgexfoundry/edgex-go/blob/9a89dd08bf0d3cc841851472a5d4626c380280f5/internal/pkg/db/test/db_metadata.go#L896) that test the function itself

So, if these is an agreement that it does not make sense to update/create/delete Commands aside from the device Profile (exception: delete device.commands when we are deleting the device instance) this will be the first thing I will do. (it will make my next steps easier)

**Comment by tsconn23** [comment]
Well, we'll need to discuss it in a Core WG call but I am nominally in agreement. I mean, those endpoints right now effectively don't do anything because we always look to a device profile for a device's commands. Someone could add/update commands all day long and it would have no effect. So we should just get rid of the endpoints.
