### ISSUE TITLE
Implement Persistence Layer in Core-Command

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1274]
Once all of the above issues have been addressed, we need to then implement the Persistence layer in the Core-Command service. This will replace the current calls to core-metadata with a direct database call, eliminating what are effectively pass-through hops.

1.) Create an `internal/core/command/interfaces` package. A db.go file inside of that should define the necessary function signatures for the persistence layer. It's possible that these will overlap with functions [already found](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/core/metadata/interfaces/db.go#L90) in the core-metadata DBClient. 
** TODO: We can discuss what to do with these when the time comes. **
2.) It will be necessary to add bootstrapping of the appropriate database client as found in [other services](https://github.com/edgexfoundry/edgex-go/blob/713baa536c1563875d9ec61d0096859740ca004d/internal/core/metadata/init.go#L220). This will also require configuration changes to include connection information (host/port) and database type, as well as Registry support.
3.) Functions that [previously utilized](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/command/device.go) the metadata client to obtain their data should now use the DBClient instance.

The format of the data returned to the external caller of the API should be the same. That is, we preserve the `contract` struct return types.

**Comment by difince** [comment]
@tsconn23 
Currently "device commands" (i call them this way, because they appears when the device is added, based on the device.Profile) are saved in "metadata" database. 

Implementing Persistent Layer in Core-Command service.. does it mean that a new database with name "command" should be added? 

It make sense each service to have each own database, but the way the device commands are created is tidy connected with metadata service - add/ delete device. 
If we add new database, we should add new endpoints for managing device commands in command service(not only reading as it is nowadays).These endpoints will be called from metadata service when the device is added/deleted. (note: these endpoints need to be only for internal use )

**Comment by tsconn23** [comment]
@difince Would recommend for this effort that the existing core-command endpoints call through to the metadata db and the command collection it contains. I agree with all of your points above and if we were building this as a new service, that's how I'd proceed. However, I'd like to minimize impacts to the API for now -- at least until Fuji is out the door. If we decide a more thorough re-org of the responsibilities would make sense for Geneva, we can discuss at that time.

**Comment by difince** [comment]
@tsconn23 
What I just realized is that if we force command service to directly query the metadata database, this means: 
when the command service is booting we will need to load 2 configuration files - the command service conf file and metadata service config file. We will need metadata service config file in order to understand what database metadata service is configured to use , on which port and etc... I am not happy with this

**Comment by tsconn23** [comment]
@difince Not necessarily. Here's what I'd recommend.

1.) Bring over the `[Databases][Databases.Primary]` section from core-metadata's configuration.toml (don't forget the docker version) into core-command's configuration.toml
2.) Core-command will need its own DBClient interface. To be consistent with the other services, this should be defined in `internal/core/command/interfaces/db.go`. Copy the signatures of the functions you need from the version of this interface in core-metadata.
3.) Core-command's init.go will need to be extended to actually connect to the database. See [here](https://github.com/edgexfoundry/edgex-go/blob/03f28e5980c37459c208a296556b0d148bea68db/internal/core/metadata/init.go#L221) for an example. You will need the interface in step 2 for this to work. **

At that point you should have a DBClient instance that is usable for querying commands and you can rewrite the relevant functions to use it.

_** I realize this area of the code isn't encapsulated very well and relies heavily on cut-n-paste_
