### ISSUE TITLE
Upgrade to official mongodb driver

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1288]
An official mongodb go driver has been released: https://github.com/mongodb/mongo-go-driver/releases/tag/v1.0.0 (see also the announcement https://www.mongodb.com/blog/post/official-mongodb-go-driver-now-ga-and-ready-for-production and a tutorial series https://www.mongodb.com/blog/post/mongodb-go-driver-tutorial-part-1-connecting-using-bson-and-crud-operations)
It's not clear to me how much work it would be to switch to this, but considering the one we are currently using is only slightly more maintained than the original one which was deprecated switching to the official one is probably a good idea.

**Comment by tsconn23** [comment]
After Edinburgh we can look at this. A question I'd ask is do we need to do this if there isn't a specific bug that we need to address in the current driver? I did play with the Mongo driver when it was in alpha to get a sense of the work involved in replacing the GlobalSign driver and at that time, it looked like it was going to be an expensive effort due to the two being pretty different.

If someone wants to go down this road a bit and do a presentation at one of the upcoming Core WG calls, I'd be open to that.

**Comment by michaelestrin** [comment]
Closed.  Not on the current road map.
