### ISSUE TITLE
Update kong to 1.0.3 in the snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1303]
The snap should be updated to match the docker-compose file for the security-api-gateway and use kong 1.0.3. A few outstanding issues to handle when doing so:

* Apparently kong has never worked properly on arm64, silently failing when run with:
```bash
ubuntu@ubuntu:~$ sudo kong migrations up --v --yes --conf /var/snap/kong/current/config/kong.conf
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```
(more details available in https://github.com/edgexfoundry/blackbox-testing/issues/185)
* Kong now has new dependencies such as a yaml library etc. that need to be installed. For reference, looking at the build tools repo here will be useful: https://github.com/Kong/kong-build-tools/tree/feat/multi-arch
* The version of perl in the snap after we migrate to core18 is different now so we need a better way to handle running perl inside the snap and setting up those environment variables
* Doing the trivial thing and just updating the `source-tag` somehow breaks the symlinks setup in the snap currently such that somewhere along the line kong tries (and fails) to execute:
```
ubuntu@ubuntu:~$ kong
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
ERROR: failed to run command "/build/kong/parts/openresty/install/nginx/sbin/nginx -p /tmp/resty_VzlrgHvfEw/ -c conf/nginx.conf": No such file or directory
```

- [ ] Disable security-api-gateway on arm64, including kong and cassandra
- [x] Use `lua5.1` and `luarocks` deb packages with `stage-packages` instead of building from source
- [x] Fix kong part to not build inside `$SNAPCRAFT_STAGE`
- [x] Debug hard-coded path to nginx when running kong perl module (shown above)
- [x] Dynamically determine perl version before running kong

**Comment by anonymouse64** [comment]
Currently unclear if arm64 will be officially supported by kong in time for Edinburgh, however if not it seems that armhf support is working and so we could hypothetically cross-compile kong for armhf target architecture on the arm64 jenkins builders, however this sounds rather difficult to setup in the snap. 

We may just end up disabling the security-api-gateway on arm64 if these issues aren't resolved in time.

**Comment by anonymouse64** [comment]
After some discussion today, we decided to just disable security-api-gateway in the snap when running on arm64 until kong + openresty (and lua I guess?) properly support arm64.

**Comment by anonymouse64** [comment]
The version of lua and luarocks in the bionic archive seems to be sufficient to build kong 1.0.3, so we can probably drop those parts and just build openresty and kong in the snap. This should simplify the build process a bit and also speed it up. While doing this, care should also be taken to ensure that we fix the kong part build to not just build everything inside $SNAPCRAFT_STAGE so that we don't end up staging everything from previous parts into the snap.

**Comment by jpwhitemn** [comment]
Ian - separate concern, but related to Lua - what are your thoughts?  Some discussion at the Face to Face about using a Lua or similar engine with scripting to replace the rules engine.  Reaction?  Have you actually done any work with Lua outside of just getting the Kong build working?

    On Monday, May 13, 2019, 7:15:22 PM PDT, Ian Johnson <notifications@github.com> wrote:  
 
 
The version of lua and luarocks in the bionic archive seems to be sufficient to build kong 1.0.3, so we can probably drop those parts and just build openresty and kong in the snap. This should simplify the build process a bit and also speed it up. While doing this, care should also be taken to ensure that we fix the kong part build to not just build everything inside $SNAPCRAFT_STAGE so that we don't end up staging everything from previous parts into the snap.

**Comment by anonymouse64** [comment]
@jpwhitemn I've used lua a bit to extend another application by writing plugins (specifically VerneMQ, an MQTT broker written in Erlang). Lua is fairly simple to use and can have good performance, but to my knowledge it's not widely used. It's used in the video games industry a lot, as well as in some applications such as high performance applications that need generic plugin functionality like VerneMQ (as well as Redis actually - perhaps @andresrinivasan can comment on experience using lua in Redis)

**Comment by andresrinivasan** [comment]
In Redis, Lua is perfect for the equivalent of a stored procedure, triggers, and even creating new Redis commands. We have also seen it used in the way IOTech described as a way to create OTA updated apps while treating Redis as an app server.

In general I've been seeing Lua used in microcontrollers and low power devices due to its portability, runtime size, and speed. It would be trivial to express the IFTTT rules described by the EdgeX rules interface in Lua and push them to Redis.

**Comment by anonymouse64** [comment]
@jpwhitemn perhaps you should spin off a new issue to discuss lua usage as a replacement of the rules engine, possibly with some integration directly into redis...
