### ISSUE TITLE
Getting Started Go developers page doesn't say Java services is archived

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1364]
# 📚 Docs or Wiki Bug Report

### Description

The GettingStartedGoDevelopers docs say that Java will be archived in the future, but AFAICT, all of the services except rulesengine have already been archived, so I think the page should be updated to reflect that.

### What's the affected URL?**
https://docs.edgexfoundry.org/Ch-GettingStartedDevelopers.html

**Comment by mhall119** [comment]
This reference is specifically in the [Java developers](https://docs.edgexfoundry.org/Ch-GettingStartedJavaDevelopers.html) documentation. 

Instead of updating and maintaining this page, it might be better to just remove it entirely. @jpwhitemn @tsconn23 what do you think? Should we ask the full TSC to weight in on that?

**Comment by anonymouse64** [comment]
Well there's both the reference in the Java developers page, as well as the normal developers page.

**Comment by mhall119** [comment]
Oh, it's in Ch-GettingStartedGoDevelopers.rst, I see it now
