### ISSUE TITLE
SMA docker container has minor issues

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1371]
The SMA docker container currently has this line:

https://github.com/edgexfoundry/edgex-go/blob/18f1118eedbe044ac12d3fa88b7e6ed2a7e9fe97/cmd/sys-mgmt-agent/Dockerfile#L39

This is the wrong way to get bash support inside the final container, instead it should be installed using `apk`. 

There are some other small issues like this line:

https://github.com/edgexfoundry/edgex-go/blob/18f1118eedbe044ac12d3fa88b7e6ed2a7e9fe97/cmd/sys-mgmt-agent/Dockerfile#L17

which should just be 

```dockerfile
RUN apk update && apk add make bash git
```

Additionally I think this line is suspect:

https://github.com/edgexfoundry/edgex-go/blob/18f1118eedbe044ac12d3fa88b7e6ed2a7e9fe97/cmd/sys-mgmt-agent/Dockerfile#L50

because it's referring to the moving branch master of developer-scripts, and so building this container at one point in time can end up with one version of the compose file, while building it later with the same edgex-go source leads to a different container. I think there should be some better way to tie the SMA container to a particular release with a particular docker-compose file. Additionally, it's not clear what the docker-compose file is even used for anymore, so if it's not used it should probably be dropped from the container.

**Comment by akramtexas** [comment]
@anonymouse64 To your point (i.e. `This is the wrong way to get bash support inside the final container, instead it should be installed using apk.`), I see that the following two approaches are suggested as possible, based on an online search I just did:
`RUN apk update && apk add bash`
`RUN apk add --no-cache bash`
Could you please advise on best approach? Thanks.
cc: @jpwhitemn @JPWKU

**Comment by JPWKU** [comment]
The `apk add --no-cache bash` means that it won't keep the package around on the container in the cache, thereby making the image smaller.   Since you are also doing an update and apk add'ing other packages it might be better to delete the apk cache directly after you are done installing.  `rm -rf /var/cache/apk/*`

**Comment by JPWKU** [comment]
Regarding @anonymouse64 concern about pulling the docker-compose file in, he is correct that it will result in an image not being reproducible if the compose file changes.  Not sure what to do about that in the immediate term.  In the future, we could opt to publish compose files to nexus as released artifacts which we can guarantee won't be changed.  That is, hook the generation of compose-files into the CI build and release process.

**Comment by akramtexas** [comment]
> Regarding @anonymouse64 concern about pulling the docker-compose file in, he is correct that it will result in an image not being reproducible if the compose file changes. Not sure what to do about that in the immediate term. In the future, we could opt to publish compose files to nexus as released artifacts which we can guarantee won't be changed. That is, hook the generation of compose-files into the CI build and release process.

Yep, and the solution turns out to be as simple as we would wish for it to be: For the Edinburgh release, I had simplified the implementation so that we use `Docker` commands throughout the executor, consistently. In other words, we do not go through `docker-compose` anymore. As such, it is a simple matter of removing the `docker-compose`-related directive from the `Dockerfile` 👍

**Comment by bnevis-i** [comment]
> The `apk add --no-cache bash` means that it won't keep the package around on the container in the cache, thereby making the image smaller. Since you are also doing an update and apk add'ing other packages it might be better to delete the apk cache directly after you are done installing. `rm -rf /var/cache/apk/*`

It's kind of late for me to jump in to this discussion, since the commit is already merged, but, for future referece,
```
RUN apk add --no-cache bash
RUN rm -rf /var/cache/apk/*
```

is the wrong way to do it, because you get a layer with apk results in it, and another layer with the rm results in it.  In general, use as few RUN commands as possible:
```
RUN commnd1 && command2
```
for conditional execution, or
```
RUN commnd1 ; command2
```
for unconditional execution
