### ISSUE TITLE
SMA in the snap starting/stopping services is not persistent

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1375]
Currently, in the snap when we one uses the SMA to start/stop services, it is an ephemeral change - it doesn't persist across upgrades or reboots. We could easily change this by also setting the configuration for that service to on/off using `snapctl set SVC=on|off` here:

https://github.com/edgexfoundry/edgex-go/blob/e34f2681076b036c3f9b55d9e3aafaaba931e687/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh#L36

However it's not clear to me whether we want stopping/starting services to be persistent when using the SMA. I think it should be, but perhaps that's not the intention of the SMA.

**Comment by anonymouse64** [comment]
@akramtexas @jpwhitemn can either of you comment on this? When a service is stopped by the SMA in docker or when deployed with native containers, is that service meant to be persistent or is it just a "stop this service right now" with the understanding it could be restarted again if a machine gets rebooted.

**Comment by jpwhitemn** [comment]
Hi Ian,per earlier discussion on this, we had said it would be just "stop" - with no persistence.  This seems to have parallels to some of the parameter string ideas for the enable/disable restart of services on restart of reboot (documented below in one of our Sys Mgmt meetings) brought forth before.  Is this revisiting the same idea with new insight?? 




Parameter strings provided by configuration and passed from the SMA through to the executor can be used to provide platform or environmental indicators to the Executor. For example, in some environments, there is the ability to enable/disable restart of services on restart or reboot of the underlying platform. The parameters list would be separated by a space if there was more than one. 


We are going to be relooking the start/stop/restart functionality for Geneva.  We are going to be making things more async and we need persistence to address what happens when the SMA is restarted as one of the services and there is a need to call back to the original client (covered in our meeting this morning).  So this is a requirement we could re-explore, but I'd like to know more about what differs from before.
Jim


   On Tuesday, September 3, 2019, 2:01:27 PM CDT, Ian Johnson <notifications@github.com> wrote:  
 
 
@akramtexas @jpwhitemn can either of you comment on this? When a service is stopped by the SMA in docker or when deployed with native containers, is that service meant to be persistent or is it just a "stop this service right now" with the understanding it could be restarted again if a machine gets rebooted.

**Comment by anonymouse64** [comment]
@jpwhitemn That answers my question and the current behavior in the snap is correct - it doesn't persistently stop services. This bug was simply about whether the snap should interpret a "stop" as a persistent stop or not.

**Comment by anonymouse64** [comment]
Re-opening this since #770 is done, we can now support persistently starting/stopping services in the snap with parameters. 

The snap executor at https://github.com/edgexfoundry/edgex-go/blob/master/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh should be updated to understand a third argument of enable/disable and if present, pass that along to `snapctl`.

**Comment by jpwhitemn** [comment]
@anonymouse64 - still a Fuji release item?  Label Geneva?

**Comment by anonymouse64** [comment]
If someone ever desires to re-open this and make the snap executor disable services persistently, here is the patch which I wrote that does so (this patch also performs validation on the arguments provided to the executor as per some of the discussion on https://github.com/edgexfoundry/edgex-go/issues/1851):

```patch
From 78eb022fdc24698f024e8558e91d4411a9068343 Mon Sep 17 00:00:00 2001
From: Ian Johnson <ian.johnson@canonical.com>
Date: Mon, 30 Sep 2019 18:13:02 -0500
Subject: [PATCH] sys-mgmt-agent-snap-executor.sh: support enable/disable
 parameters

Also perform validation that the operation provided is either start or stop.

Signed-off-by: Ian Johnson <ian.johnson@canonical.com>
---
 .../bin/sys-mgmt-agent-snap-executor.sh       | 47 +++++++++++++++----
 1 file changed, 39 insertions(+), 8 deletions(-)

diff --git a/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh b/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh
index 0bd3b1a6..c038ce34 100755
--- a/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh
+++ b/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh
@@ -2,9 +2,9 @@
 
 # the first argument is the service
 # the second argument is the operation, one of "stop", "start", "restart"
-# TODO: handle enable/disable when those paramaters are provided
+# the third optional argument is an enable/disable parameter
 
-if [ "$#" -ne 2 ]; then
+if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
     echo "invalid number of arguments"
 fi
 
@@ -17,21 +17,52 @@ case "$#" in
         echo "the operation must be provided"
         exit 1
         ;;
-    2)
+    2|3)
         # correct - do nothing
         ;;
     *)
         echo "too many arguments provided"
-        echo "only the service and the operation must be provided"
+        echo "only the service, the operation and optionally the parameter to the operation must be provided"
         exit 1
         ;;
 esac
 
-
 # note this prefix is in edgex-go, as go code, and if it changes we don't have
 # a good way to pull that here so if this breaks go look for changes there
 svcName=${1#"edgex-"}
 
-# the operation type maps 1:1 to the snapctl service operations
-snapctl "$2" "$SNAP_NAME.$svcName"
-
+if [ -n "$3" ]; then
+    case "$3" in 
+        enable)
+            if [ "$2" = "start" ]; then
+                snapctl start --enable "$SNAP_NAME.$svcName"
+            else
+                echo "invalid parameter $3 for operation $1"
+            fi
+            ;;
+        disable)
+            if [ "$2" = "stop" ]; then
+                snapctl stop --disable "$SNAP_NAME.$svcName"
+            else
+                echo "invalid parameter $3 for operation $1"
+            fi
+            ;;
+        *)
+            echo "invalid parameter $3"
+            exit 1
+    esac
+else
+    # the operation type is supposed to map 1:1 to the snapctl service operations
+    case "$2" in
+        start)
+            snapctl start "$SNAP_NAME.$svcName"
+            ;;
+        stop)
+            snapctl stop "$SNAP_NAME.$svcName"
+            ;;
+        *)
+            echo "invalid operation $2"
+            exit 1
+            ;;
+    esac
+fi
-- 
2.20.1
```
