### ISSUE TITLE
Add an app to the snap to clear the DB

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1490]
When developing device services that are running against the snap, it's useful to be able to clear out the DB entirely. It would be nice if there was a single command which would do this for either Redis or MongoDB exposed from the snap.

**Comment by anonymouse64** [comment]
This is what I've been doing for mongo:
```bash
$ snap stop edgexfoundry.mongod
$ sudo rm -rf /var/snap/edgexfoundry/current/mongo/db/*
$ snap start edgexfoundry.mongod
$ snap start edgexfoundry.mongo-worker
```

**Comment by anonymouse64** [comment]
Similarly it would be nice to have something to clear out Consul...

**Comment by anonymouse64** [comment]
Assigning this to @knitzsche

**Comment by anonymouse64** [comment]
Since this is just a nicety I think it's fine for this to slip to Geneva

**Comment by andresrinivasan** [comment]
To clear Redis, send the [FLUSHALL](https://redis.io/commands/flushall) command.

```
redis-cli flushall
```

**Comment by tonyespy** [comment]
As there's mongo is being deprecated as of Geneva, and this can be done via a single redis-cli command, I'm closing this.

**Note** - since redis authentication is enabled by default, the user needs to grab the redis password from the password file and specify on the command-line using the -a option or via the REDIS_AUTH environment variable (more secure).
