### ISSUE TITLE
Create common EdgeX error type

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1513]
# 🚀 Feature Request

### Relevant Package
All core services and possibly consumers of core services.

### Description
At the `router` level in the EdgeX services, there is a lot of logic regarding error handling. Specifically type checking and mapping to a relevant HTTP response code. For example,
https://github.com/edgexfoundry/edgex-go/blob/03f28e5980c37459c208a296556b0d148bea68db/internal/core/metadata/rest_deviceprofile.go#L108-L117

### Describe the solution you'd like
I think we can create a common error type which encapsulates all the necessary data(HTTP response code, description, etc...) so that when errors bubble up to the `router` we can  simply extract the HTTP response code, rather then checking for a specific type and duplicating the logic. This is more evident as we are incorporating the operator pattern in the REST handlers where we are attempting to abstract the business logic from the REST handler and have the operator simply return an error to the caller(REST handler). For example,

https://github.com/edgexfoundry/edgex-go/blob/818be3dfd721e644cbac9b5acdcbef0f0d1fb2ce/internal/core/metadata/rest_device.go#L88-L89

Taking this a step further, I think we can create an `interface` to which all of our custom errors would conform. We can than return that `interface` type in our functions(rather than the standard `error`)

Going even further, I think this will allow us to communicate errors more effectively to clients. Right now, we rely solely on the HTTP status code. If we standardise the errors we would be able to respond to the user with the common error marshaled in the response body. This would allow the client to serialise the custom error type and handle the information how they want, most likely log.

### Describe alternatives you've considered
None, the alternative to this feature is to continue to handle errors as we are today.

**Comment by tsconn23** [comment]
I want to make sure you're aware of this type in [go-mod-core-contracts](https://github.com/edgexfoundry/go-mod-core-contracts/blob/ab099800f5bf055fb95c35604f41f5c22f3c7434/clients/types/errors.go#L33)

That error type is used for service to service interactions. The use case is that Service A calls Service B. Some error happens in Service B and the call returns to Service A. When Service A replies to _its_ caller, we want the details of Service B's error to be passed through.

Having said, that, it sounds like you're referring to something else -- whereby the error type checking we currently perform is encapsulated within a more streamlined API for use in the router. This layer would need to handle errors caused by a service to service call and also errors that cause an in-process unwinding of the stack. The type checking of errors from the lower layers shown in the example above would be wrapped by the proposed type. If that's correct, is your proposal to adopt this on a service by service basis or to implement something across the platform?

**Comment by AnthonyMBonafide** [comment]
The `ErrServiceClient` does handle the functionality I am referring to regarding service to service communication, I completely missed that :disappointed:.

I was thinking of implementing something for the lower layers across the platform for consistency and possibly reduction in code.

**Comment by AnthonyMBonafide** [comment]
As I thought about this a little more, I realized that the `ErrServiceClient` is one half of the issue I am mentioning. The `ErrServiceClient` is useful when the client receives an error from another API and turns an HTTP response code and body into a struct to be bubbled up the call stack. The other half of this is the invoked API does not return useful information to the client. For example, in some of our creation APIs we return `true` if the operation is successful, but return only a status code(500,404,419,etc) when the operation fails. The client is never given any additional information, like a message, description, or reason. What I am proposing here is that from the invoked API's perspective we use a common "error struct"  when responding with a non 2xx response. That way the client can then translate that common error into an `ErrServiceClient` with the body and status code populated. This will allow the client to handle the error more effectively. Futhermore, using a common struct will allow us to respond in the appropriate format, like `JSON` or `YAML`. 

I am thinking from the two different perspectives when it comes to this issue:

1. A non-EdgeX-service invoking EdgeX APIs - The current implementation can make it difficult when dealing with non 2xx responses as the problem may not be clear to the client.

1. Distributed EdgeX platform - Tracing an error can be more difficult if the information as to why a request failed is only located within the logging system of the API which generated the error.

**Comment by tsconn23** [comment]
>  What I am proposing here is that from the invoked API's perspective we use a common "error struct" when responding with a non 2xx response.

Related https://github.com/edgexfoundry/edgex-go/issues/1573
