### ISSUE TITLE
Add consul support for security-proxy-setup to retrieve configuration file.

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1539]
Currently security-proxy-setup gets the configuration file either from the local file system or command line parameters. The option to retrieve configuration from consul ( similar to other microservices ) needs to be added.

**Comment by AnthonyMBonafide** [comment]
One thing I noticed was that we are using the TOML type List/Array for the SNIS configuration property which is mapped to a slice of strings(`[]string`).

This property:

https://github.com/edgexfoundry/edgex-go/blob/a8c98aa17145faa549b1f7c47218a0b48e2b4e89/cmd/security-proxy-setup/res/configuration.toml#L51

gets loaded into this field:

https://github.com/edgexfoundry/edgex-go/blob/bffbfbb22ffcf4af19cdb9abd2bfdafab25ed54a/internal/security/proxy/kongParameters.go#L90

This might be a problem when populating Consul via config-seed as the result will be a directory named `SNIS` and entries where the key is the slice index(i.e. 0,1,2,etc.) and the values being the strings(in this case `edgex-kong`). I am not sure if this is how you represent Lists in Consul, I did some digging and could not find anything. The other half of the issue is that the current unmarshaling mechanism we are using will panic when trying to load the configuration with the layout created by config-seed. I wanted to make a note of this so that if we find away around this I would like to also apply that to the pattern we use when integrating the `SecretClient` into the core-services and loading this configuration:

https://github.com/AnthonyMBonafide/edgex-go/blob/2e28b9be966421ef6321ac3a0cb60d92e0ca15f1/cmd/core-data/res/configuration.toml#L62

**Comment by lenny-intel** [comment]
@AnthonyMBonafide , good catch on this. The problem is that Arrays are not supported by the Consul API we use to pull the configuration from Consul. We need avoid use of arrays and use CSV strings in these cases.

**Comment by tingyuz** [comment]
Since it is decided that no configuration changes for Geneva and we will be introducing break change for the next major release, I would propose an option as below:

1. Leave the code and configuration as it for Geneva,
2. For the next major release, we need to change the SNIS from array to CSV string so that the SNIS will be like this
```
SNIS = "edgex-kong,localhost,whatever"
```
3.  Before calling SNIS directly, we may need a function call to convert CSV string to array 
```
https://github.com/edgexfoundry/edgex-go/blob/66410e18d718e37ade8ffa971b6c490420a0802d/internal/security/proxy/service.go#L176

# something like below:
Snis: FromCVStoArray(s.configuration.SecretService.SNIS)
```

**Comment by lenny-intel** [comment]
> * Leave the code and configuration as it for Geneva,

@tingyuz , this was like this in Fuji? Doesn't it cause a panic when reading it back from Consul? I.e. this is a bug that needs to be addressed.

**Comment by lenny-intel** [comment]
@tingyuz , never-mind, I didn't look at the topic for this issue. So it currently ins't using consul.... so no bug.

**Comment by tingyuz** [comment]
This is being covered by https://github.com/edgexfoundry/docker-edgex-consul/pull/26

**Comment by tingyuz** [comment]
This issue was discussed in security wg meeting on April 15th ( meeting notes reflects the details ). Bryon suggested to move this configuration to internal since no customer seems interested in the feature for now. We will check with Tony and make decision.

**Comment by tonyespy** [comment]
I'm not sure what _move this configuration to internal_ means?

**Comment by tingyuz** [comment]
Instead of exposing the configuration through config file, Bryon's proposal is to make it as part of internal structure so customers won't be able to modify it. 
I am OK to push it back to icebox for the future version as it is same as the point 1 in my previous comments.

**Comment by jpwhitemn** [comment]
This is in core working backlog.  It appears to be worked in security WG.  Is there a part of this that is core WG?  Putting this in Core WG icebox for now too.

**Comment by hutchic** [comment]
during security pre-wire planning the security working group decided we will close this as won't fix. Reasoning and discussion is in the recorded zoom as well as recorded on the security working group pre-wire wiki document
