### ISSUE TITLE
Apply Operator Pattern Get/Delete NotificationByID 

### ISSUE THREAD

**Issue by nkstanchev** [edgexfoundry/edgex-go#1588]
This issue addresses the transition of the Notification endpoints for GET and DELETE by id to the operator pattern and the addition of the accompanying unit tests.

**Comment by anonymouse64** [comment]
Could you add more detail to this issue please? It's not clear what this issue is about from the title.

**Comment by tsconn23** [comment]
@nkstanchev To support your work here, I have created work items in the project below for all of the support-notifications service endpoints.

https://github.com/edgexfoundry/edgex-go/projects/11

Go ahead and expand your PR associated to this issue to include the DELETE operation as well since that one route handles two different HTTP verbs. Also please update the issue description accordingly.

The way this flow works is that when you are ready to take on another task, go to the project workboard and identify the task you want to work on. Create an issue for it and then put the issue URL in the work item so we know it's assigned to you. Then drag it over to the "In Progress" column. I've done this with this issue so you can see what I mean.

**Comment by nkstanchev** [comment]
@tsconn23 @anonymouse64 I've updated the title and the description. I hope it's better now.
Thank you Trevor for the work items and the explanation!
