### ISSUE TITLE
Add new endpoint for obtaining service version

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#1596]
# 🚀 Feature Request

### Relevant Package

 This feature request is for...
All supported services

### Description

The earlier intention was to provide version information via the ping endpoint. However this did not land in Edinburgh and as Fuji will not change existing APIs, ping will continue to return "pong" until at least Geneva.
In lieu of the above, provide a new endpoint "version" which will return the version in a simple JSON response type.
`{"version":"v1.1.0"}`
This issue obsoletes #1449

**Comment by tsconn23** [comment]
Question -- Should this endpoint be served from the root rather than as `/api/v1/version`?

The reason is that in v2, the v1 api endpoints will still be there for backward compatibility. We won't want to dual implement a version endpoint (e.g. `/api/v1/version` and `/api/v2/version` and so on) and it seems odd that `/api/v1/version` would return `{"version":"v2.1.3"}`.

So possibly this route should be `/api/version`

**Comment by anonymouse64** [comment]
+1 for `/api/version`
