### ISSUE TITLE
Fix typo in option name pertaining to verifying HTTPS hosts

### ISSUE THREAD

**Issue by mkbhanda** [edgexfoundry/edgex-go#1651]
Reported by @anonymouse64 in the context of https://github.com/edgexfoundry/edgex-go/pull/1627
The option name for not verifying HTTPS hosts has a typo in it in  
cmd/security-proxy-setup/main.go:

flag.BoolVar(&ensureSkipVerify, "insureskipverify"

**Comment by tsconn23** [comment]
I want to confirm -- this changes the flag's name making it different from the Edinburgh release. As per the internal variable being used, it should be `ensureskipverify`. Or, if we're going to change the spelling anyway we could call it something that makes sense. This change needs to be included in the security-related release notes for Fuji.

**Comment by anonymouse64** [comment]
While the flag was in Edinburgh, since it was obviously a typo I think it's okay to fix it, since you can fix bugs from a previous release even if "fixing" the bug is an incompatible change because anything relying on it is effectively relying on buggy behavior.

As to the name of the user-facing option, I like `--insecure-skip-verify` or maybe `--insecure-https-skip-verify` since that's even more clear what the option does. 

As to the variable name, I think it should be something like `insecureSkipVerify` to match the option name.

**Comment by mkbhanda** [comment]
Could catch on needing to capture in Fuji release notes @tsconn23.
@anonymouse64 is the naming logic "insecure" ==> what it makes the system
skip-verify or host-skip-verify or https-skip-verify (most informative) .
My vote: --insecure-https-skip-verify

**Comment by scsosna99** [comment]
Quick check indicated no real standard: --insecure, --no-check-certificate, --disable--ssl-verify, --trust-server-cert, --tls-skip-verify, --disable-tls-checks.

IMO --insecure-https-skip-verify actually seems less understandable because there's multiple meanings baked in: is it insecure because we're not verifying or are we skipping the insecure verification.  And it's kind of long to remember.

I suggest either --tls-skip-verify or --disable-ssl-verify, both are succinct and clearly indicate a functionality change.

**Comment by scsosna99** [comment]
Should we also standardize the internal naming to match?  Currently it's InsecureSkipVerify in common.go, would we want to change it to be TlsSkipVerify or SslVerifyDisable or InsecureHttpsSkipVerify?  Makes it easier to understand but touches a lot of files.

**Comment by anonymouse64** [comment]
> IMO --insecure-https-skip-verify actually seems less understandable because there's multiple meanings baked in

I disagree, I read this option name as "run this command in an insecure manner by skipping https verify", but perhaps that's an uncommon reading.

**Comment by scsosna99** [comment]
> I disagree, I read this option name as "run this command in an insecure manner by skipping https verify", but perhaps that's an uncommon reading.

You might have nailed it, not that it's an uncommon reading but perhaps one of multiple meanings, which may add confusion.  I think/hope that --disable-ssl-verify conveys only one distinct meaning, more difficult to misinterpret.

I'm low person on the totem pole so if someone wants to be the benevolent dictator and decide, great, I'm willing to make the changes, just don't want to do them twice.

**Comment by anonymouse64** [comment]
Some folks are at a conference this week, so let's defer the decision to next week's security WG meeting in that case.

**Comment by scsosna99** [comment]
np, I'll try and join the WG next week.  Is the next meeting on the 28th?

**Comment by anonymouse64** [comment]
> np, I'll try and join the WG next week. Is the next meeting on the 28th?

Yes

**Comment by tingyuz** [comment]
I believe this has been fixed for security-secretstore-setup but not for security-proxy-setup. Will open a PR to address this soon.
