### ISSUE TITLE
Device profile name became empty string, when updating device profile and the request body didn't contain name

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1668]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Upload device profile by "http://localhost:48081/api/v1/deviceprofile/uploadfile" using attached yaml file. 
[sample_profile.yaml.txt](https://github.com/edgexfoundry/edgex-go/files/3505528/sample_profile.yaml.txt) (Please rename the file to sample_profile.yaml before upload file).
2. Find the device id and modify the device profile using the following API and request body.
> Method : PUT
> URL : http://localhost:48081/api/v1/deviceprofile
> {
>     "id": "{{deviceprofileId}}",
>     "description": "Test DeviceProfile after PUT",
>     "coreCommands": [
>       {
>         "id": "57f4995be4b060e268aeb084",
>         "name": "cooling point1",
>         "get": {
>           "response": {
>             "errorDescription": "Integer Value",
>             "expectedValues": "temperature"
>           }
>         },
>         "put": {
>           "response": {
>             "errorDescription": "Integer Value",
>             "expectedValues": "temperature"
>           }
>         }
>       }
>     ]
> }

## 🔥 Exception or Error
<pre><code>

Get the device profile by api http://localhost:48081/api/v1/deviceprofile/yaml/{deviceprofile id}
Only get the following data.
```
modified: 1565868865522
description: Test DeviceProfile after PUT
 id: ca97f3d3-f842-4ae7-a1bd-c4d6722b338f
coreCommands:
   - name: cooling point1
```

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** ubuntu18.04

**EdgeX Version:** master

**Anything else relevant?**

**Comment by AnthonyMBonafide** [comment]
I am assuming that the suggestion here is: if a `name` is not present in the update request body we will not change the name. If this is the case, then is this only true for `name` or should this apply the same logic to all the fields? If this does apply to all the fields then we will not be able to perform an implicit delete for any nest entities, such as `ValueDescriptors`, because we will then be assuming that since the request does not contain that information it is to be unchanged. 

I think we should simply return a `400(Bad Request)` for situations that do not contain a name or if it is blank. I think of the update request body to be the desired state the client wishes the entity to be in after the request has been successfully processed.

@tsconn23, any thoughts

**Comment by tsconn23** [comment]
Device Profile model validation expects either ID or Name to be populated. If the ID is provided on the request but not the name, the update logic should not blank the name out (since it is effectively part of the unique identifier). All other fields should be updatable. The effect of the above request on the `coreCommands` will be to only retain `cooling point1`. The `coreCommands` specified in the sample YAML file as well as the `deviceCommands` will be eliminated. The proper way to use a PUT is to specify the totality of the document you are trying to update, not specify some marginal piece of it expecting that bit to be applied in a larger document.

See [here](https://restfulapi.net/rest-put-vs-post/)
```
Use PUT when you want to modify a singular resource which is already a part of resources collection. PUT replaces the resource in its entirety. Use PATCH if request updates part of the resource.
```
We do not currently have PATCH operations in our API. As a PUT the above request is telling the device profile that we don't care about the prior definition. Now we just want to have a single `coreCommands` entry on the given profile. Except for the elimination of the name, this behavior is as expected @cherrycl
