### ISSUE TITLE
Return code should be 409 when the device profile contains duplicate names in device profile commands

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#1670]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-metadata

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction
1. Upload device profile and the file contains duplicate names in device profile commands.
[sample_profile_duplicated_command.yaml.txt](https://github.com/edgexfoundry/edgex-go/files/3505522/sample_profile_duplicated_command.yaml.txt)
(Please rename the file to sample_profile_duplicated_command.yaml before upload file).
> curl -F 'file=@sample_profile_duplicated_command.yaml' http://localhost:48081/api/v1/deviceprofile/uploadfile -v

expected result : return code should be 409, not 400.
## 🔥 Exception or Error
<pre><code>

< HTTP/1.1 400 Bad Request
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Thu, 15 Aug 2019 12:31:11 GMT
< Content-Length: 43
* HTTP error before end of send, stop sending
<
duplicate names in device profile commands
* Closing connection 0

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** ubuntu 18.04

**EdgeX Version:** master

**Anything else relevant?**

**Comment by AnthonyMBonafide** [comment]
I do not agree that the response code should be [409(Conflict)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409) when the request contains duplicate names. A `409` indicates there is a conflict with current state of the server, which is not the case here. The request is invalid because it violates a business requirement that can be identified before processing the request. To me a [400(Bad Request)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400) is the better, more clear response to the client. 

@tsconn23, any thoughts?

**Comment by tsconn23** [comment]
Well, formally speaking we can't change it from 409 since that's what is published in the [1.x API spec](https://docs.edgexfoundry.org/core-metadata.html#deviceprofile_upload). To modify it would not be backward compatible. I also think 409 works personally because the server-side state (what's in the DB) indicates an entry for the given name is already present, thus adding a duplicate is in conflict with our business requirements. I strictly limit 400 errors to mal-formed contracts -- either unparseable JSON or missing required fields / out of range values on the request.

**Comment by AnthonyMBonafide** [comment]
I agree we cannot change it and it has to be reverted to a `409`. However, I still think `409` does not apply here as the reason we are getting the error is because we cannot unmarshal the request body since it fails in the `Validate` function as seen here:

https://github.com/edgexfoundry/go-mod-core-contracts/blob/1a837e55fdcec387f13a9264a7b93c1f47d814b8/models/deviceprofile.go#L127-L148

**Comment by tsconn23** [comment]
Oh, I read this as duplicate device profile names -- not as commands in the request. Then yes, I agree this should be a 400 Bad Request.

**Comment by AnthonyMBonafide** [comment]
Also, I think this `503(Service Unavailable)` is both wrong and breaking backwards compatibility and it should be `500` as per the RAML:

https://github.com/edgexfoundry/edgex-go/blob/86c40c7972745d23b935c2c300b436537df68d8d/internal/core/metadata/rest_deviceprofile.go#L248-L253

@tsconn23 , should I fix this as well?

**Comment by tsconn23** [comment]
Yes, as long as the RAML isn't documenting the return of the 503
