### ISSUE TITLE
Standardize Error Types to NOT Use Pointers

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1671]
We have a number of custom error types in EdgeX such as those found here

- [core-data](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/data/errors/types.go)
- [core-metadata](https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/errors/types.go)

Older exception types are defined in a manner where their `New()` functions [return a pointer](https://github.com/edgexfoundry/edgex-go/blob/7ef8bff0a329065968754ab0ab9affabe0155e66/internal/core/data/errors/types.go#L104)

Over time, new exception types have been added wherein the `New()` function [does not](https://github.com/edgexfoundry/edgex-go/blob/7ef8bff0a329065968754ab0ab9affabe0155e66/internal/core/metadata/errors/types.go#L119) return a pointer.

We need to ensure universal implementation on this and right now, I'm of the opinion that these error types do not need to be returned from their `New()` functions as pointers. They're small, don't have any pointers as members and we want them to be immutable.

Along with reconciling these definitions, switch statements used for type checking should no longer expect pointers. Example of current code:

```
switch err.(type) {
		case *types.ErrDuplicateName:
			http.Error(w, err.Error(), http.StatusConflict)
		case *types.ErrItemNotFound:
			http.Error(w, err.Error(), http.StatusNotFound)
		default:
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
```
The pointer dereference will need to be removed from all such statements.

**Comment by brandonforster** [comment]
It might be worth exploring the `Kind` paradigm described in the GopherCon errors talk instead of messing with this.

**Comment by tsconn23** [comment]
@brandonforster Are you volunteering? Can you provide more details?

**Comment by brandonforster** [comment]
@tsconn23 

https://about.sourcegraph.com/go/gophercon-2019-handling-go-errors

It's certainly a lot more work than what is being described here, but I feel like having a short description for the error instead of having a `type`, a factory method and an `Error()` implementation is probably both more extensible and maintainable.

I can work on this if it's scheduled appropriately, or even just as something in my background.

**Comment by anonymouse64** [comment]
We use the Kind paradigm in snapd for errors. For example see:

https://github.com/snapcore/snapd/blob/master/daemon/response.go#L151

and 

https://github.com/snapcore/snapd/blob/master/client/client.go#L420

and 

https://github.com/snapcore/snapd/blob/master/client/client.go#L471

and 

https://github.com/snapcore/snapd/blob/master/cmd/snap/cmd_login.go#L83

for an example of how we use this paradigm. Basically you have constants that represent errors of specific types, and instead of returning just a `err`, you return a type that implements the `error` interface, and you can introspect that, either with exported `IsSomeKindError` methods, or you can type-cast the `error` to the `errorValue` type and inspect the `Value`, `Message` and `Kind` directly. We have a bit more requirements here, as we have to communicate an error kind across HTTP from the daemon to the client, but hopefully that helps.

To be clear, I am not volunteering any work, just volunteering an example :smiley:

**Comment by jdharms** [comment]
@brandonforster I would be interested in helping implement this refactor in spare cycles as well.

**Comment by AnthonyMBonafide** [comment]
I created a new issue #1734 which is intended to address the concerns regarding a refactor to improve the error handling strategy(Kind paradigm). I am going to address the issue originally proposed in the issue, which is errors being inconsistently used as either values or references rather than just values.
