### ISSUE TITLE
Implementation of Loading kong cert pair from filesystem to Vault in security-secretstore-setup.

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1675]
PKI cert pair for KONG API-gateway is created by security-secret-setup and saved into volume. Security-secretstore-setup need to load such cert pair into Vault so that the initialization process of API-Gateway can obtain them from there and apply on the path of API-Gateway.

**Comment by bnevis-i** [comment]
For separation of concerns, I'd like to see this as a separate utility. Perhaps we can name this after config-seed and call this security-seed?

 * This utility must block on consul waiting for Vault to show as "up"
 * This utility must block on the Kong TLS certificate becoming available on the file system
 * This utility should verify Vault's TLS certificate against the CA
 * We need to allow for the later replacement of a custom Kong certificate or transient certificates generated per-boot.  Thus:
   - Should add a new key secret/edgex/pki/tls/edgex-kong/auto-generated=true/false/missing  (existing code has key= and cert= as well)
   - if no keys exist under secret/edgex/pki/tls/edgex-kong, import the key, cert, and set auto-generated=true for the newly imported info
   - if key= exists and auto-generated=true, compare key= and cert= and replace them if they are out of date
   - otherwise do not touch the existing kong certificate (it may have been placed there manually).

**Comment by mkbhanda** [comment]
Thank  you Bryon for laying out the steps.
I think this is valuable too to add into issue https://github.com/edgexfoundry/edgex-go/issues/1710 -- dependency tracker

**Comment by bnevis-i** [comment]
@mkbhanda good catch, in fact, it is captured in the screen shot where I note "check that initial secrets have been provisioned", but I also edited my comment above to explicitly mention that this step needs to be part of the security dependency tracker.

**Comment by jdharms** [comment]
Some changes I made while addressing code review broke this feature and they slipped through my testing. I've opened #1813 to address these issues.
