### ISSUE TITLE
Create Vault access tokens for different roles of EdgeX in Security-secretstore-setup

### ISSUE THREAD

**Issue by tingyuz** [edgexfoundry/edgex-go#1677]
Currently all the micro services in EdgeX is utilizing master token of Vault to access credentials in Vault. It is needed to create different tokens based on different roles in Security-secretstore-setup.

**Comment by bnevis-i** [comment]
Suggest that this component be a standalone service that runs in the egdex-vault-worker container (TOKEN_SERVER=file-token-server) Its job is to generate per-service Vault tokens for all of the Edge services that need Vault-based secret storage.

file-token-server must to the following:
 * Needs to regenerate the root token and create a token-issuing-token. 
 * While it still has the root token, it needs to enumerate and revoke all previously issued tokens. (Resolves current bug in legacy token server where new tokens are issued, but old tokens live on in the Vault DB)
 * Revoke the root token that it just created, and drop privileges by using the token-issuing-token would be used for the remainder of execution.
 * Needs to verify Vault against the CA
 * It needs to record the fact that it has executed on volatile storage that will be cleared on the next boot (e.g. in /run), so that if the service is restarted for any reason other than a complete restart, it doesn't blow away active tokens.
 * Needs to iterate some configuration (WIP) to generate policies and tokens on a per-service basis.
 * Each token file should be generated in a service-specific directory to facilitate fine-grained access control for individual containers.

The nature of the configuraiton file that drives file-token-server is still WIP.

**Comment by tingyuz** [comment]
This is the feature that token-server will implement. Assign this issue to self to track the progress.

**Comment by tingyuz** [comment]
@bnevis-i I will assign the ticket since you are the one who is working on it actually. Thanks!

**Comment by anonymouse64** [comment]
I don't think this was fully completed, just the first PR was merged

**Comment by bnevis-i** [comment]
Reopen - not done yet.

**Comment by bnevis-i** [comment]
New requirement: ability to set permissions/owner/group on created token files.

**Comment by bnevis-i** [comment]
Reopening.  Needs one more PR to turn the feature on.
