### ISSUE TITLE
Error Handling Refactor

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#1734]
# 🚀 Feature Request

### Relevant Package
Core services and possibly mod-core-contracts

### Description
The way we are creating, handling, and logging errors causes a lot of duplicate code and does not provide a clear consistent pattern to be used across the board. For example, the translation of error to an HTTP response is duplicated in many REST handlers across core service:

https://github.com/edgexfoundry/edgex-go/blob/087ead41cf58c57bbed4836ce723319706201d7e/internal/core/metadata/rest_deviceprofile.go#L108-L119

As for logging, there are some situations where we are logging multiple times for the same error. For example, in the `restGetAllDeviceProfiles` REST handler a `ErrLimitExceeded` is logged within the operator:
https://github.com/edgexfoundry/edgex-go/blob/8627af8819795f333cf7a38c6bcd9bb746df233b/internal/core/metadata/operators/device_profile/get.go#L37

and the error is bubbled up to the REST handler and again logged with less context:
https://github.com/edgexfoundry/edgex-go/blob/087ead41cf58c57bbed4836ce723319706201d7e/internal/core/metadata/rest_deviceprofile.go#L39

### Describe the solution you'd like
A pattern, paradigm, and/or strategy which will standardize the common functionality used when dealing with errors so that we can eliminate duplicate code and improve logging. Possibly do this in a non-invasive fashion to minimize the work that needs to be done to adopt these new ideas.

If possible I think it would be nice if we can also address the issue of inconsistent response bodies when an error is encountered. In an effort to harden our APIs I think we should always respond to a request with a proper content type and response body which adheres to that content type. Also, we should come up with an error structure so that clients can unmarshal the error response and use pro grammatically. 

### Describe alternatives you've considered
A proposal has been made and presented in core working group meetings on [August 22nd](https://zoom.us/recording/share/b823jU0h-MM0HOTFMCfgCccyZCORgNdILX3jAaNZdF6wIumekTziMw) , and [August 29th](https://zoom.us/recording/share/N7VEYfqTC8bSvO7c12TdT4VTdbf4ojao4uY4-T85x4CwIumekTziMw). 

You can find the code presented in those meetings:
edgex-go: https://github.com/AnthonyMBonafide/edgex-go/tree/proposal/issue_1671-common_error_type_and_handling

mod-core-contracts: https://github.com/AnthonyMBonafide/go-mod-core-contracts/tree/proposal/issue_1671-common_error_type_and_handling

The changes in `mod-core-contracts` are needed to build the changes in `edgex-go`. See the commit messages for more details.

**Comment by jbonafide623** [comment]
In looking at the proposal, I do have some questions regarding this approach to error handling.
With our current approach to error-handling (albeit a non-standardized approach), we do gain the benefit of each entity fine-tuning their own error-checking. For instance, the device_profile entity may only be concerned with StatusNotFound and InternalServerError. With that, there is a simple check (switch statement) to resolve the status code for the given error. 

Are there going to be some benchmarks for this proposal which can further spell out an performance changes with this new approach? My thought is that when we isolate error-checking into a single place and have to ensure that we are properly handling the variety of errors, are we sure that there are no performance hits in doing so.

After talking with @AnthonyMBonafide today about general performance hits on any new error-checking, he mentioned that we may want to evaluate the performance affects on this new approach given the Error wrapping feature introduced in Go 1.13 https://golang.org/doc/go1.13#error_wrapping

Just something of note/question while working on #1745

**Comment by mkbhanda** [comment]
Any advantage of tracking all error codes and messages centrally is for localization, a single place to look and translate these strings. When Edgex is wildly successful/adopted, this is useful because errors traditionally are user facing


---
Sent from Workspace ONE Boxer<https://whatisworkspaceone.com/boxer>

On September 13, 2019 at 10:49:58 PM GMT+5:30, Jason Bonafide <notifications@github.com> wrote:

In looking at the proposal, I do have some questions regarding this approach to error handling.
With our current approach to error-handling (albeit a non-standardized approach), we do gain the benefit of each entity fine-tuning their own error-checking. For instance, the device_profile entity may only be concerned with StatusNotFound and InternalServerError. With that, there is a simple check (switch statement) to resolve the status code for the given error.

Are there going to be some benchmarks for this proposal which can further spell out an performance changes with this new approach? My thought is that when we isolate error-checking into a single place and have to ensure that we are properly handling the variety of errors, are we sure that there are no performance hits in doing so.

After talking with @AnthonyMBonafide<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnthonyMBonafide&data=02%7C01%7Cmbhandaru%40vmware.com%7C3aeee8dd1f504202e6d308d7386e9862%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637039919972726680&sdata=RTNo%2F8FcyvEEVWLmJBhJWuMzU5lWFN7SiiBsHyxx4pI%3D&reserved=0> today about general performance hits on any new error-checking, he mentioned that we may want to evaluate the performance affects on this new approach given the Error wrapping feature introduced in Go 1.13 https://golang.org/doc/go1.13#error_wrapping<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgolang.org%2Fdoc%2Fgo1.13%23error_wrapping&data=02%7C01%7Cmbhandaru%40vmware.com%7C3aeee8dd1f504202e6d308d7386e9862%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637039919972726680&sdata=EmEAXak7ESRBLdFf%2BiE5CaTWv7IuYnLnZQSGaCMtvNg%3D&reserved=0>

Just something of note/question while working on #1745<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fedgexfoundry%2Fedgex-go%2Fissues%2F1745&data=02%7C01%7Cmbhandaru%40vmware.com%7C3aeee8dd1f504202e6d308d7386e9862%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C637039919972736674&sdata=iyYyAcpSyAbN7%2BTXF4F%2FHe55%2BV%2B2tgayWBxjulngDxI%3D&reserved=0>

**Comment by jdharms** [comment]
I don't imagine there will be much of a performance hit at all, based on the proof of concept code that @AnthonyMBonafide has in the branches linked above.  There are a couple of endpoints that have been reworked to use the "new" error-handling flow in these branches.  I'm sure you could use Go's benchmarking tools to figure out if there's a significant performance impact based on this.

**Comment by cloudxxx8** [comment]
I would like to work on this with V2 API
