### ISSUE TITLE
Add minimum supported Go version to go.mod

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#1826]
Locally, I've upgraded to Go 1.13 to test it out. The project hasn't officially rev'ed to that version yet. One of the things I notice is that when I do a build, an entry indicating `go 1.13` as the minimum supported version is put into the `go.mod`. According to the following article, we should have started seeing this behavior with Go 1.12, but I don't recall that being the case

https://golang.org/doc/go1.12#modules

I wouldn't want this to be checked in as `go 1.13` until the project moves to that version. I've tested compilation of the edgex-go services locally with the version directive set to `go 1.12` and everything works as far as I can tell. Again, this directive is only indicating a minimum supported version.

I think we should do this fairly soon as we could easily get contributions from people who've upgraded to Go 1.13 and who might miss this small edit.

**Comment by jpwhitemn** [comment]
Trevor - based on what I read, it sets this by default to the current release if it is not set (which is what you saw when you rev'ed to 1.13).  -> "It will be set to the current release (go 1.12) if no existing version is present."So I am wondering if we just want to leave it out of go.mod and let the default continue to apply.  That way we don't have to have the lock in to the version.  For example, when we do move to 1.13, I presume (maybe incorrectly) that what we do still would compile and work with 1.12 since we aren't using any feature of 1.13 explicitly.  But if we start updating all the go.mods, doesn't this require any developer to have to upgrade to 1.13 (or change their go.mod file back to 1.12)?
In other words, unless we really have a min supported Go that we work with (perhaps that is 1.0 for us??) why set this and artificially require developers to move up when it really isn't necessary?  Shouldn't we use the "minimum required" to indicate just that - minimum and not what we are currently working with?

    On Wednesday, September 25, 2019, 7:47:22 PM GMT+1, Trevor Conn <notifications@github.com> wrote:  
 
 
Locally, I've upgraded to Go 1.13 to test it out. The project hasn't officially rev'ed to that version yet. One of the things I notice is that when I do a build, an entry indicating go 1.13 as the minimum supported version is put into the go.mod. According to the following article, we should have started seeing this behavior with Go 1.12, but I don't recall that being the case

https://golang.org/doc/go1.12#modules

I wouldn't want this to be checked in as go 1.13 until the project moves to that version. I've tested compilation of the edgex-go services locally with the version directive set to go 1.12 and everything works as far as I can tell. Again, this directive is only indicating a minimum supported version.

I think we should do this fairly soon as we could easily get contributions from people who've upgraded to Go 1.13 and who might miss this small edit.

**Comment by anonymouse64** [comment]
We should move the version of Go up as the project moves on because older releases of Go are not maintained and as such could have security vulnerabilities in them, etc. I think it's reasonable to say that the project's minimum Go version is the oldest one currently supported by the Go team (i.e. right now that's Go 1.13, Go 1.12 and Go 1.11, see https://golang.org/doc/devel/release.html#policy)

That is until we start needing specific features from Go 1.13, etc.

**Comment by tsconn23** [comment]
@jpwhitemn 
> In other words, unless we really have a min supported Go that we work with

We DO have a minimum version required, as we said on the Core WG call, and that's Go 1.12.x because of the module capabilities. I still advocate setting this to `go 1.12` instead of `go 1.11` because as we know, Go 1.11 was a "preview" of modules with the official support coming in 1.12.

**Comment by anonymouse64** [comment]
+1 to set go 1.12 as the minimum, and then when go 1.15 is released, bump that to 1.13, etc.
