### ISSUE TITLE
SMA should validate parameters passed to the service executors

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#1851]
Continuing from https://github.com/edgexfoundry/edgex-go/issues/770#issuecomment-536821382 ...

The SMA should validate parameters passed to it via HTTP before passing those parameters to the executors. 

> By definition, parameters are passed through the agent to an executor as-is without verification.

Sorry I haven't been attending the SMA meetings regularly recently, but where was this decided? 

> I'd propose we leave it to the executor to validate and ignore incoming parameters based on the requirements of its specific implementation.

I disagree with this choice specifically because this is exactly the kind of avenue for privilege escalation against the docker socket that I think could be our first critical remote code execution CVE we get hit with after discovering some set of docker options to `start`/`stop`/`restart` allows executing arbitrary containers. 

I also want to apologize for approving the original PR without having thought more deeply about this issue, if folks don't think we can fix this issue specifically in time, I'd like us to revert that PR since I think it's just too big of a security risk to allow arbitrary options to be passed over HTTP to the docker command.

**Comment by michaelestrin** [comment]
> The SMA should validate parameters passed to it via HTTP before passing those parameters to the executors.

I disagree for the reasons stated on #770 and below.

> > By definition, parameters are passed through the agent to an executor as-is without verification.
> 
> Sorry I haven't been attending the SMA meetings regularly recently, but where was this decided?

It's implied.  Unless there's a standard set of optional parameters that each executor implementation is obligated to support, the optional parameters are executor implementation-specific.   This was discussed in passing during today's SMA WG call and consensus seemed to reinforce this and the approach of executor-validation of these parameters.

> > I'd propose we leave it to the executor to validate and ignore incoming parameters based on the requirements of its specific implementation.
> 
> I disagree with this choice specifically because this is exactly the kind of avenue for privilege escalation against the docker socket that I think could be our first critical remote code execution CVE we get hit with after discovering some set of docker options to `start`/`stop`/`restart` allows executing arbitrary containers.

Please explain how modifying the Docker executor implementation to validate and ignore incoming parameters will lead to security risk.  I don't understand.

> I'd like us to revert that PR since I think it's just too big of a security risk to allow arbitrary options to be passed over HTTP to the docker command.

Let's fix the problem -- after we agree on a solution -- instead of reverting the PR.  

I don't understand your assertion of security risk in allowing arbitrary options to be passed over HTTP to an executor implementation.  They're being passed to an executor binary -- which for the executor implemented in edgex-go -- is responsible for executing the docker command.

**Comment by anonymouse64** [comment]
> Unless there's a standard set of optional parameters

I guess I understood the previous issue to be that we _would have enable/disable as standard parameters_. I guess I'm a bit shocked looking today at this code that we don't even do any validation that the operations provided to the HTTP handler are start/stop/restart before it is passed to the binary. We should also do that, and we used to do that. See below for why we should do this validation in as many places as possible from a security perspective. Additionally, I have a few bugs here that I just found I will be filing later that only happen because we don't do any validation (i.e. they are regressions because we used to validate this type of thing but now it seems we don't validate anything).

> Please explain how modifying the Docker executor implementation to validate and ignore incoming parameters will lead to security risk. I don't understand.

My assertion is we should do _both_ types of validation for maximal security. This means that if there's a bug in our docker executor implementation, it will still be protected by the validation done by the SMA. If we don't do any validation in the SMA, then we will be subject _only_ to the security from one part of the system, when we have the opportunity to do extra validation. 

> I don't understand your assertion of security risk in allowing arbitrary options to be passed over HTTP to an executor implementation.

This is _exactly_ where remote code execution vulnerabilities live... When you don't validate that "expected" or valid data is passed to your service from HTTP (which could be from any client) you are essentially passing untrusted user input to something else deeper in the system. For references on this kind of attack, see https://www.owasp.org/index.php/Injection_Theory, https://cwe.mitre.org/data/definitions/807.html, https://martinfowler.com/articles/web-security-basics.html, etc. 

This kind of attack should be especially considered harmful given that this is an IoT framework/application and so it will most likely be attacked with HTTP requests when deployed on a real network.

In general, doing extra validation seems pointless until you or someone else finds a security vulnerability. Having seen these kinds of attacks before, I am suggesting that we do all we can to prevent these attacks before they manifest.

**Comment by michaelestrin** [comment]
> guess I understood the previous issue to be that we _would have enable/disable as standard parameters_

My understanding of our agreement on implementation as documented in #770 is different from yours.  Providing support for enable and disable parameters only was not part of our implementation agreement.  Further, they're not relevant to the example Docker executor in the edgex-go repository.  I have no context for why they're needed, where they'll be used, or how they constitute a standard.

> I guess I'm a bit shocked looking today at this code that we don't even do any validation that the operations provided to the HTTP handler are start/stop/restart before it is passed to the binary. We should also do that, and we used to do that.

I don't agree and maybe it's because I have a different view of the agent/executor relationship.  To me, the agent/executor constitute a single service -- they're in the same bounded context.  I believe they're only separate processes because Golang doesn't support the concept of plugins.  They are tightly-coupled components that are intended to be deployed together.  Further, executor is only ever intended to be called by the agent.

With that view in mind, the agent simply provides routing support and delegates implementation to the executor.  The example executor provided does validate its request content to ensure only start, stop, restart, and metrics operations are supported.

The executor must be responsible/reliable as the rest of the system relative to security.  I don't see the value in having the agent validate the various permutations (that exist now or in the future) that specific executor implementations might require when the individual executor can (and should) be responsible for validating requests it receives.

>When you don't validate that "expected" or valid data is passed to your service from HTTP (which could be from any client) you are essentially passing untrusted user input to something else deeper in the system. 

Again, my perspective of the agent/executor relationship may be different from yours (and from the larger community's).  Agent exists to provide the common plumbing.  Agent delegates to executor.  Executor validates and processes the request and returns a result (which is proxied back to the caller by the agent).  We're validating the input in the executor -- which is really the only place that input can be properly validated.

I see your perspective on having the agent validate input before passing requests to the executor as equivalent to saying our Kong-based security proxy should validate input before it passes requests to EdgeX services for processing.  It doesn't make sense to me.  They're both proxies.

**I'm thinking this is an issue that needs to be discussed in the larger community.  I'm unfortunately not available for the next SMA WG call.  Although I'm not sure how to proceed here, I do know I want to nail down requirements acceptable to the community before reworking any existing implementation.**

**@jpwhitemn to spark larger community discussion and/or guidance.**

**Comment by michaelestrin** [comment]
> I have a few bugs here that I just found I will be filing later that only happen because we don't do any validation (i.e. they are regressions because we used to validate this type of thing but now it seems we don't validate anything).

Please create new issues as quickly as possible so we can evaluate and address the issues you've found in time for the upcoming code freeze.  @anonymouse64

**Comment by anonymouse64** [comment]
> Further, they're not relevant to the example Docker executor in the edgex-go repository. I have no context for why they're needed, where they'll be used, or how they constitute a standard. 

Well I did explain the use case at the top of the issue and we do have 2 executors inside edgex-go, but :man_shrugging:

> I have a different view of the agent/executor relationship

Yes I think this is a different view from my own. Since specifically the executor can be arbitrarily _configured_ by the user when they go to deploy EdgeX, I don't view it to be so tightly coupled with the agent. Additionally, we have **_no_** docs for what all is required for an executor to integrate with the agent, so if someone does implement their own custom executor and deploy it, we shouldn't be requiring them to read through all the code to find that no validation is done and that their executor is responsible for all validation because it's tightly coupled. That's a bad user experience for folks writing the executor, and it's also problematic because they probably won't read all the docs and then upon writing a simple wrapper script like the one we have in the snap (see https://github.com/edgexfoundry/edgex-go/blob/master/snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh for how simple such a script could be implemented outside of docker) could easily expose themselves/their deployment to attacks because they didn't perform arbitrary user input cleaning on the arguments provided to their script. There is precedence in other parts of EdgeX where we code things defensively in the HTTP responses to try and limit attack surface against HTTP attacks, such as the limiting of the size of responses, etc.

>  believe they're only separate processes because Golang doesn't support the concept of plugins.

Yes this is true, but note that because they are a separate process that inflicts additional security vulnerabilities and considerations. We would have less security vulnerabilities if we didn't have to execute configurable executors from inside a HTTP server, but the community decided not to go with Go plugins for various reasons. 

> Further, executor is only ever intended to be called by the agent.

This to me is even more reason why the agent should be performing validation. The executor is only ever called by one thing, so doesn't it make sense that the one thing calling the executor should check arguments on behalf of the executor? This makes implementing executors simpler, easier, and more secure.

> The example executor provided does validate its request content to ensure only start, stop, restart, and metrics operations are supported.

Yes, as it should. It should validate these things, regardless of what other validation is performed because it is a highly privileged executable, it has full access to the docker socket, and thus full access to unconfined root. I will omit a list of docker privilege escalation exploits that exist, but there are many. I think it's useful to think of anything touching the docker socket as effectively running as sudo. 

> our Kong-based security proxy should validate input before it passes requests to EdgeX services for processing

Thank you for providing this example, I think it's useful to work with examples like these. I don't think the agent/executor situation here matches the example of Kong, because Kong's place is not to validate input, it is to authenticate and authorize a user to the EdgeX services. The input validation happens at a layer behind Kong. I'm not saying that the agent should be performing authentication and authorization, I'm saying it should be performing input validation, which is an orthogonal goal to authentication and authorization. It should make sure that the input it receives from elsewhere is sane and valid. I don't feel comfortable having something that is running as sudo performing the _only_ validation, it's one single point of failure to me, which is scary. Additionally, see my above points for why I don't think the agent and executor are tightly coupled. 

I think is a plan for next steps here:

1. yes let's discuss this in a larger community setting, if this issue isn't sufficiently wide enough (it probably isn't), I can join the SMA WG meeting next week
2. let's document for Fuji what is required and expected of an executor implementation based on the results of 2
3. if the community ends up agreeing with me that the agent and executor are not as tightly coupled as you think they are, then we should revert the PR or fix the bug that no validation is performed.

**Comment by anonymouse64** [comment]
> Although I'm not sure how to proceed here, I do know I want to nail down requirements acceptable to the community before reworking any existing implementation.

sorry missed this in my response above, but given this can we at least revert the PR first if we can't discuss this more widely for another 2 weeks? It's relatively cheap to re-commit things and similarly cheap to revert things.

**Comment by jpwhitemn** [comment]
@anonymouse64 Queued up for discussion at next available system management meeting where Michael can attend (2 weeks).  Is the PR with some progress on this long standing request of yours worse than no progress and requires pulling the PR?  Given Fuji freeze will be in a few short weeks, this may slip to Geneva otherwise.

**Comment by anonymouse64** [comment]
> Is the PR with some progress on this long standing request of yours worse than no progress and requires pulling the PR

In my mind, yes it is worse with this PR in than not in, because the PR adds additional surface for potential attacks. Since we won't be able to discuss for 2 weeks, which will then be only 1 week before freeze, I'd prefer to revert now, and then un-revert if needed after we meet. 

It's perfectly okay to me for the feature to slip to Geneva if it means that the implementation has less attack surface.

**Comment by anonymouse64** [comment]
@jpwhitemn @michaelestrin so the next WG meeting that folks can attend to discuss this issue is on the oct 18th at 10 AM central TZ, correct?

**Comment by jpwhitemn** [comment]
correct.  Sys mgmt now meets on Fridays at 10 central and so that is the next available meeting.

    On Friday, October 11, 2019, 9:14:02 AM CDT, Ian Johnson <notifications@github.com> wrote:  
 
 
@jpwhitemn @michaelestrin so the next WG meeting that folks can attend to discuss this issue is on the oct 18th at 10 AM central TZ, correct?

**Comment by jpwhitemn** [comment]
Ian to revert with upcoming PR

**Comment by jpwhitemn** [comment]
@anonymouse64 Ian - I'll let you close out this issue with your forthcoming PR.
