### ISSUE TITLE
Improve core-data add event performance

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#187]
In order to improve the add event performance in core-data, which should be called several times, there are different things which can be done:

1. As said in #128, why use Device property as dual purposed? I think should be better to only allow to use device name

```
// Get device from metadata
deviceFound := true
// Try by ID
d, err := mdc.Device(e.Device)
if err != nil {
	// Try by name
	d, err = mdc.DeviceForName(e.Device)
	if err != nil {
		deviceFound = false
	}
}
```

2. If MetaDataCheck isn't enabled, why get Device name in metadata? This requires some time which should be avoided if MetaDataCheck isn't enabled
```
// See if metadata checking is enabled
if configuration.MetaDataCheck && !deviceFound {
	loggingClient.Error("Device not found for event: "+err.Error(), "")
	http.Error(w, err.Error(), http.StatusNotFound)
	return
}
```
3. Now ValueDescriptorByName is called if ValidateCheck is enabled (inside isValidValueDescriptor) and also if PersistData is enabled. This second check should be removed
```
if configuration.ValidateCheck {
	loggingClient.Debug("Validation enabled, parsing events")
	for reading := range e.Readings {
		valid, err := isValidValueDescriptor(e.Readings[reading], e)
		if !valid {
			loggingClient.Error("Validation failed: %s", err.Error())
			return
		}
	}
}

// Add the readings to the database
if configuration.PersistData {
	for i, reading := range e.Readings {
		// Check value descriptor
		_, err := dbc.ValueDescriptorByName(reading.Name)
```

4. AddReading should be called inside of AddEvent. This will allow to use transactions or similar in data base, which increases considerably the performance (I performed some tests using InfluxDB and other databases, with an important reduction of time)
```
	// Add the reading
	id, err := dbc.AddReading(reading)
	if err != nil {
		http.Error(w, err.Error(), http.StatusServiceUnavailable)
		loggingClient.Error(err.Error())
		return
	}

	e.Readings[i].Id = id // Set the ID for referencing later
}

// Add the event to the database
id, err := dbc.AddEvent(&e)
if err != nil {
	http.Error(w, err.Error(), http.StatusServiceUnavailable)
	loggingClient.Error(err.Error())
	return
}
```
5. There are several logs which can be removed (or changed to debug)

All this issues are still present in the refactored branch. If you want, I can help in order to solve them.

**Comment by tsconn23** [comment]
Regarding your points:

1.) Yes, need to finally get around to dealing with this. From talking to @tonyespy it sounds like name is the most reliable identifier for the device currently. This is on my plate.
2.) That Metadatacheck property only governs whether we actually throw an error if the device being asked for is not found. It's like a consistency flag. We have to attempt to go and get the device regardless, no way around that.
3.) If I understand correctly, you're saying we've already validated the descriptor above so no need to load it here since isValidValueDescriptor() itself makes a call to dbc.ValueDescriptorByName(reading.Name). Sounds reasonable to me.
4.) I'm inclined to agree with this. @jpwhitemn @tonyespy Is there some reason we would save readings independently of their event envelope as in the code path above?
5.) I'm sure there are.

Yes, the DDD refactoring repo in the holding area (assuming that's what you're referring to) was largely dedicated to reorganizing the code so that we can move forward with optimizations. I'm not surprised you see this behavior there as well.

**Comment by jduranf** [comment]
Thanks for your reply @tsconn23. Some comments:
2. If we only use the device name and MetaDataCheck is disabled, which is the point to check the device name if we will continue anyway?
3. Yes, that's right

If you want, I can make some PR in order to do those optimizations. But it's not clear for me if I should do this PR in the main repository, in the holding area repository or wait until the code in holding area is merged in the main repository.

**Comment by tsconn23** [comment]
@jduranf It was decided to hold off on merging from holding to main until after California so if you create individual issues for these work items, you can issue PRs against the main repo.

**Comment by jduranf** [comment]
All points done!
