### ISSUE TITLE
Is there any plans to translate with other languages?

### ISSUE THREAD

**Issue by devFallingstar** [edgexfoundry/edgex-go#192]
Hi, I'm a person who'll going to use the edgex foundry system for our own services.
I want to know if you guys have any plans about translating.

As Korean and as edgex user, I hope I can help you guys with documentation things.
As a result, I want to make the documentation pages(like git book) or manual with Korean version.

Is there any way to get the separated docs directories with specific languages?

Thanks.

**Comment by yanghua** [comment]
+1, I claim Chinese translation.

cc @jpwhitemn

**Comment by tsconn23** [comment]
@andyf1967

**Comment by andyf1967** [comment]
@devFallingstar in the short term we didn't have any plans to translate into other languages. Mainly due to the fact that no one had volunteered. However, if you can help then we can think about how to make this happen.  We have created the new documentation set in reStructuredText and use Sphinx to generate HTML. I know that Sphinx has support for Internationalization (see http://www.sphinx-doc.org/en/master/usage/configuration.html#intl-options) but don't know too much about it and it's something that we'll have to look into.

@yanghua thank you for volunteering to help with a Chinese translation  

At the next Core WG meeting I'll see it we can add the topic it to the agenda and get  the ball rolling.

cc @tsconn23 @jpwhitemn

**Comment by jpwhitemn** [comment]
We are seeing an up-tick in following of the project in Asia Pacific & Japan (thanks in no short measure to people like @yanghua and others).  Will add this to the list of needs of the project.  Of course we welcome volunteers willing to provide the translation of documentation, but we will also look into what other open source projects have done and if there is the potential of finding additional funding to accelerate.  No promises, but certainly worthy of research.

**Comment by yanghua** [comment]
hi @jpwhitemn no need for funding, just for expanding Edgex's influence. If you can promote this thing, that would be better.

**Comment by devFallingstar** [comment]
hi @jpwhitemn
I don't need for funding too, also I want to expand edge's influence as @yanghua said.
And, plus, I claim Korean translation with our team members(total 3 members include me).

Thanks for your opinion.

**Comment by jpwhitemn** [comment]
@devFallingstar @yanghua and others with interest in multi-language documentation support... we discussed this topic in the Core Working Group today.  Your willingness to contribute the initial translation is really appreciated.  What thoughts do you have on how to keep the documentation up to date once the initial translation is complete?  Would this be something you continue to update?  Do you think we could find sponsoring companies to help keep the documentation up to date (either by providing long term commitment of resources or even funding for professional writers/translators)?  Beyond the initial translation, what ideas do you have on how we keep the documentation current?

**Comment by yanghua** [comment]
@jpwhitemn AFAIK, many Apache top level such as (Spark, Flink, Beam) they all have not official version for Chinese document. The PMC and community will keep update the official document which is a part of the project repository, for example [Flink doc](https://github.com/apache/flink/tree/master/docs) it will go forward with the whole project (if a contributor implements a new feature the committer maybe ask he provide the document, if part of document is old, contributor could create a issue to update it). The document‘s version also keeps consistent with the project. And for internationalization, it seems Apache community let it free development. For example, here is a [flink-china repository](https://github.com/flink-china/flink-china-doc) which hosted the official document's Chinese version. For edgex, we could let the document repository hosted in 'edgexfoundry' organization.

Summary:
If there are sponsoring companies and under the condition that allows in funding, that would be better. Yes, it would be more professional.
However, community-driven is freedom , fast and zero-cost. It depends on the growth rate of Edgex, If the Edgex grows fast, community would defeat single translate organization.
About the update, all things based on the official's document version, the contributor (or volunteer) would calibrate it. We could split the translate task into many sub tasks based on modules and create them as issues, the contributor will claim it then make a PR. The committer would calibrate it before approving the PR.

**Comment by devFallingstar** [comment]
@jpwhitemn Actually, I think, there's many way to translate, repository by repository. 
This project, edgex-go, is mixed project made with source code(go) and documents(some mark down based). So in my opinion, we need two track translation, one for code, and another for documents.

As I know, most of project I saw follow up the below steps.
1. choose the translation owner for each languages, 
2. Any committer can make PR for their languages and owner of each language merge it after checking.
3. Each PR can managed with some guidelines or labels.
Does step is working with modularity and committer-driven based system, so it'll be good for initial translation.

Also I prefer the community-driven based for translation. Because as @yanghua said, we need the fast and zero-cost translation for initial translations. Moreover we need some user's passion that makes higher quality for our own result. Of course there's always pros/cons for each way, but at now, the translating without sponsoring is better than with it.

**Comment by jpwhitemn** [comment]
thanks Vino.  I have forward the issue along with your response up to the board for consideration.  
    On Thursday, May 10, 2018, 9:13:22 PM CDT, vinoyang <notifications@github.com> wrote:  
 
 
@jpwhitemn AFAIK, many Apache top level such as (Spark, Flink, Beam) they all have not official version for Chinese document. The PMC and community will keep update the official document which is a part of the project repository, for example Flink doc it will go forward with the whole project (if a contributor implements a new feature the committer maybe ask he provide the document, if part of document is old, contributor could create a issue to update it). The document‘s version also keeps consistent with the project. And for internationalization, it seems Apache community let it free development. For example, here is a flink-china repository which hosted the official document's Chinese version. For edgex, we could let the document repository hosted in 'edgexfoundry' organization.

Summary:
If there are sponsoring companies and under the condition that allows in funding, that would be better. Yes, it would be more professional.
However, community-driven is freedom , fast and zero-cost. It depends on the growth rate of Edgex, If the Edgex grows fast, community would defeat single translate organization.
About the update, all things based on the official's document version, the contributor (or volunteer) would calibrate it. We could split the translate task into many sub tasks based on modules and create them as issues, the contributor will claim it then make a PR. The committer would calibrate it before approving the PR.

**Comment by devFallingstar** [comment]
@jpwhitemn Can I know the current progress?

**Comment by jpwhitemn** [comment]
Still waiting word from the board level on this @devFallingstar.  I will report as soon as I have feedback and direction.

**Comment by jpwhitemn** [comment]
Expect board response tomorrow (7/11/18)

**Comment by jpwhitemn** [comment]
After the recent governing board meeting, the feeling was that EdgeX should always encourage contributions when possible and unless they are counter to the architecture or direction of the project, accept code, documentation, demos, etc. whenever presented and after a proper vetting review.
This same approach applies to the issue of alternate language documentation.  In general, EdgeX will accept alternate language documentation (the default language for EdgeX is and will remain English, so alternate documentation would be in Chinese, Korean, etc.) for possible adoption into the project.  However, as with any donated artifact, it will need to be donated under the LF and Apache 2 license, made available under the EdgeX Foundry Holding GitHub account and subject to review by appropriate members of the community.  Specifically, we will need to find members of the community with the appropriate language skills to be able to review the material and ensure the membership of its accuracy (it correctly documents EdgeX) and quality (the content is grammatically correct and professional in the language provided).  If there are no members of the community who are able/willing to provide this review, we cannot accept the contribution.  After accepting the contribution, the artifact must be maintained and keep up with the general state of the EdgeX product.  In case of documentation, it must continually reflect the state of the system.  If the community sees that the documentation in an alternate language is falling out of sync with the product, it will be archived as would any artifact in the EdgeX community.  
EdgeX encourages member companies with a strong interest in the alternate language documentation to take a leading role in encouraging the development, review and maintenance of the documentation in alternate languages – in other words to serve as sponsors of the alternate language documentation – in order to best serve the needs of the community long term.
