### ISSUE TITLE
Version bump of 3rd party Docker containers for Geneva

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1935]
# 🚀 Feature Request

### Relevant Package
Mostly a validation-only change.

### Description
To limit technical debt and pick up bug fixes and security fixes, we should bump the versions of 3rd party containers in the EdgeX Dockerfile for Genvea release.

The list of affected images is:
- consul
- kong
- portainer
- postgres
- redis
- vault

Additionally, the Dockerfile for security-secretstore-setup hard-codes alpine:3.10 and should be changed to just alpine for consistency with the rest of the containers.

**Comment by tingyuz** [comment]
Need more testing to find the root cause/alternative solution.

**Comment by michaelestrin** [comment]
Since none of the changes actually need to be made within the edgex-go repository, this more properly should be individual issues in each of the affected repositories (such as docker-edgex-mongo, docker-edgex-consul, developer-scripts, etc.). 

Closing here and notifying @bnevis-i to create the necessary issues in the appropriate repositories.
