### ISSUE TITLE
Develop process for security vetting of 3rd party components

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#1947]
# 🚀 Feature Request

### Relevant Package
Can apply to any part of EdgeX framework.  Most directly relevant to security services.

### Description
The project does not have an objective means of evaluating the security of 3rd party components as they are being introduced to the EdgeX foundry code base.  A recent pull request introduced a 3rd party component, GoKey, to be used in password generation.  No formal assessment was done of the library before deciding to include it as part of a security-critical flow.

The current high-level statistics of GoKey are:
- Age: 3 years
- Commits: 34
- Issues: 1 open and 9 closed
- Releases: 1
- Stars: 210
- Forks: 24
- Watchers: 10
- CVEs: None

Subjectively, the relative obscurity of the package leaves it unclear as to whether this is an OK component to use.

### Describe the solution you'd like
This request proposes the development of an objective process for assessing the security risk of 3rd party components.  Such a process could take into consideration item such as the project's age, popularity, evidence of security practices, recent commit history, diversity of committers, established CVE practices, or other observable evidence.

cc: @anonymouse64

**Comment by jamesrgregg** [comment]
_Crawl:_ Paper study (manual) as completed by @bnevis-i 

_Walk:_ Automation of paper study to include all required data points  - scope includes automating the generation of the report (ad-hoc) + use of Community Bridge Advanced Snyk reporting AS-IS

_Slow Run:_ Combination of the automated paper study + Fossology (with generation of evidence collected / considered + use of Community Bridge Advanced Snyk reporting (issues fixed) 

_Fast Run:_ Combination of automated paper study + Fossology + Dependency Track
Requires explore with LF to see what may exist already

In this phased approach, I think we can achieve completion by the Slow Run phase for Hanoi

**Comment by jamesrgregg** [comment]
I've now learned that the Linux Foundation may have an option via Nexus IQ.  Per our Linux Foundation release engineer…
“We currently offer Nexus IQ to projects, primarily for Java. However, it looks like it has Go support as well, so I think EdgeX can utilize this. Please take a look at what Nexus IQ supports, and let me know if the features cover what you need. Here's a couple links to get you started:”
https://www.sonatype.com/press-release-blog/sonatype-goes-long-with-godelivers-fully-automated-security-solution-for-fast-growing-programming-language
https://help.sonatype.com/iqserver/analysis/go-application-analysis

**Comment by jpwhitemn** [comment]
James - this looks promising.  Wonder if there would be a way for us to compare results on something like edgex-go to see if Nexus IQ appears to give us any benefits over our existing solution?jim white

    On Friday, May 8, 2020, 5:01:36 PM MST, jamesrgregg <notifications@github.com> wrote:  
 
 


I've now learned that the Linux Foundation may have an option via Nexus IQ. Per our Linux Foundation release engineer…
“We currently offer Nexus IQ to projects, primarily for Java. However, it looks like it has Go support as well, so I think EdgeX can utilize this. Please take a look at what Nexus IQ supports, and let me know if the features cover what you need. Here's a couple links to get you started:”
https://www.sonatype.com/press-release-blog/sonatype-goes-long-with-godelivers-fully-automated-security-solution-for-fast-growing-programming-language

https://help.sonatype.com/iqserver/analysis/go-application-analysis

**Comment by jamesrgregg** [comment]
@jpwhitemn I ran the scan against edgex-go tonight.  The project would need to adopt the use of go.sum files to go along with go.modules. The Nexus IQ scans are based off what's in that file.
The sample project includes a good example of what is shown in the CI so this would definitely work.  I'm checking on cost now with LF.

Example CI (Travis CI build for a sample project)
https://travis-ci.org/github/sonatype-nexus-community/intentionally-vulnerable-golang-project/builds/490260408

**Comment by jamesrgregg** [comment]
Detail on proposed recommendation for consideration within the Security WG has been submitted for review [https://github.com/jamesrgregg/1947-explore](https://github.com/jamesrgregg/1947-explore)

**Comment by jamesrgregg** [comment]
Per additional request that came out of Architect's meeting on 05/18/2020, there's a few options that are mentioned on the 1947-explore.  Please take a closer look at the free tools (DepShield and OSS Index) listed at the bottom of the writeup that could be utilized within the developer workflow, as well as through the use of a GitHub bot that's available through GitHub marketplace.

**Comment by jamesrgregg** [comment]
I've now added a table for consideration of the different use cases we discussed in the Architect's meeting as well as additional findings for considerations in each use case.  I'd appreciate feedback here on this issue.

**Comment by bnevis-i** [comment]
> I've now added a table for consideration of the different use cases we discussed in the Architect's meeting as well as additional findings for considerations in each use case. I'd appreciate feedback here on this issue.

This table "Summary of Findings and Final Recommendation"?

**Comment by jamesrgregg** [comment]
yes @bnevis-i 
there's also some additional references to some other tools which could be used in the developer workflow as well as some changes to include Snyk now on every PR. I just confirmed with Snyk that we shouldn't reach any limitations for scans on every PR.  The impact will be time it takes to complete an additional stage within each pipeline.

**Comment by jamesrgregg** [comment]
Also, I'm not sure that the "Automated Paper Study" is still relevant so I've removed that recommendation for inclusion for Hanoi scope.

**Comment by lenny-intel** [comment]
@jamesrgregg , looks good. 

On #3 might want to add an exception for modules new repo, but already used else where in other EdgeX repos.

**Comment by bnevis-i** [comment]
My own personal opinion:

Option 1 (Build pipeline scanning): I think the drawbacks outweigh the benefits:
- It will slow down the build pipeline, increasing likelihood of cascading chain of out of date PRs
- If enabled in enforcing mode, it could block merging of PRs needed to refactor around a vulnerable module in order to replace or upgrade it.
- When issues are flagged, it will not likely be the result of the proposed PR
- This feature will only work so long as there are active contributions to trigger the scans. 

I think a periodic scan will report results even when there are no active PR's being worked.  Is there a way to do that?

Option 2 looks good.

Option 3 looks like it might be problematic.  Is it fair to say that if I want #3 I have to take #1 along with it?  Is there a way to automate the snyk analysis only if go.mod is changed?

**Comment by jamesrgregg** [comment]
@bnevis-i the use cases are what's in play today for multiple scenarios that need to be considered.  They are not options and in fact, for the most part, all of the tooling is already in place to support each of these use cases, with the exception of the 2.) Holding use case, as that's dependent upon local developer workflow and the submitter of code under review in holding.  What's being "proposed" , that could be considered if approved by the community, is the use of an indicator on the Pull Request template that should catch the eye of the reviewer / working group chair, as well as changing the way we do scans within each Pull Request vs. Only on Merge to Master.  The expectation and hope is that the CommunityBridge Advanced Snyk reporting will improve to include better reporting that includes the correct license identification, as well as improved dependency scanning of the go modules dependencies.  If we don't need the feedback loop within each PR, I agree with you it's best to keep it as is with only scanning on merge to master.

**Comment by bnevis-i** [comment]
@jamesrgregg I think I was conflating the "every PR" flow with the "merge to master" flow.  Assuming we don't accidentally lock ourselves out of updating the code base when there is a finding, I think I can live with the side effects.

**Comment by bnevis-i** [comment]
So in order to make progress, how about we do this:

- Introduce the synk scan on merge to master.  This report will be part of the synk history and available to the SIR team as a data point.  This is easy to do and will give us good data.
- For stuff being moved out of holding, do a manual scan (as suggested) that is part of the approval request to move the repository out of holding.
- For new dependencies, do upgrade the PR template, do add the label, but request both an NVD scan and Nancy report for the PR, and have the discussion about the new dependency in the PR.

We should be upgrading dependencies regularly, but few go modules at this time actually have CVE's filed against them and so there is very little data to say whether upgrading modules is to get new features, fix bugs, or resolve security issues.  We have already started this process for container versions and we should be evolving our process to do it for go.mod dependencies.

**Comment by jamesrgregg** [comment]
@bnevis-i  for clarification, the snyk scan is already included in the pipelines after a PR is merged to master.  This capability was introduced in Geneva..  The changes to the PR template and the additional label are easily managed.

**Comment by jamesrgregg** [comment]
I've reorganized this explore to make it easier to read.  The TLDR is summarized [here](https://github.com/jamesrgregg/1947-explore#summary-of-findings-and-final-recommendation)

**Comment by tonyespy** [comment]
Sorry it's taken me so long to comment, but the discussion at this week's Core WG meeting re: the go-core-contracts [V2 DTO API PR](https://github.com/edgexfoundry/go-mod-core-contracts/pull/236) forced the issue. Also note, I'm commenting on both this issue and Jame's [1947-explore](https://github.com/jamesrgregg/1947-explore) document.

This issue is titled "Develop process for security vetting of 3rd party components", however it's now been discussed in the architecture group as well. And since the discussion has included license vetting as well as correctness/maturity vetting (i.e. be poorly designed and/or implemented), maybe the title and/or description should be updated? 

The latest [TLDR](https://github.com/jamesrgregg/1947-explore#summary-of-findings-and-final-recommendation) in Jame's document as well as Bryon's last comment suggest the process for a PR introducing a new Go module/package import (and for device-sdk-c maybe a new shared library dependency) is:

 * PR submitter should indicate via a new PR template checkbox that the PR introduces one or more new dependencies
 * "dependency" label is added to the PR
 * Reviewers should also always look for changes to go.mod (or the equivalent for C-based projects) even if the dependency checkbox has not been checked
 * Request an NVD and Nancy scan for the new dependency
 * Discuss the new import in the PR

What happened to perform a manual paper study (eg. [PR 236 paper study](https://github.com/jamesrgregg/1947-explore/blob/master/236-analysis.md)) requirement? Looking at his analysis, a couple of thoughts:

 * the manual and automated paper studies only cover the new explicit dependencies being introduced
 * in this case, the three new imports actually result in an additional seven implicit dependences (see forthcoming PR comment)
 * the Nancy scan does cover all (explicit and implicit) dependencies
 * our paper scans should do this as well. In the case of Go, it doesn't matter if it's an explicit or implidit dependency, the new code is being linked into our executables, so vetting all additions is important (see above for justification).
 * Ian Johnson also asked me to mention that he provided a script to the project which we use to keep our `Attribution.txt` files up-to-date. He mentioned to me that it might useful as part of our paper scan process...
 * **note** - some of the new dependencies may only be used by _test code, which means in theory we could potentially exclude them, however my gut tells me that amount of work to determine this is probably more effort than thus including and analyzing them with all the rest...

Also as a last comment, I found this nugget in a golang.org blog post [Using Go Modules](https://blog.golang.org/using-go-modules):

_Note that while the go command makes adding a new dependency quick and easy, it is not without cost. Your module now literally depends on the new dependency in critical areas such as correctness, security, and proper licensing, just to name a few. For more considerations, see Russ Cox's blog post, “[Our Software Dependency Problem.](https://research.swtch.com/deps)”_

**Comment by tonyespy** [comment]
During Thursday's Core WG meeting I took an action to check with our snapd team to see if they have a process for vetting new golang imports. This is what they had to say:

Our team doesn't have a formal process per se, but in general when reviewing a PR with new package imports we always consider:

 * does the new import add a large number of it's own dependencies? In general the team tends to shy away from packages like this as it puts a burden on the reviewers and leads to package bloat.
* does it build on the versions of Go we care about, i.e. Go 1.10 right now ?
* license compatibility questions, can we legally use it?
* maintenance questions, if the upstream code is not maintained and we use it are we okay with forking it to fix it when it is found to be buggy?
* where/what would it be used for in snapd? if security related, has our security team signed on to review this and help maintain this dependency (i.e. see libseccomp)?

I don't think we actually have a specific metric to the number of releases/developers/other things, but all of those are certainly factors when looking at a new dependency and it's just usually assumed that the upstream projects have a good number of recent commits and some level of activity from developers, etc.

As a final note, our team is pretty conservative about allowing new imports primarily due to the added maintenance burden. snapd itself only depends on < 30 external public imports. There are additional imports used, but those packages are maintained directly by the snapd team.

**Comment by tonyespy** [comment]
While working on the PRs to update all of our device services to the latest device-sdk-go for our Geneva maintenance release, I noticed that the underlying modbus implementation used by device-modbus-go had a version tag of [v0.1.0](https://github.com/edgexfoundry/device-modbus-go/blob/master/go.mod#L6).

Looking at the actual package [github.com/goburrow/modbus](https://github.com/goburrow/modbus):

 * it has one release from 2018
 * the project has four contributors
 * the last commit was two years ago
 * there are 22 open issues
 * it has 8 open PRs, one actually opened 23 days ago

To me, this looks like a dead project, or maybe just one on life support...

**Comment by bnevis-i** [comment]
@tonyespy This probably deserves its own issue ticket.

**Comment by jamesrgregg** [comment]
Research now updated to include [FOSSA](https://github.com/jamesrgregg/1947-explore/blob/master/research.md#fossa)

**Comment by jamesrgregg** [comment]
Additional research and comparison of FOSSA and existing capabilities already afforded with Snyk and Community Bridge Advanced Snyk reporting has now been documented. TLDR; stick with Snyk and Community Bridge reports.
See [here](https://github.com/jamesrgregg/1947-explore/blob/master/comparison-tools.md)

**Comment by jpwhitemn** [comment]
Good write up James.  " This would be considered a heavy lift for anyone on the project. "  - we have other more pressing issues right now and this can wait until we have more defined needs with regard to tooling.

    On Monday, June 22, 2020, 11:06:09 AM CDT, jamesrgregg <notifications@github.com> wrote:  
 
 


Additional research and comparison of FOSSA and existing capabilities already afforded with Snyk and Community Bridge Advanced Snyk reporting has now been documented. TLDR; stick with Snyk and Community Bridge reports.
See here

**Comment by tonyespy** [comment]
> @tonyespy This probably deserves its own issue ticket.

https://github.com/edgexfoundry/device-modbus-go/issues/156

**Comment by jamesrgregg** [comment]
After additional discussion with @tonyespy today, I've updated the process for assessing new dependencies to include the process for seeking review on security related dependencies from a security wg community member and adding a new label as `security-review` to the PR.  Additionally, the submitter of a PR which includes new dependencies, would be requested to provide scan results.  The summary of this is in the TLDR found [here](https://github.com/jamesrgregg/1947-explore#summary-of-findings-and-final-recommendation)

**Comment by jamesrgregg** [comment]
Please review for formal adoption / ratification of the outlined process now documented within the project wiki - [here](https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=46760301)

**Comment by jpwhitemn** [comment]
Per the Architect's meeting (and pending TSC vote) - this issue is closed.  The process has been defined here:  https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=46760301
