### ISSUE TITLE
.dockerignore file should include .git/ directory

### ISSUE THREAD

**Issue by jdharms** [edgexfoundry/edgex-go#1973]
# 🚀 Feature Request

### Description
 A clear and concise description of the problem or missing capability...
Currently, the `.git/` directory is sent in the docker build context for each image built.  This currently represents 230MB of transfer that needs to happen, as well as bloat in potentially cached images on developer systems.  Adding .git to the .dockerignore file will speed up docker build times for developers and in CI/CD

### Describe the solution you'd like
I think we should add .git and log files to the .dockerignore file.

**Comment by anonymouse64** [comment]
This actually just broke the snap build, because the snap is built inside a docker container that needs the .git folder to exist in order to assign a version tag to the snap. 

There could be a workaround here that involves modifying the .dockerignore file when we run the snap build specifically in the job, but I don't like that because it would mean that the builds of the snap are operating on a "dirty" git tree.

**Comment by anonymouse64** [comment]
I have consensus from @jdharms and @tsconn23 that we can just revert the PR and figure out a better solution after Fuji is out the door.

**Comment by anonymouse64** [comment]
Apparently on jenkins there is an env var that has the git sha which we could use for the docker/jenkins build. This could be used, but we would need to modify the version set script to check for that env var and use if it's available, otherwise using the current behavior to ask git what commit we're on. The current behavior would also continue to work for local builds in that case then. 

It also appears as if that env var would need to be passed through jenkins env to the snap docker build env with a flag like we do currently for other env vars: 

https://github.com/edgexfoundry/ci-management/blob/f61a8fc4dbfe77ab35ae65835dc9aa25aa9b1d47/shell/edgexfoundry-snapcraft.sh#L179-L184

**Comment by cloudxxx8** [comment]
`.git` has been added to `.dockerignore` in
https://github.com/edgexfoundry/edgex-go/commit/eebbc51e4a300ba4ec20fbfde4689b2c90fa3bc0

closing this issue
