### ISSUE TITLE
BB Test Failing: Unauthorized secret store access check

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#1997]
Investigate and correct the implementation issue behind the failing blackbox test: 

Unauthorized secret store access check

![image](https://user-images.githubusercontent.com/464327/67572906-c80d0a00-f6fc-11e9-9c1a-90c62699daa0.png)

@tingyuz for visibility.

**Comment by tingyuz** [comment]
bb test failures ( issue #1997 to issue #2007) are due to incorrect header settings in the Blackbox testing cases. In Fuji release the requirement of header for HTTP requests to proxy has been removed. These bb testing cases need to be adjusted accordingly. I have a PR open to address it:
https://github.com/edgexfoundry/blackbox-testing/pull/303

**Comment by tingyuz** [comment]
Currently some blackbox testing cases are failed, most of which are related to proxy health checking. Checking the log on bb testing centOS image and noticed that KONG was failed to start. After some research we found that KONG 1.0.3 is not working on centOS 7 ( issue opened at KONG here: https://github.com/Kong/docker-kong/issues/274).  Since KONG was failed to start, these testing cases were failed.
These issue are not related to current codebase of edgex-go, but environment issue of blackbox testing. I would suggest to move these issues under blackbox testing and put these limitation into release guide, and mark them as unresolved issues for next release of blackbox testing.

**Comment by michaelestrin** [comment]
Moved to https://github.com/edgexfoundry/blackbox-testing/issues/305
