### ISSUE TITLE
Returning 404 Status is Incorrect

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#201]
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L361
https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-data.postman_collection.json#L929
When I run these two **core-data** test script, it's expect return 409 http status ,  
cause hummidity is non-existent value descriptor .

I have check java version and go version,  
...should return 409 http status at
https://github.com/edgexfoundry/edgex-go/blob/master/core/data/event.go#L262
Just like java version’s core-data 
https://github.com/edgexfoundry/core-data/blob/master/src/main/java/org/edgexfoundry/controller/impl/EventControllerImpl.java#L273"

=============== 
update ...
here are same error at **core-metadata**
https://github.com/edgexfoundry/edgex-go/blob/master/core/metadata/rest_deviceservice.go#L99
https://github.com/edgexfoundry/edgex-go/blob/master/core/metadata/rest_deviceservice.go#L111
and it's also define in
https://github.com/edgexfoundry/edgex-go/blob/master/core/metadata/raml/core-metadata.raml#L1348

**Comment by yanghua** [comment]
cc @jpwhitemn @tsconn23

**Comment by tsconn23** [comment]
It appears the statuses were changed during the initial conversion from Java to Go. Example:

https://github.com/edgexfoundry/core-data-go/blob/master/event.go#L249

To me 404 is more appropriate since we're aware that a value descriptor on the event is not found. By contrast, 409 is as follows:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

So again, I think the service logic is appropriate but the RAML and tests need to be updated @jpwhitemn @andyf1967

**Comment by weichou1229** [comment]
@tsconn23 
this is data validation error , I think use 400 as bad request is more sensible,
https://tools.ietf.org/html/rfc7231#section-6.5.1

**Comment by tsconn23** [comment]
@andyf1967 @jpwhitemn Please chime in here. Same type of situation as #211

**Comment by andyf1967** [comment]
Looks to me as though 404 Not Found is the correct error.  I think if not too much work we should fix RAML and update Java code and tests.

**Comment by jpwhitemn** [comment]
Per sites like this one:  http://www.restapitutorial.com/httpstatuscodes.html, 404 would be the correct response as the resource is not found (The requested resource could not be found but may be available again in the future).  Agree with @tsconn23 .  Update the RAML to meet the current Go code.  We'll update the Java code if not too much lift- otherwise record as an issue against the Java service.
