### ISSUE TITLE
Update configuration for SecretClient retries from nanoseconds(int) to seconds(string)

### ISSUE THREAD

**Issue by michaelestrin** [edgexfoundry/edgex-go#2092]
See https://github.com/edgexfoundry/edgex-go/pull/2087#issuecomment-551182309

Intent is to get this into Fuji before release.

**Comment by michaelestrin** [comment]
@anonymouse64 -- per https://github.com/edgexfoundry/edgex-go/pull/2087#issuecomment-551177079, don't hesitate to move ahead with corresponding PRs.  Ask is to add @AnthonyMBonafide and me as reviewers.  I believe Fuji release has been delayed until at least next Friday to allow for remaining security issues/questions to be investigated and resolved.  Which means there is time to merge this early next week.

cc: @lranjbar

**Comment by anonymouse64** [comment]
To be clear, what is being asked is to change edgex-go's configuration.toml to use a string for the retry period, parse that into a time.Duration to provide to go-mod-secrets, correct? 

@AnthonyMBonafide Is the change to having go-mod-secrets accept a string and do the parsing itself still for Geneva?

**Comment by lranjbar** [comment]
@michaelestrin @anonymouse64 @AnthonyMBonafide The release date is moved to Friday to allow the Security WG to do some manual testing and report out on those bugs. Lets target Wednesday for bug fixing.

**Comment by AnthonyMBonafide** [comment]
@anonymouse64 that is correct. My apologies for the delayed responses, I am traveling today.

**Comment by AnthonyMBonafide** [comment]
I have a bigger question here regarding versioning. This change would essentially be a breaking change, since existing configurations would not work. I'm in favor of bumping the major version of this module. What I'm not sure is how we (would) handle this situation for other library modules, like `go-mod-core-contracts`. I don't think we have had this happen yet and this might be a time to come up with a plan so we can approach this consistently across other repos. Luckily this is a new module with few consumers so for this situation it's not that big of a deal

**Comment by lranjbar** [comment]
We haven't had any major discussions regarding the versioning of the go modules. So it sounds like maybe the time has come where we need to think about the versions. None of the go modules are currently versioned to be same as the core microservices.

**Comment by anonymouse64** [comment]
> This change would essentially be a breaking change, since existing configurations would not work

Here I am assuming you are referring to the configuration.toml files, which won't be changing between Edinburgh and Fuji and Geneva. There will only be the small change between this week's Fuji configuration.toml files and the finally released ones next week, assuming that nothing happens that prevents me from filing a PR to fix this.

The versioning of the go-mods-secrets format for Geneva I don't think is an issue as I detailed in the PR:

> 1. The only change to do what Anthony wants is in what go-mod-secrets accepts from an API perspective (i.e. accept a string instead of a time.Duration)
> 1. This change doesn't break compatibility for client services config format (i.e. the configuration.toml)
> 1. We haven't tagged go-mod-secrets with a 1.X release so I think it's fine to break go-mod-secret's API

Point 3 is most relevant here I think. I wouldn't recommend releasing a major version of go-mod-secrets until at least we are closer to being done with the Geneva work items from the security WG because we may need to break some more things in go-mod-secrets to get Geneva where we want it.

**Comment by michaelestrin** [comment]
> We haven't had any major discussions regarding the versioning of the go modules.

Discussion should include @tsconn23.

> None of the go modules are currently versioned to be same as the core microservices.

I think this is intentional.

**Comment by anonymouse64** [comment]
Actually as I work on implementing this, it's simpler to just make go-mod-secrets accept a string. There's a bit of complexity in having `BootstrapConfiguration.SecretStoreInfo` both inhert `RetryWaitPeriod` from `vault.SecretConfig` and have a separate string defined for it. It can be made to work, but it's simpler code and it's what's wanted in the end, so let's just do it now. This will require a few more PR's but I will have them all open today and hopefully that means we can land everything by Wednesday

**Comment by michaelestrin** [comment]
> Actually as I work on implementing this, it's simpler to just make go-mod-secrets accept a string. There's a bit of complexity in having `BootstrapConfiguration.SecretStoreInfo` both inhert `RetryWaitPeriod` from `vault.SecretConfig` and have a separate string defined for it. It can be made to work, but it's simpler code and it's what's wanted in the end, so let's just do it now.

Please do a complete solution or none at all.  Technically, this is functioning now as-is.  It makes no sense to me to do an implementation that duplicates fields.

**Comment by anonymouse64** [comment]
PRs open:
- https://github.com/edgexfoundry/edgex-go/pull/2098
- https://github.com/edgexfoundry/docker-edgex-mongo/pull/67
- https://github.com/edgexfoundry/go-mod-secrets/pull/38

**Comment by anonymouse64** [comment]
> Please do a complete solution or none at all. Technically, this is functioning now as-is. It makes no sense to me to do an implementation that duplicates fields.

Sorry if I was unclear but to use your words all of the work I did is the "complete solution"

**Comment by anonymouse64** [comment]
> Technically, this is functioning now as-is

For clarity there's still a race condition between mongo and security-secretstore-setup, and to do that we need https://github.com/edgexfoundry/docker-edgex-consul/issues/7 and https://github.com/edgexfoundry/developer-scripts/issues/175

**Comment by tsconn23** [comment]
> This change would essentially be a breaking change, since existing configurations would not work. 

Not true because the configuration being modified by Ian's work was added during the Fuji dev cycle. There is no `[SecretStore]` section in the edinburgh [configuration ](https://github.com/edgexfoundry/edgex-go/blob/edinburgh/cmd/core-data/res/configuration.toml)files.

> We haven't had any major discussions regarding the versioning of the go modules.

I'm thinking we need to look at tagging the go-mod modules with a major version during Geneva. We could also do it for Hanoi if the LTS release picture becomes clearer.

I won't hijack this issue's discussion anymore but felt I should reply since questions were directed at me.

**Comment by lranjbar** [comment]
Just to be clear I believe we are fine with breaking changes with regards to go modules at this point because we haven't revved them to 1.0. Also because of this we need to have a community discussion when we feel they are ready for their 1.0 release. It is intentional that they are currently not the same version as the core microservices.

I will also now stop hijacking this discussion because I hope this is enough clarity to move forward.

**Comment by anonymouse64** [comment]
Forward-port PR's for docker-edgex-mongo are open here:
- https://github.com/edgexfoundry/docker-edgex-mongo/pull/69
- https://github.com/edgexfoundry/edgex-go/pull/2103

**Comment by anonymouse64** [comment]
Fixed in #2103
