### ISSUE TITLE
Error, exceeded the max limit as defined in config 

### ISSUE THREAD

**Issue by wassim6975** [edgexfoundry/edgex-go#2097]
Hello everyone, 
I have a problem when I try to get http://localhost:48080/api/v1/reading : 
Error, exceeded the max limit as defined in config 

I don't know how I can access to my logs to delete the data. 
How can I solve this issue ? 

Thank you a lot for your help

**Comment by tsconn23** [comment]
Question already asked on Slack. No details on which release/branch is being used. No details on which database is being used. Suggest you do research on the commands available for your chosen database to clear the relevant data -- or otherwise refer to the published API spec for core-data on docs.edgexfoundry.org which will answer this question.
