### ISSUE TITLE
Delete event func for Redis misses the deletion of the checksum collection for binary data

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#2143]
# 🐞 Bug Report

### Affected Services
The issue is located in: Core-Data

### Is this a regression?
No, it also happens in Edinburgh release

### Description and Minimal Reproduction
When creating the event, there is an additional collections added to reference to the event id for binary data
https://github.com/edgexfoundry/edgex-go/blob/d7fd3d05ee7535716585419652c1d825b0693da7/internal/pkg/db/redis/data.go#L1060-L1062

However, the deleteEvent func doesn't delete it
https://github.com/edgexfoundry/edgex-go/blob/d7fd3d05ee7535716585419652c1d825b0693da7/internal/pkg/db/redis/data.go#L1091-L1119

## 🔥 Exception or Error
The data will keep growing until out of memory

## 🌍  Your Environment
**Deployment Environment:**
Ubuntu

**EdgeX Version:**
Edinburgh and Fuji

**Anything else relevant?**
it is similar to https://github.com/edgexfoundry/edgex-go/issues/2076

**Comment by michaelestrin** [comment]
Fix in Fuji and master.  With Fuji now released, we're no longer supporting Edinburgh.

**Comment by AnthonyMBonafide** [comment]
The fix for this bug is not as simple as adding a `ZREM` statement to remove the member from the sorted set. This is due to the lack of information within the `deleteEvent` function. The `deleteEvent` function uses the `eventByID` function to translate an Event ID to an Event struct which contains information we need to effectively delete all associated data. The event type returned by `eventByID` is the contract version of the Event type, which does not have the necessary `Checksum` information:

https://github.com/edgexfoundry/go-mod-core-contracts/blob/1530e9d185e90c69609b83a703c8fd1de8df1c2c/models/event.go#L23-L32

Even though there is a simple fix for this, such-as use and/or create a different function for obtaining the Event by ID which will provide the missing information. I think there is a better way to design the whole `DBClient` interface, especially since we are exploring the idea creating explicit DTOs to separate the internal  from the external representations of our entities. I think the `DBClient` would serve better if it operated only with the internal representations of the entities and left the conversion from internal entities to DTOs to the business logic. I bring this thought up because I think that it if we do decide to head in that direction, I can possibly look into updating some of the helper functions to use the `correlation` version of the Event type and upgrade the methods to convert the `correlation` representation to the `models` representation before returning to the caller. This would benefit us in that the Redis client will consistently be using the "internal" version of the Event type making kinds types of issues less likely and easier to maintain. Also, there is a 3rd Event type at play here making this a little less easy to follow:

https://github.com/edgexfoundry/edgex-go/blob/d7fd3d05ee7535716585419652c1d825b0693da7/internal/pkg/db/redis/event.go#L26-L34

@michaelestrin, Any thoughts as to if I should just do a quicker fix since this is a bug in Fuji or take some additional time and clean this up a bit?

**Comment by AnthonyMBonafide** [comment]
Created this follow-up issue to clean up some of the code #2166
