### ISSUE TITLE
Failing blackbox tests - core-data when using Redis

### ISSUE THREAD

**Issue by AnthonyMBonafide** [edgexfoundry/edgex-go#2163]
# 🐞 Bug Report

### Affected Services
core-data, specifically events

### Is this a regression?
Not sure when the problem was introduced.

### Description and Minimal Reproduction

1. Configure core-data to use Redis for persistence, either by TOML or Consul
2. Start core-data
3. Run core-data blackbox tests against the running instance of core-data using Redis

## 🔥 Exception or Error

Newman failures:

<pre><code>
 ↳ 30 http://localhost:48080/api/v1/event/removeold/age/:age
 DELETE http://localhost:48080/api/v1/event/removeold/age/0 [500 Internal Server Error, 198B, 18ms]
 2. Status code is 200
 ✓  Response time is less than 800ms

 ↳ 32 http://localhost:48080/api/v1/event/scrub
   DELETE http://localhost:48080/api/v1/event/scrub [500 Internal Server Error, 198B, 12ms]
   1. Status code is 200
   ✓  Response time is less than 800ms

</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
OS: Linux Fedora 31
Persistence: Redis running locally and natively
Service: core-data with an updated TOML file to use the locally running instance of Redis 
Blackbox tests: Updated the blackbox tests to use the local postman environments rather than the docker versions.

**EdgeX Version:**
Geneva(tip of master branch)

**Anything else relevant?**
I have not determined the root cause of the error, so that will need to be determined. If I figure out a root cause I will provide a comment to this issue.

**Comment by michaelestrin** [comment]
Blackbox tests currently execute using Mongo.  In the Geneva cycle, I anticipate they'll be updated to execute using Redis.  However, the project currently supports both databases and I do not expect this to change going forward.  

Because we're not running blackbox tests against all of the supported database variations, we're missing issues that would otherwise be caught.  [This particular GitHub issue](https://github.com/edgexfoundry/edgex-go/issues/2163) is a representative example.

I recognize the project intends to change the testing framework and test implementation away from the existing Newman/JSON blackbox tests to the TAF framework.

The ask here is to update the build environments to incorporate the two currently support databases as variations when we run the tests (whatever framework we're currently using and those that we intend to use in the future).  Expect this will result in a discussion topic in either the DevOps WG, the Q/A WG, or both.

@frq92290 @cloudxxx8 @jamesrgregg @lranjbar @tsconn23

**Comment by cloudxxx8** [comment]
@AnthonyMBonafide I believe this issue is fixed by https://github.com/edgexfoundry/edgex-go/pull/2192
Could you please help confirm that?

**Comment by cloudxxx8** [comment]
@michaelestrin I opened issue https://github.com/edgexfoundry/blackbox-testing/issues/344 for your request, and we will take care of it by the middle of January.

**Comment by michaelestrin** [comment]
> @michaelestrin I opened issue [edgexfoundry/blackbox-testing#344](https://github.com/edgexfoundry/blackbox-testing/issues/344) for your request, and we will take care of it by the middle of January.

That will be awesome! Thank you.

**Comment by michaelestrin** [comment]
> @AnthonyMBonafide I believe this issue is fixed by #2192
> Could you please help confirm that?

Assigning confirmation/additional work (if any) to @brandonforster.

**Comment by brandonforster** [comment]
Verified this is no longer an issue.
