### ISSUE TITLE
ThingsBoard IoT export connector

### ISSUE THREAD

**Issue by jduranf** [edgexfoundry/edgex-go#225]
We are starting to work in a export connector to allow EdgeX to export device data to [ThingsBoard](https://thingsboard.io/) using MQTT and a custom JSON format.
As MQTT is already implemented this connector will only imply add a new format to export-distro, maybe called FormatThingsBoardJSON.
If everything goes fine, we will have this connector implemented in just few days.
Please feel free to add any comment.

**Comment by jpwhitemn** [comment]
This is great Joan.
 Going forward, we want to make the export distro more modular and scalable so that connectors like this will be easier to put together and also configurable for inclusion or exclusion at deployment time.  But for now, this helps extends EgdeX's reach to more cloud and enterprise platforms.

    On Tuesday, May 15, 2018, 6:50:43 AM CDT, Joan Duran <notifications@github.com> wrote:  
 
 
We are starting to work in a export connector to allow EdgeX to export device data to ThingsBoard using MQTT and a custom JSON format.
As MQTT is already implemented this connector will only imply add a new format to export-distro, maybe called FormatThingsBoardJSON.
If everything goes fine, we will have this connector implemented in just few days.
Please feel free to add any comment.

**Comment by jpwhitemn** [comment]
Putting this in the Delhi Milestone, but if it is available for California - more better

**Comment by Wanderzhd** [comment]
Hi Joan,

Thanks for adding in Thingsboard connector.

As to the format, if we want to send data to thingsboard, what's the format we need to set? thanks.
format: JSON or XML are your options at this time

**Comment by jduranf** [comment]
As a format you must use `THINGSBOARD_JSON`

**Comment by Wanderzhd** [comment]
Thank you Joan.

With below config, still failed to get any msg in ThingsBoard server side.  Any suggestion?
curl -X PUT -d '{
    "name":"1",
    "addressable":{
        "name":"ThingsBoard",
        "protocol":"tcp",
        "address":"52.80.40.46",
        "port":9000,
        "user":"boxing",
        "publisher":"EdgeXExportPublisher",
        "topic":"v1/devices/me/telemetry"
    },
    "format":"THINGSBOARD_JSON",
    "filter":{
        "deviceIdentifiers":["Random-Integer-Generator01"]
    },
    "enable":true,
    "destination":"MQTT_TOPIC"
}'

**Comment by Wanderzhd** [comment]
After changed the topic to v1/gateway/telemetry, the issue resolved.

**Comment by jduranf** [comment]
@Wanderzhd you are right!
Also in user maybe you should put the token generated in ThingsBoard

**Comment by Wanderzhd** [comment]
yes.  
Really appreciated for your help!

**Comment by Salvocll** [comment]
Hi everyone, I made some attempts but I couldn't connect edgeX with thingsboard. Could you kindly copy a complete and correct configuration template?

Thanks in advance.

**Comment by zhanglt** [comment]
> Hi everyone, I made some attempts but I couldn't connect edgeX with thingsboard. Could you kindly copy a complete and correct configuration template?
> 
> Thanks in advance.

Me too
