### ISSUE TITLE
Cannot create access token for API gateway authentication (Geneva)

### ISSUE THREAD

**Issue by FelixTing** [edgexfoundry/edgex-go#2267]
**Version:** fuji, master

**Environment:**
X86_64 Ubuntu16.04
X86_64 macOS Catalina 10.15.1

**Description:** Cannot create access token for API gateway authentication

**Steps to reproduce:**

_fuji_
1. docker-compose -f [docker-compose-fuji.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/fuji/compose-files/docker-compose-fuji.yml) up -d
2. docker-compose -f docker-compose-fuji.yml run edgex-proxy --init=false --useradd=user --group=admin

_master_
1. docker-compose -f [docker-compose-nexus.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus.yml) up -d
2. docker-compose -f docker-compose-nexus.yml run edgex-proxy --init=false --useradd=user --group=admin

(Also tried to start the security-related services individually like the [deploy-edgex.sh](https://github.com/edgexfoundry/blackbox-testing/blob/master/deploy-edgeX.sh) does, it's still not working.)

**Expected result:** Return the access token

**Received result:**
> Starting kong-db ... done
> Starting edgex-files ... done
> Starting edgex-core-consul ... done
> Starting edgex-vault ... done
> Starting kong-migrations ... done
> Starting kong ... done
> \+ cd /consul/scripts
> \+ command -v jq
> \+ JQ=
> \+ '[' -z ]
> \+ LD_LIBRARY_PATH=.
> \+ export LD_LIBRARY_PATH
> \+ JQ=/consul/scripts/jq
> \+ export JQ
> \+ /consul/scripts/jq -r '.[] | select(.ServiceName == "kong") | .Status == "passing"'
> \+ curl -s -G edgex-core-consul:8500/v1/agent/checks
> \+ '[' true '=' true ]
> \+ cd /consul/scripts
> \+ command -v jq
> \+ JQ=
> \+ '[' -z ]
> \+ LD_LIBRARY_PATH=.
> \+ export LD_LIBRARY_PATH
> \+ JQ=/consul/scripts/jq
> \+ export JQ
> \+ curl -s -G edgex-core-consul:8500/v1/agent/checks
> \+ /consul/scripts/jq -r '.[] | select(.ServiceName == "security-secretstore-setup") | .Status == "passing"'
> \+ '[' true '=' true ]
> level=ERROR ts=2019-12-23T09:11:57.639625Z app=edgex-security-proxy-setup source=logger.go:73 msg="logTarget cannot be blank, using stdout only"

> Creating directory: ./logs
> level=INFO ts=2019-12-23T09:11:57.6417117Z app=edgex-security-proxy-setup source=requestor.go:40 msg="successfully loaded rootCA certificate."

> level=INFO ts=2019-12-23T09:11:57.6504506Z app=edgex-security-proxy-setup source=service.go:64 msg="the service on http://kong:8001 is up successfully"

> level=DEBUG ts=2019-12-23T09:11:57.6904699Z app=edgex-security-proxy-setup source=service.go:151 msg="trying to upload cert to proxy server"

> level=ERROR ts=2019-12-23T09:11:57.6957547Z app=edgex-security-proxy-setup source=service.go:182 msg="failed to add certificate with errorcode 400, error {"message":"schema violation (snis: edgex-kong already associated with existing certificate '49b0a17f-599d-45dd-9496-33b9a0af14d1')","name":"schema violation","fields":{"snis":"edgex-kong already associated with existing certificate '49b0a17f-599d-45dd-9496-33b9a0af14d1'"},"code":2}"

> level=INFO ts=2019-12-23T09:11:57.6970807Z app=edgex-security-proxy-setup source=service.go:98 msg="skipping as the initialization has been done successfully"

**Comment by FelixTing** [comment]
@tingyuz @bnevis-i for awareness

**Comment by tingyuz** [comment]
It appears that the process was trying to upload the cert again for KONG ( which already exists from last successful start up). Since such cert already exists it just reports error and skips the rest of the work.  Here is the related log:

level=ERROR ts=2019-12-23T09:11:57.6957547Z app=edgex-security-proxy-setup source=service.go:182 msg="failed to add certificate with errorcode 400, error {"message":"schema violation (snis: edgex-kong already associated with existing certificate '49b0a17f-599d-45dd-9496-33b9a0af14d1')","name":"schema violation","fields":{"snis":"edgex-kong already associated with existing certificate '49b0a17f-599d-45dd-9496-33b9a0af14d1'"},"code":2}"

When init flag is passed into edgex-proxy such cert loading needs to be skipped and user account will be created. Need to check if init flag is honored with process or something else went wrong.

**Comment by hutchic** [comment]
I haven't examined the specific go code but is it possible this could be related to https://github.com/Kong/kong/issues/5309 ?

**Comment by FelixTing** [comment]
btw, this function works fine in the Edinburgh release.

**Comment by tingyuz** [comment]
This is due to recent change of the docker-compose file in Fuji. I had discussion with @anonymouse64 and we agreed to improve this part in both user guide and dock-composer file in the following steps. I will work on it. 
Short version of the answer - we can't use the same docker-compose file to create token. It needs some update. 

A bit details in length: 
As part of the service dependence check in Fuji, we add an entrypoint in the entry of edgex-proxy as below:
entrypoint: >
      /bin/sh -c 
      "until /consul/scripts/consul-svc-healthy.sh kong; do sleep 1; done;
      until /consul/scripts/consul-svc-healthy.sh security-secretstore-setup; do sleep 1; done;
      /edgex/security-proxy-setup --init=true"
So the old way to pass "--init=false --useradd=user --group=admin" will not work as the container of edgex-proxy doesn't honor such command parameters any more. So we had two options during testing Fuji in the past:

1. start everything as normal, then update docker-compose.yml file to add one more entry of containers same as edgex-proxy, but remove the script part and replace it with original method of Edinburgh release, then use the original method to create token. 

2. use security-proxy-setup directly and pass "--init=false --useradd=user --group=admin" to create token. 

And of course a much better solution is to separate the functionality of creating token from edgex-proxy so that it can server the single purpose.

**Comment by bnevis-i** [comment]
How about this workaround instead?

```
docker-compose -f docker-compose-nexus.yml run --rm --entrypoint /edgex/security-proxy-setup edgex-proxy --init=false --useradd=user --group=admin
```

I do agree, however, that the current functionality of `security-proxy-setup` is overloaded.

**Comment by tingyuz** [comment]
I think the method from @bnevis-i of overwriting the entrypoint is the most the elegant approach among these three options. If there is no objection I will adopt it into our README for both project and wiki update.
