### ISSUE TITLE
Database transaction mechanism on updating device's properties

### ISSUE THREAD

**Issue by hahattan** [edgexfoundry/edgex-go#2281]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Metadata

### Is this a regression?

 No

### Description and Minimal Reproduction
This issue was found during resolving #2280, basically we need to do is move the [UpdateLastConnected logic](https://github.com/edgexfoundry/edgex-go/blob/dc418d78119841c12533dc76385ae689c1b3f3d2/internal/core/data/device.go#L53-L57) to Device SDK (which is already be finished in [#429](https://github.com/edgexfoundry/device-sdk-go/pull/429)).
But when 2 goroutines tries to update the same device (in this scenario, coredata trying to update `LastReported` and device SDK trying to update `LastConnected`), the behavior/result would be random/inconsistent: usually only 1 of the timestamp would be updated.   

## 🌍  Your Environment
**Deployment Environment:** macOS Catalina + docker-compose deploy

**EdgeX Version:** nightly-build

**Anything else relevant?**

**Comment by michaelestrin** [comment]
It sounds like you're executing two separate requests simultaneously that update different fields on the same object.  This is a classic problem -- thread A reads object, thread B reads object, thread A updates field Y, thread B updates field Z, thread A saves object, thread B saves object.  Result is thread A's update is lost.

This is expected behavior given our current implementation.
