### ISSUE TITLE
Tracking Error Handling Improvement Suggestions

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#2403]
I'm using this issue to track a discussion around how to improve error handling the EdgeX platform. This discussion was initiated in the Security WG (19-Feb-2020) due to the following comment

https://github.com/edgexfoundry/edgex-go/issues/2344#issuecomment-583589139

There were four things, according to my notes from the meeting, that we wanted to unpack later in more detail. I'll list them below and then refer to this issue as discussions occur in the various working groups.

- What information should get put into an error versus being logged? Should the error always be written to the log or should it just be returned to the caller?
- Error codes should be defined relative to the EdgeX platform and then used when responding to failures. Defining error codes helps to abstract error handling away from a specific language / transport.
- Hopefully through defining the above codes, we would clarify what are actual runtime errors (can't unmarshal type) versus valid states (item not found)
- What is the timeframe for undertaking this effort? Do we implement in V1 or in V2?

**Comment by michaelestrin** [comment]
There's also the question around whether application-level errors should be implemented as Golang Error implementations.  Things like "unable to unmarshal" or "item not found" are exceptional but known acceptable states to return in results.  The proposed APIv2 implementation (#2285, #2371) intentionally returned these as status codes (and not Golang errors); [example here](https://github.com/michaelestrin/edgex-go/blob/bd9a0a063ce530175d185e065745127683162a2a/internal/pkg/v2/infrastructure/persistence/memory/core/metadata/addressable/addressable.go#L52).

**Comment by bnevis-i** [comment]
| What information should get put into an error versus being logged? Should the error always be written to the log or should it just be returned to the caller?

What I have done in the past, and believe to be a good practice is.  (a) External interfaces (like HTTP APIs) return only HTTP error codes and generic errors when something goes wrong.  They should definitely NOT propagate error messages from lower layers.  Details about what went wrong should be logged.  (b) Internally, internally return typed exception classes that let the caller decide how to deal with errors at a granular basis, but log most of the details.  (c) In all cases, secrets like keys, passwords, HTTP Authorization headers, or fields that might accidentally contain sensitive information due to user error (e.g. putting password when the system asks for a username) should not be logged.

There may be an opportunity to borrow a little bit from Java w.r.t exception hierarchies like Runtime vs Checked exceptions to communicate errors that the caller should explicitly handle vs things that will just happen that you can't really do much about.
