### ISSUE TITLE
Scheduler container failed to find requires authentication 

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2433]
# 🐞 Bug Report

### Affected Services

 The issue is located in:  support-scheduler

### Is this a regression?

 -

### Description and Minimal Reproduction
Refer to [developer-scripts#233](https://github.com/edgexfoundry/developer-scripts/issues/233)

## 🔥 Exception or Error
```
level=ERROR ts=2020-03-11T08:08:16.1829089Z app=edgex-support-scheduler source=init.go:63 msg="Failed to load schedules and events command find requires authentication"
```

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Master

**Anything else relevant?**
This issue is currently blocking mongo no secuity Jenkins jobs.
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-centos7-blackbox-4c-2g-master/DATABASE=mongo,node=centos7-blackbox-4c-2g/6/console

**Comment by weichou1229** [comment]
It seems didn't retrieve the username and password from the consul.

The steps to reproduce:
1. Deploy EdgeX
```
docker-compose -f docker-compose-nexus-mongo-no-secty.yml up -d
```
https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-mongo-no-secty.yml

2. Navigate to http://localhost:48080/api/v1/reading
```
curl http://localhost:48080/api/v1/reading 
command find requires authentication
null
```
3. I can find Username and password on the Consul
http://localhost:8500/ui/dc1/kv/edgex/core/1.0/edgex-core-data/Databases/Primary/

4. Navigate to http://localhost:48080/api/v1/config
Username and password are both empty.
```
{
   "Service" : {
      ...
   },
   ...
   "Databases" : {
      "Primary" : {
         "Username" : "",
         "Password" : "",
         "Host" : "edgex-mongo",
         "Type" : "mongodb",
         "Name" : "coredata",
         "Timeout" : 501,
         "Port" : 27017
      }
   },
}
```

**Comment by bnevis-i** [comment]
Wondering out lout if this has something to do with what is present in types.go in go-mod-bootstrap.  Note that the credentials are referenced via a nested struct instead of being included literally.  This may be throwing off whatever kind of type introspection the code is doing to fill this struct up.

```
type Database struct {
	Credentials
	Type    string
	Timeout int
	Host    string
	Port    int
	Name    string
}

// Credentials encapsulates username-password attributes.
type Credentials struct {
	Username string
	Password string
}
```

**Comment by weichou1229** [comment]
@bnevis-i 
You are right, I change the Database struct
```
type Database struct {
	Username string
	Password string
	Type    string
	Timeout int
	Host    string
	Port    int
	Name    string
}
```

Then It can fetch the username password from Consul
```
	decoder := client.newConsulDecoder()
	decoder.Consul = client.consulConfig
        ...

	go decoder.Run()

	select {
	...
	case raw := <-updateChannel:
		configuration = raw
	}

	return configuration, err
```
https://github.com/edgexfoundry/go-mod-configuration/blob/master/internal/pkg/consul/client.go#L175

**Comment by bnevis-i** [comment]
@weichou1229  Great news!  I tried to fork the module, but then had to update all the edgexfoundry/go-mod-bootstrap references to my fork everywhere.  Been trying to get this going for hours.  I will abandon my futile attempt to validate this given your result and yet you push the necessary fixes.

**Comment by weichou1229** [comment]
But I 'm not sure that is the correct way to fix the issue.
@tsconn23 Could you help review this issue?

**Comment by bnevis-i** [comment]
When I send this the old data structure through fmt.Printf %v, the generic structure outputs as a nested data structure `{  { username, password } type, timeout, host, port name }` whereas flattening it should remove the artificial nesting.  Since before the mongo --auth fix, the database didn't require any password at all, I would guess that this implementation never worked, and that in the security-enabled case, passwords were injected via the secret store.  This behavior seems consistent with the failures we are observing with blackbox-testing.  I am not enough of a golang expert to figure out how to subvert go's module system to be able to test this change out easily at a system level.  @tsconn23, do you think we can try this fix and roll it back if it doesn't improve the situation?

**Comment by michaelestrin** [comment]
Based on what I've read, the proposed correction -- flattening the data structure -- is the correct one.  Raise a PR.  @weichou1229 

@bnevis-i go.mod's [replace](https://github.com/golang/go/wiki/Modules#when-should-i-use-the-replace-directive) should help you avoid making mass import name changes for testing in the future.

**Comment by weichou1229** [comment]
PR opened https://github.com/edgexfoundry/go-mod-bootstrap/pull/57

**Comment by bnevis-i** [comment]
```
   curl  http://localhost:48080/api/v1/config | python -mjson.tool

    "Databases": {
        "Primary": {
            "Host": "edgex-mongo",
            "Name": "coredata",
            "Password": "password",
            "Port": 27017,
            "Timeout": 5000,
            "Type": "mongodb",
            "Username": "core"
        }
    },
```

Configuration is now passing through after local testing with new go-mod-bootstrap, however, edgex-mongo appears to still not be provisioning passwords.
