### ISSUE TITLE
[Redis] ERR Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by jinlinGuan** [edgexfoundry/edgex-go#2516]
# 🐞 Bug Report

### Affected Services

 The issue is located in: 
edgex-support-scheduler
edgex-device-virtual

### Is this a regression?

 -

### Description and Minimal Reproduction
1.  Download nightly-build [docker-compose-nexus-redis-no-secty.yml ](https://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml)
2. `docker-compose -f docker-compose-nexus-redis-no-secty.yml up -d`
3. edgex-support-scheduler and edgex-device-virtual exited

## 🔥 Exception or Error
device-virtual log:
```
Couldn't register to metadata service: 500 - Could not dial Redis: ERR Client sent AUTH, but no password is set
level=ERROR ts=2020-04-23T07:09:14.5265911Z app=device-virtual source=service.go:86 msg="DeviceServicForName failed: 500 - Could not dial Redis: ERR Client sent AUTH, but no password is set\n"
```
support-scheduler log:
```
level=ERROR ts=2020-04-23T07:09:04.144541Z app=edgex-support-scheduler source=init.go:63 msg="Failed to load schedules and events Could not dial Redis: ERR Client sent AUTH, but no password is set"
```

## 🌍  Your Environment
**Deployment Environment:**
MacOS
**EdgeX Version:**
master

**Anything else relevant?**

**Comment by andresrinivasan** [comment]
Root cause is microservice is configured with a database password via `configuration.toml` and the Redis client code blindly sends the password even though EDGEX_SECURITY_SECRET_STORE=false. Redis (the DB) returns an error because it is not configured with a password and it is surprised to see the AUTH command. 

Updating the Redis client code to not send the password when EDGEX_SECURITY_SECRET_STORE=false.
