### ISSUE TITLE
Redis startup race condition - Not setting up DB credentials

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2542]
# 🐞 Bug Report

### Affected Services

 The issue is located in: All services using the database

### Is this a regression?

 No, Redis was not used in secure mode for Fuji

### Description and Minimal Reproduction
On a system similar to HP MP9 (16GB RAM, 125.5 GB DISK, 125.5 GB, Intel Core I7 2.8GHZ x8) running Ubuntu 18.04.3 LTS

- Stop any EdgeX stack currently running
- Remove stopped containers - `docker rm $(docker ps -aq)`
- Prune docker volumes - `docker volume prune`
- Run `docker-compose -f docker-compose-nexus-redis.yml pull` to make sure latest images are used
- Run `docker-compose -f docker-compose-nexus-redis.yml up -d`
- View logs for Support Scheduler and verify `Could not dial Redis: ERR invalid password` error
- If you get a `connect: connection refused` error.  Rerun the above steps and verify now get `Could not dial Redis: ERR invalid password` error.

## 🔥 Exception or Error
<pre><code>

Failed to load schedules and events Could not dial Redis: ERR invalid password
</code></pre>

## 🌍  Your Environment
**Deployment Environment:**
See above
**EdgeX Version:**
Geneva WIP

**Anything else relevant?**
Restarting Redis container and then restarting Support Scheduler container resolves the issue for Support Scheduler. All other services that require the DB also need to be restarted.
Also `docker-compose -f docker-compose-nexus-redis.yml down` followed by `docker-compose -f docker-compose-nexus-redis.yml up -d` resolves the errors.

**Comment by andresrinivasan** [comment]
@andresrinivasan 

Follow issue in [developer-scripts](https://github.com/edgexfoundry/developer-scripts/issues/273).

**Comment by tonyespy** [comment]
@andresrinivasan I see your two commits were merged, but I don't see a root cause described in the issue. Here's what I think was happening:

_If someone deploys edgex-secure-redis via compose, then brings it all down and prunes the volumes, the redis server password file in /tmp is still present, so if someone then brings up a fresh instance, a new password is generated in security-secretstore-setup, yet since the file exists in /tmp, the new password won't be read from vault. This results in the services using the new password, and the server using the old password_

Is that correct? I just want ensure there isn't an issue lurking in the snap. I don't think there is, as when a snap is removed all of it's writable data (even files in /tmp) gets removed.

Also in developer-scripts, you added a new `[ -s ] `condition to your password file check (which ensures the file size > 0). Is there ever a scenario where the file could be present by size=0?

And final questions, why did you add an exec to the redis command-line (just curious)?

**Comment by andresrinivasan** [comment]
@tonyespy 

Your description of the root cause is correct. My bad for not copying that into this issue.

Wrt `[ -s ]`, yes. I don't use any mechanism to guarantee that when the file inode becomes visible the content has already been writen.

The `exec` makes the redis process PID 1 in Docker instead of the shell process so Redis sees the SIGINT when the service is stopped gracefully (instead of the shell).

**Comment by tonyespy** [comment]
@andresrinivasan thanks for confirmation, and answers to my other questions.

Re: [ -s ], isn't it still possible for the the file to be partially written when this check is made? Wouldn't a semaphore file be safer?

**Comment by andresrinivasan** [comment]
Yes, in retrospect, the most correct implementation would have been to create the file under a temp name, fsync it, and then use a rename to make it visible. A semaphore file would work too.

Given the length of the password and the typical I/O buffer, it is unlikely for a partial write to occur.

When Geneva is released, I'm going to rewrite `security-secretstore-read` to eliminate the password file altogether and set the password directly in Redis.

**Comment by jpwhitemn** [comment]
Per security WG meeting, this issue is closed as the PR fixed for Geneva.  Creating a new issue for the Andre rewrite suggested going forward.
