### ISSUE TITLE
Reading Id not set when using Redis

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#2569]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Core Data Redis DB

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Fuji with Mongo & Geneva with Mongo. Unsure about Fuji with Redis

### Description and Minimal Reproduction

Edit Geneva Redis secure compose file to set App Service Configurable profile to http-export.
Create Postman Mock endpoint
Run Geneva Redis compose file
Edit App Service Configurable http-export pipeline in Consul to set the url for HttpJsonExport to the mock endpoint
View data sent to Mock endpoint which will look like this:
```
id: "34511beb-ba3f-43b2-a2dc-c2a40fd40422"
device: "Random-Boolean-Device"
origin: 1590508601358048800
readings: Array(1)
0: {…}
origin: 1590508601253235500
device: "Random-Boolean-Device"
name: "Bool"
value: "true"
valueType: "Bool"
```
Doing the same with Mongo compose file results in data exported that looks like this:
```
id: "7d698e4b-6916-4b91-aa76-52c5ef52f0af"
device: "Random-Boolean-Device"
origin: 1590511191026868700
readings: Array(1)
0: {…}
id: "31020d1a-e0c6-425f-87d3-ca506b3c1feb"
origin: 1590511190862357500
device: "Random-Boolean-Device"
name: "Bool"
value: "true"
valueType: "Bool"
```

## 🔥 Exception or Error

None

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
Geneva Redis

**Anything else relevant?**

**Comment by andresrinivasan** [comment]
I can take a look later this week. Can you attach all of your configuration files here?

**Comment by lenny-intel** [comment]
@andresrinivasan , simply running the Redis version of the compose file with Device Virtual generating the readings. I assume you can view the readings in the DB and see they don't have an Id value set?

**Comment by andresrinivasan** [comment]
That I can do

**Comment by tsconn23** [comment]
Unable to duplicate. Using the redis-no-secty docker compose, I see IDs for readings on events generated by device-virtual. If the flow is specific to an Application Service flow, please edit the title of the issue so it is scoped properly.
```
[
  {
    "id": "20dc2490-286a-405e-8186-4e48f145189b",
    "device": "Random-Integer-Device",
    "created": 1590515832786,
    "origin": 1590515832785706000,
    "readings": [
      {
        "id": "c9edf5b5-a2ae-41db-854a-61ec87c55574",
        "created": 1590515832786,
        "origin": 1590515832608827100,
        "device": "Random-Integer-Device",
        "name": "Int64",
        "value": "8524979692215781672",
        "valueType": "Int64"
      }
    ]
  },
  {
    "id": "240a4622-b111-4dca-8928-a2413d5b208a",
    "device": "Random-Integer-Device",
    "created": 1590515832386,
    "origin": 1590515832385515000,
    "readings": [
      {
        "id": "2c3bc45a-fc36-4056-b015-f4fafc1bb44c",
        "created": 1590515832386,
        "origin": 1590515832356031000,
        "device": "Random-Integer-Device",
        "name": "Int16",
        "value": "-3082",
        "valueType": "Int16"
      }
    ]
  }
]
```

**Comment by lenny-intel** [comment]
> Unable to duplicate. Using the Geneva redis-no-secty docker compose

@tsconn23 , very interesting. I used the secure Redis. Can you try to recreate with the secure version?

**Comment by tsconn23** [comment]
@lenny-intel Same result
```
[
  {
    "id": "37d9ee04-5270-4b47-9719-c8c075237b3d",
    "device": "Random-Boolean-Device",
    "created": 1590516626758,
    "origin": 1590516626754050000,
    "readings": [
      {
        "id": "bb89b770-f75f-4ad1-b993-eff8aff3a045",
        "created": 1590516626758,
        "origin": 1590516626508697600,
        "device": "Random-Boolean-Device",
        "name": "Bool",
        "value": "true",
        "valueType": "Bool"
      }
    ]
  },
  {
    "id": "468fc926-3178-49bc-ac3b-b25c0f0dfaa8",
    "device": "Random-Integer-Device",
    "created": 1590516632354,
    "origin": 1590516632353837600,
    "readings": [
      {
        "id": "32a8ccb4-0f02-4fa0-a0bc-1ad1277899be",
        "created": 1590516632354,
        "origin": 1590516632308813300,
        "device": "Random-Integer-Device",
        "name": "Int16",
        "value": "10877",
        "valueType": "Int16"
      }
    ]
  }
]
```

**Comment by lenny-intel** [comment]
@tsconn23 , are you pulling these from the DB?

**Comment by tsconn23** [comment]
From the core-data REST endpoint `http://localhost:48080/api/v1/event`

**Comment by lenny-intel** [comment]
Ok, so it is getting stored, but not set prior to sending on the Message Bus. I verified Id is set when app service receives it when using either of the Mongo configurations.

**Comment by lenny-intel** [comment]
@andresrinivasan,  I think the issue is here where the Id is created and persisted but then set on the reading, `r`, so that it is there when pushed onto the Message Bus.
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/data.go#L1085

**Comment by AnthonyMBonafide** [comment]
I will take a look at this issue.

**Comment by AnthonyMBonafide** [comment]
I did some digging and I am not sure how this is working for `Mongo`  and not `Redis`. As I see it, the problem is that the `Reading` IDs are not being populated after we are persisting the `Event`. 
https://github.com/edgexfoundry/edgex-go/blob/93a900b48c21df2a0611ee8b9bdbe214b0c3fa76/internal/core/data/event.go#L135-L142

Looking at the above code, I do not see how the `Reading` IDs are ever populated(even when using Mongo) since we are passing in a copy of the `Event` to the `AddEvent` method, so even if the `DBClient` hydrates the ID field for each `Reading` it would not be reflected in the `Event` variable `e` that is being used to publish via the `MessageBus`. 

My proposed solution is to do a "quick fix" by getting the newly persisted `Event` from the database, which will have the IDs generated and populated, and then populate the `Event` which is being used to respond to the user.

This is not the best solution, since it has a negative performance impact since we will need to make an extra database call(CPU), and also retain 2 copies of the `Event` structure(memory). However, this a simple solution that will allow us to get this issue resolved.

In the future, I think a better way to handle this is to define a database abstraction which either accepts a reference to the `Event`(`&e`) so that we can update the IDs and the caller will have access to the data, or we can return a new `Event` with all the information populated. I am a fan of returning a new `Event` to avoid side effects and possible bugs. This approach would be a big effort and would be something better left for V2 when we rework the APIs and the infrastructure layers.

I tested my "quick fix" locally and verified this issue is resolved.

Any thoughts?

**Comment by lenny-intel** [comment]
@AnthonyMBonafide , I agree that it is a bit strange that AddEvent is able to modify the Event/Reading when it appears to have a copy, but it is doing it... 

I used the Mongo AddEvent() as a guide and added `e.Readings[i].Id = id` here:
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/redis/data.go#L1085
And now I have Reading Ids when recieved off the Message Bus. 

Please give this a try and verify it works for you. THX!

**Comment by lenny-intel** [comment]
I am just going to create a PR with my change.

**Comment by AnthonyMBonafide** [comment]
Looking more deeply at this. The reason the `DBClient` is able to modify the IDs and the caller have access is because the type that is holding the `Reading`s is a `Slice` which will be passed by reference regardless if the `Event` is passed as a pointer or a value, so the method will have access to the original data. I still agree with a"quick fix" solution, but in the future I would strongly recommend not doing this since it is confusing, unclear, and takes advantages of possibly unwanted mutations of data.
