### ISSUE TITLE
Module exploration - remove or replace bitbucket.org/bertimus9/systemstat

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2614]
# 🚀 Feature Request

### Relevant Package
bitbucket.org/bertimus9/systemstat

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
Package imported here
https://github.com/edgexfoundry/edgex-go/blob/2ee4d1612d56aa2c3a9d1db8dcaf36afac99cebf/internal/pkg/telemetry/linux_cpu.go#L22

This file has a Linux OS build constraint so either attempt to remove and build locally using Linux or run a PR through the CI/CD pipeline
https://github.com/edgexfoundry/edgex-go/blob/2ee4d1612d56aa2c3a9d1db8dcaf36afac99cebf/internal/pkg/telemetry/linux_cpu.go#L1

**Comment by tonyespy** [comment]
To add a bit more context, the edgex-go internal telemetry package defines an OS specific version of cpu.go for linux and windows. The linux version uses the systemstat package which is what this issue is about. The reasons this package was flagged include:

 * the last commit was in Oct '15
 * there are no releases or tags
 * there are no bugs reported
 * there are three developers, and two of them have only authored single commits

While it's great that we were able to provide this functionality easily, this is a classic unmaintained package and as such, shouldn't be used in our code. I'd like us to entertain alternatives, including possibly forking such that we maintain it.

I'll also point out that the windows version of this internal package uses the unsafe package. Maybe it's unavoidable in this case, but I will note that [golang guidelines](https://golang.org/doc/go1compat#expectations) has this to say about its usage:

_Use of package unsafe. Packages that import unsafe may depend on internal properties of the Go implementation. We reserve the right to make changes to the implementation that may break such programs._

**Comment by cloudxxx8** [comment]
Thanks for the update, @tonyespy 
Windows CPU would be another topic to discuss.

After looking into the code of this module, it is a simple code and relies on the Linux proc file.
We can copy the code and create our own go module to maintain and remove this dependency, if we want.

**Comment by jpwhitemn** [comment]
It sounds like we should target this for eventual replacement (perhaps our own module per @cloudxxx8 ).  Does it make sense that we do this for Ireland release or does anyone feel we have to accelerate this for Hanoi?  Unless I hear otherwise, I am targeting Ireland release for possible replacement.

**Comment by jpwhitemn** [comment]
Should not cause breaking changes if replaced so a target for Jakarta??

**Comment by cloudxxx8** [comment]
it could be internal only

**Comment by cloudxxx8** [comment]
we have removed this dependency in the latest version
