### ISSUE TITLE
Module exploration - remove or replace github.com/kr/logfmt

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#2616]
# 🚀 Feature Request

### Relevant Package
github.com/kr/logfmt

### Description
Based on exploration of dynamically versioned packages, this one showed significant issues against the Gregg/Espy defined criteria.  Explore means to replace or exclude it from use.  Otherwise document why it must be kept.

**Comment by tsconn23** [comment]
This package was formerly a dependency of `github.com/go-logfmt/logfmt@v0.4.0`. A PR on that package has since been merged to eliminate the dependency.

https://github.com/go-logfmt/logfmt/commit/72090209a41223df99307d2e7a160cb4873a5ead

This means the reference in `go-mod-core-contracts` likely needs to be updated to point to latest.
https://github.com/edgexfoundry/go-mod-core-contracts/blob/06f35a91c3483fdb0f6c49f522d5f90e47e2d85a/go.mod#L6

**Comment by jpwhitemn** [comment]
Should not cause breaking changes if replaced so a target for Jakarta??

**Comment by lenny-intel** [comment]
Should be non-breaking internal change.

**Comment by cloudxxx8** [comment]
Decided in Core WG meeting on 12-DEC-2023.
We will fork the repository if we encounter any real issue for this lib.
It's a simple lib, so there is no plan to replace it.
