### ISSUE TITLE
How to configure two ports in configuration.toml file?

### ISSUE THREAD

**Issue by xuexiqiangzhe** [edgexfoundry/edgex-go#2623]
In the past，I run edgex by executing the following statement
sudo docker-compose -f docker-compose-nexues-redis-no-secty.yml up -d
and I discover that core-data with two ports
```
image: nexus3.edgexfoundry.org:10004/docker-core-data-go:master
    ports:
      - "127.0.0.1:48080:48080"
      - "127.0.0.1:5563:5563"
```

I want to make core-data service send messages to app service through messagequeue  on port 5563.
```
[MessageQueue]
Protocol = 'tcp'
Host = 'localhost'
Port = 5563
Type = 'zero'
Topic = 'events'
```
So,how to configure two ports in the configuration.toml file of core-data?

Thanks!

**Comment by lenny-intel** [comment]
@xuexiqiangzhe , the `ports` section in the compose file is just exposing those ports to the localhost so you can access them from a tool or app running on the localhost rather than in the docker network. Useful for testing an app and need to run it locally, not in docker.

core-data already sends messages to app service through Message Bus on port 5563, so not sure what you are trying to do. You can change the MESSAGEQUEUE_PORT via env override in the `environment` section of core data in the compose file, but you will also need to do an override of the MESSAGEBUS_SUBSCRIBEHOST_PORT on the application service so it receives on that port you changed core-data to send on. 

Not sure why you would need/want to change this port??

**Comment by xuexiqiangzhe** [comment]
@lenny-intel  
Maybe I didn't express myself clearly,sorry.

I used to use docker-compose.yml to start egdex, which has two ports configured for core-data
```
-"127.0.0.1:48080:48080"
- "127.0.0.1:5563:5563"
```
So core-data is able to sends messages to app service through Message Bus on port 5563.

But，now I use edgex-go package to start edgex, core-data sends messages to app service failed. 
```
Error reporting information is following
No device ''http:localhost:5563''
```
The file ''edgex-go/cmd/core-data/res/configuration.toml'' is configured with only one port 48080
```
[Service]
Host = 'localhost'
Port = 48080
Protocol = 'http'
```
So there is no port 5563.How to add 5563 port to core-data in its configuration file？

**Comment by cloudxxx8** [comment]
@xuexiqiangzhe you don't need to do further changes.  It's still defined in the [`MessageQueue]` section
https://github.com/edgexfoundry/edgex-go/blob/4c8b75db6bcf36065f6e2cf8696ea10020b74332/cmd/core-data/res/configuration.toml#L51-L56

How and where did you get the error message?  May we know the recreate steps?

**Comment by xuexiqiangzhe** [comment]
@cloudxxx8 Thanks for your reminder.
Now core-data is able to send messages to app service successfully,by repeating all the steps,including downloading edgex go again and compiling it.

I think I have changed following Host from '*' to 'localhost'.This is the cause of the error.I'm sorry to trouble you both.
 ```
[MessageQueue] 
 Protocol = 'tcp' 
 Host = '*' 
```

Thank you very much, @cloudxxx8 @lenny-intel
