### ISSUE TITLE
Improve core/domain/models JSON encoding

### ISSUE THREAD

**Issue by tonyespy** [edgexfoundry/edgex-go#314]
We recently made a change to the return value of device-service command REST endpoints, which now return Events and Readings instead of ResponseObject(s). The current JSON encoding of our core/domain/models struct is generating JSON which includes all members of a struct vs. only including required members and members with non-zero (for the type) values.

e.g.

`{"id":"","pushed":0,"device":"XDK01","created":0,"modified":0,"origin":0,"schedule":null,"event":null,"readings":[{"id":"","pushed":0,"created":0,"origin":1529592066,"modified":0,"device":"XDK01","name":null,"value":"0.00747"}]}`

Ideally the JSON for this response should look like this:

`{"device":"XDK01","readings":[{"origin":1529592066,"device":"XDK01","value":"0.00747"}]}`

This is being reported using the latest California code as of 20180621.

**Comment by tsconn23** [comment]
FYI -- https://golang.org/pkg/encoding/json/

The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string. 

As found [here](https://github.com/edgexfoundry/edgex-go/blob/california/core/domain/models/action.go):
```
URL string `json:"url,omitempty"`
```

**Comment by tsconn23** [comment]
@cloudxxx8 @andyf1967 What effect, if any, will this have on blackbox testing?

**Comment by cloudxxx8** [comment]
@tsconn23 this change should not impact blackbox testing.  if it causes any failed test case, we could modify the script to make it work, because this change is useful and reasonable.
However, the value 0 or false might not be a real empty value.  They might be something meaningful.  I thought we should not add "omitempty" to bool or numerical type fields.
@andyf1967 and @weichou1229, please correct me if anything wrong

**Comment by tsconn23** [comment]
@brandonforster To verify no adverse testing effects on a small subset of service calls.
