### ISSUE TITLE
feat(data): Make MaxEventSize a service configuration setting

### ISSUE THREAD

**Issue by judehung** [edgexfoundry/edgex-go#3237]
To avoid large data causing unexpected memory exhaustion when decoding the large payload (CBOR or JSON), maxEventSize was introduced as a limit 25MB for handling CBOR payload in edgex-go.  More details could be found at https://github.com/edgexfoundry/edgex-go/issues/2439

@lenny-intel made a good point in https://github.com/edgexfoundry/edgex-go/pull/3202#discussion_r589521540_, we should consider to make such limit configurable, so that users could adjust the event size value per system requirements.  Open this issue to track the status of such change.

**Comment by lenny-intel** [comment]
@cloudxxx8 , environment variables give us system level like configuration. We code consider as env var for this. Something to discuss at Core WG...

**Comment by cloudxxx8** [comment]
Oh, right.  We might just need a good configuration name.

**Comment by JamesKButcher** [comment]
@jpwhitemn @cloudxxx8 This is REST specific right? Is something similar needed for message bus?

**Comment by cloudxxx8** [comment]
@JamesKButcher this should be applied to both REST and message bus.

**Comment by JamesKButcher** [comment]
@lenny-intel suggests using MaxRequestSize as the setting here

**Comment by cloudxxx8** [comment]
This is not for the request payload, so I thought `MaxRequestSize` is not a proper naming.
The purpose of `MaxEventSize` is to limit the size of binary data read from the Device.
The purpose of `MaxRequestSize` should block the large size request sent by other clients.

**Comment by lenny-intel** [comment]
@cloudxxx8 Ok, so this needs to be a new setting only for Core Data. At the top level in the TOML (similar to scheduler [here](https://github.com/edgexfoundry/edgex-go/blob/main/cmd/support-scheduler/res/configuration.toml#L1)) or in a new section named something like [Data]. I am good with either.

**Comment by cloudxxx8** [comment]
@lenny-intel I think there are two topics we should discuss here:

1. Whether we should make two configuration for normal request size and event size.  My opinion is yes, because the original implementation doesn't limit the normal request size (default 0), and we have hard code event size limit 25 MB.
2. The original approach of event size limit is wrong.  It is only implemented in HTTP post API, and it just drop the additional binary without returning error.  The correct way in my onion is that check the payload size before parsing it and return http status code 413 if the payload is more than the limit.  Also, implement the same in the message subscriber, but it can only print error and drop the event.  I thought App Service should do the same.

**Comment by lenny-intel** [comment]
Ok, thanks for the refresh... :-)

**Comment by JamesKButcher** [comment]
@cloudxxx8 Question from Core WG meeting... should this setting also be on the Device SDK?  And avoid sending the request if it's too big?

**Comment by cloudxxx8** [comment]
yes, this can also be implemented in device sdk

**Comment by cloudxxx8** [comment]
@lenny-intel if the JSON or other encoding size is really large, should we also handle it?  they can also cause memory exhaustion.  why do we limit it to CBOR?  In this case, we should rename the config name to `MaxCborEventSize`

**Comment by lenny-intel** [comment]
@cloudxxx8 , the issue was specifically written for CBOR, but yes JSON might also, but doubt we would ever see it get that large with out binary data, which is then CBOR encoded... ;-) 

But my point above is we can't check the size before encoding it and if there was a issue with size it should fail the encoding.
