### ISSUE TITLE
Consul can’t be reached

### ISSUE THREAD

**Issue by gavinju** [edgexfoundry/edgex-go#3281]
# 📚 Docs or Wiki Bug Report

### Description
When running in source mode, consul cannot be accessed. This site(http://localhost:8500/ui/) can’t be reached.
But based on docker mode operation, you can register to consul.

## 🌍  Your Environment
edgex-go v1.3.1

**Comment by lenny-intel** [comment]
Need more details? Is this the health check from consul back to the non-docker deployed service? If so, yes this is known and is not a supported deployment, i.e. mixed. We are aware this is a common debug/dev deployment in which we ignore the health check errors.

**Comment by gavinju** [comment]
@lenny-intel  So,  In the production env, Do I have to deploy  based on docker ? 
Can I start edgex-core-consul based on docker mode?  Other services, such as: core-data, core-metadata use source code to compile and start?

**Comment by lenny-intel** [comment]
No, you can deploy non-docker as is done with the Snap deployments.
https://docs.edgexfoundry.org/1.3/getting-started/Ch-GettingStartedSnapUsers/

Mixing docker with non-docker can be problematic when the service running in docker is expected to callback to the service running non-docker since `localhost` in the docker service is the container itself, not the host machine. 

If you plan to deploy production w/o docker, you should consider using the snap deployment.

**Comment by jpwhitemn** [comment]
@gavinju - EdgeX does not dictate, stipulate or require that you deploy or install EdgeX in any way.  We provide Docker containers, Docker Compose files, example Kubernetes deployment files, and Ubuntu Snaps as options and samples, but you don't have to use any of those.  We try to remain agnostic with regard to deployment and orchestration - but that does not mean we have all the elements you might need to satisfy your own production deployment needs.  

You can certainly use some services in containers and other services outside of containers (what we call a hybrid mode), but this will often require you to change some of the configurations and accesses in order for it to work.  We see this type of hybrid model more in development than production (as outlined here:  https://docs.edgexfoundry.org/1.3/getting-started/Ch-GettingStartedHybrid/).  But again, just because it can be done, it doesn't mean the EdgeX project has all the options outlined in examples, documentation, or completed as full solutions you can use without some customization on your part.

I am going to close this issue as I don't think it is a bug in our documentation.  If anything, it would be a request to provide an enhancement to our documentation to provide and example that might help you more.  But for that, we need a little bit more detail on what you want to do, your use case, and the difficulties you are encountering.
