### ISSUE TITLE
Core Data Subscribe receives own messages published to MessageBus

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#3497]
# 🐞 Bug Report

### Affected Services

 The issue is located in: Core Data

### Is this a regression?

 No, subscribe is a new feature

### Description and Minimal Reproduction
Run edgex stack with Device Virtual and the following will be in Core Data's log

```
level=ERROR ts=2021-05-21T16:47:57.3060488Z app=core-data source=subscriber.go:65 msg="fail to persist the event, Event Id exists"
```

This is because the Pub/Sub is sending the messages Core Data publishes back to Core Data, Verified with Redis and MQTT MessageBus.

## 🔥 Exception or Error

```
level=ERROR ts=2021-05-21T16:47:57.3060488Z app=core-data source=subscriber.go:65 msg="fail to persist the event, Event Id exists"
```

**Comment by cloudxxx8** [comment]
The intuitive resolution is that when core-data receives an Event from message bus, check whether its existence by id from database.  However, if the persistData is turned off, it will cause an infinite cycle.
We need think more about it.

**Comment by cloudxxx8** [comment]
We should remove the PersistData configuration, and make the persistence mandatory in core-data.
https://github.com/edgexfoundry/edgex-go/blob/dfd83a2c80b22c5abde7548ed5ab1fe11263d6eb/cmd/core-data/res/configuration.toml#L4

Since Device Service can publish Event to the message bus on its own, there is no reason to send to core-data without persistence.
In this case, we can always check Event existence by id from the database before proceeding other behavior, if the Event comes from the message bus.

**Comment by lenny-intel** [comment]
@jpwhitemn , please add this one to this week's Core WG agenda. THX!

**Comment by jpwhitemn** [comment]
Lenny to experiment with multi-topic approach; will submit a PR when approach seems to work.

**Comment by lenny-intel** [comment]
@cherrycl , @cloudxxx8 , Per Test/QA WG meeting we have disable Core Data subscribing to MessageBus until a proper fix is in place.
