### ISSUE TITLE
[Metadata] Add notification after updating device entity

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#3601]
# 🚀 Feature Request

### Relevant Package

 This feature request is for core-metadata

### Description
The core-metadata V2 API should add a notification to `support-notification` after updating the device entity.

https://github.com/edgexfoundry/edgex-go/blob/0f46f9c91dceca59bd5ea8aaab086cfec78c4084/cmd/core-metadata/res/configuration.toml#L25-L29
https://github.com/edgexfoundry/edgex-go/blob/0f46f9c91dceca59bd5ea8aaab086cfec78c4084/cmd/core-metadata/res/configuration.toml#L46-L52

**Comment by cloudxxx8** [comment]
@tonyespy this is the feature we have implemented since Barcelona release, so there is no ADR
https://github.com/edgexfoundry/edgex-go/blob/3f34ef6f36250df298827e5642cbe8f0e70aa7b0/cmd/core-metadata/res/configuration.toml#L22

It can be disabled by default from here, if we make the decision
https://github.com/edgexfoundry/edgex-go/blob/69f0044378c84a2584b9cc14c244d921f2d7705f/cmd/core-metadata/res/configuration.toml#L46-L47

I can't find a proper document about this feature, either
