### ISSUE TITLE
[Command] core-command crashes when it can't access the device service successfully

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#3611]
# 🐞 Bug Report

### Affected Services

 The issue is located in: core-command

### Is this a regression? no

 Yes, the previous version in which this bug was not present was: ....

### Description and Minimal Reproduction

1. start a Device Service with a unreachable address, for example, `localhost.localdomain`
2. create a profile and device for this Device Service
3. execute a command

## 🔥 Exception or Error
see attachment [command-logs.txt](https://github.com/edgexfoundry/edgex-go/files/6777262/command-logs.txt)

## 🌍  Your Environment
**Deployment Environment:**

**EdgeX Version:**
v2.0.0

**Comment by weichou1229** [comment]
>  level=ERROR ts=2021-07-07T10:58:31.100950389Z app=core-command source=http.go:38 X-Correlation-ID=715a2d0c-7673-4d67-8c5d-bf7cb17cb41e msg="failed to send a http request -> Get \"http://localhost.localdomain:59990/api/v2/device/name/RandomDevice1/Switch\": dial tcp 127.0.0.1:59990: connect: connection refused"

>  2021/07/07 10:58:31 http: panic serving 172.18.0.14:45094: invalid WriteHeader code 0


1. When fail to send the HTTP request, client lib return the error with http code 0
    ```
   return nil, errors.NewCommonEdgeX(errors.KindClientError, "failed to send a http request", err)
   ```
   https://github.com/edgexfoundry/go-mod-core-contracts/blob/152c15f88b9e1c145499af1f47b8d68a35226704/clients/http/utils/common.go#L60

   ```
    ClientErrorCode int = 0
    ```
   https://github.com/edgexfoundry/go-mod-core-contracts/blob/152c15f88b9e1c145499af1f47b8d68a35226704/errors/types.go#L43

2. Since the http server lib doesn't accept the 0 http code, so the core-command crash , see https://golang.org/src/net/http/server.go
```
func checkWriteHeaderCode(code int) {
	...
	if code < 100 || code > 999 {
		panic(fmt.Sprintf("invalid WriteHeader code %v", code))
	}
}
```
