### ISSUE TITLE
How to handle Metric and Operation in k8s?

### ISSUE THREAD

**Issue by Imy123** [edgexfoundry/edgex-go#3695]
# 🚀 Feature Request

### Description
 A clear and concise description of the problem or missing capability...
![image](https://user-images.githubusercontent.com/17736269/131944411-9904498a-132c-4557-a05f-ddc08f900c62.png)
In k8s, can not do this operation, such as start,restart,stop

![image](https://user-images.githubusercontent.com/17736269/131944709-d63a17bd-28ee-4136-ae11-7567826151bb.png)
The metric can not work, because in k8s the container name is not exact

**Comment by cloudxxx8** [comment]
system management agent doesn't support k8s environment and this service is deprecated.

**Comment by jpwhitemn** [comment]
Hi @lmy123 - your enhancement request is really specific to integration with a particular type of deployment (in this case K8s).  We try to facilitate deployment options without being specific to any one of them.  Much of system management is provided as demonstration with implementations for Docker/Docker compose and Linux but it really requires you to implement your own once you our outside of our reference examples.

If you would like to make a contribution to help in this area, we'd be happy to explore your work.  Otherwise, I am going to move this to our Icebox and track it as a potential need, but one that is unlikely to get attention without others also asking for this feature specific to K8s and without members of the community willing to help do the implementation.

**Comment by JamesKButcher** [comment]
Yes I am going to close this for the above reasons. K8s support is not covered by the Foundry right now.
