### ISSUE TITLE
edgex with prometheus

### ISSUE THREAD

**Issue by ccb1900** [edgexfoundry/edgex-go#3705]
yes I search it but nothing

# 🚀 Feature Request

metrics 

### Relevant Package
nop.

### Description

I want to use edgex with prometheus,edgex metrics looks bad and can not be used with prometheus

### Describe the solution you'd like

ummm,you can tell me .

### Describe alternatives you've considered

may be I should integrate it myself?

**Comment by jpwhitemn** [comment]
hi @ccb1900 - thanks for submitting your enhancement request.  Getting data (whether sensor data or telemetry metrics) to Prometheus has been something that I have seen organizations successfully demonstrate on their own, but we do not yet have an open source contribution on this to date.  **We welcome a contribution in this area if you would like to help on the project. ** Otherwise, I am going to put this enhancement in the requirements Icebox as we have had past requests for it and we want to keep it in our backlog, but we haven't had enough requests nor a volunteer to help implement it in order to put it in any release roadmap plan yet.

**Comment by jpwhitemn** [comment]
Discussed in core WG of 9/9/21 - decision to move to Icebox pending requestor or other volunteer providing an implementation contribution.

**Comment by edgego** [comment]
@jpwhitemn How to join  contribution  for prometheus metrics ?  got simple implementation  for it.

**Comment by jpwhitemn** [comment]
Discussed in Kamakura planning meeting (Nov 21).  Did not make scope for Kamakura.  Move to **icebox** for future release planning.  Contributions welcome from the community - may be best suited as an [edgex-example](https://github.com/edgexfoundry/edgex-examples).

**Comment by edgego** [comment]
Have integrated prometheus into core-command , and device sdk. If need it can contribute code

**Comment by jpwhitemn** [comment]
@edgego - the working group has put this in the icebox for the time being until we get more details from you.  Can you provide more information on your proposed changes?  Have you submitted a PR yet?  It might be worth attending a [core working group meeting](https://wiki.edgexfoundry.org/display/FA/Core+Working+Group) to present your ideas - or at least coordinating with the working group chair (@JamesKButcher ) in order to make sure any code you do submit is in line with current efforts and EdgeX Roadmap.

Also, integrating 3rd party components like this are typically done as [edgex-examples](https://github.com/edgexfoundry/edgex-examples).  Note, for instance, that we have what I think is a similar integration to InfluxDB / Telegraf in the examples repository.  It is not a requirement to put your work here, but is something for you to consider. 

Please reach out to me if you have questions or concerns.

**Comment by edgego** [comment]
@jpwhitemn currently only collect prometheus metrics for device service and core-command, if need also can put code implement to core-metadata and core-data. Curently no need changes to device service side such as for edge-examples or device-modbus, only need change both device-sdk-go and device-sdk-c . the change result can checkhttps://github.com/edgego/device-opcua-go,  via grafana can monitor  throughput and status of  autoevent and command .   will raise a PR soon.

**Comment by edgego** [comment]
@jpwhitemn  detail steps for prometheus:
  1.  add prometheus metrics code to autoevent and command(from customer side no need any metadata or coredata's metrics to visualize ,so currently not change them).
  2.  config prometheus server to pull metrics(InfluxDB probably need push metrics , device service or core-command need some change)
  3. config grafana server to visualize metrics

**Comment by edgego** [comment]
@jpwhitemn 
raised 3 PR for prometheus metrics collecting:
Integrate prometheus metrics for command #3842
Prometheus metrics for device-sdk-go #1073
Prometheus metrics for device-sdk-c #388

**Comment by jpwhitemn** [comment]
@edgego (and @ccb1900 ) - your work has been looked at by members of our core working group.  We are not accepting this PR at this time.  From our perspective, export of data to Prometheus is not a responsibility of the command service or device services.  We are currently working on a more generic means to get EdgeX metrics/telemetry to any system via message bus.  You can find the [architectural decision record ](https://github.com/edgexfoundry/edgex-docs/pull/268) being debated now and provide your input to the ideas there.  Otherwise, we think simple export of data to something like Prometheus would be done by an application service similar to what has been done for [InfluxDB](https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/influxdb-export).

If you would still like to pursue your idea for this Prometheus integration, I'd invite you to present a proposal at one of the core working group meetings (providing more ideas about your design and why you think this is the best approach to solve your use case needs).  Coordinate with @JamesKButcher if you'd like to schedule time during one of the upcoming meetings.

**Comment by cloudxxx8** [comment]
close this issue due to no further activity.
please reopen it if there is anyone wants to continue to discuss it.
