### ISSUE TITLE
support-rulesengine delete rule by an inexistent name should return http status 503 

### ISSUE THREAD

**Issue by weichou1229** [edgexfoundry/edgex-go#377]
According RAML https://github.com/edgexfoundry/support-rulesengine/blob/master/raml/support-rulesengine.raml#L44 , expect **delete rule by an inexistent name should return http status 503** ,
actually it' return 200 .

**Comment by tsconn23** [comment]
@weichou1229 Why should it return anything other than a 200? The user asked to delete a resource. The resource isn't there. Why throw an error? Should be 500 anyway. We are getting rid of these 503 responses.

**Comment by weichou1229** [comment]
@tsconn23 Maybe use 404 ? ,
I saw coreData's RAML https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml#L113 , it return 404 when the entity cannot be found by id.

**Comment by cloudxxx8** [comment]
@tsconn23 I've reviewed the source code of core-data and core-metadata.
core-metadata returns 404 when invoking deleteByID API with an in-existent id, because it checks getByID before deletion:
https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/rest_device.go#L743
https://github.com/edgexfoundry/edgex-go/blob/master/internal/core/metadata/rest_deviceservice.go#L435

core-data deleteEventByID API also returns 404 for in-existent id by MongoClient 
https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/db/mongo/client.go#L84L102

However, the RAML file of support-rulesengine doesn't state the deleteByID API should return 404 for in-existent ID, so I am fine if you thought this issue could be closed as is.

What do you think?

**Comment by cloudxxx8** [comment]
@weichou1229 since the RAML API document doesn't state the in-existent id should return 404, please close this issue as invalid issue and remove the test case from blackbox test

**Comment by weichou1229** [comment]
Close issue and remove test case by https://github.com/edgexfoundry/blackbox-testing/pull/38
