### ISSUE TITLE
Images in the edgexfoundry dockerhub support multiarch

### ISSUE THREAD

**Issue by qclc** [edgexfoundry/edgex-go#3849]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

This feature request is for `edgexfoundry dockerhub`.

### Description [**REQUIRED**]
**The images in edgexfoundry DockerHub don't support multiarch**, that is, user can't pull images of different architectures based on the nodes.
Currently, user still need to specify different image names to pull images of different architectures, for example, edgexfoundry/docker-device-virtual-go: 
- amd64: `edgexfoundry/docker-device-virtual-go:1.3.0`
- arm64: `edgexfoundry/docker-device-virtual-go-arm64:1.3.0`

When using the openyurt and edgex integration solution locally, the following problems occur because the upstream image does not support multiarch:
If the cluster contains nodes of different architectures, when different components of Edgex are randomly deployed on different nodes in the cluster, the image may not match the corresponding node architecture. At this time, the image name can only be manually changed to run normally, which brings difficulties to the unified management of edgex deployment.
### Describe the solution you'd like
Hope all images(**version 1.3.0 and later**) in edgexfoundry DockerHub support multiarch(**amd64, arm64, arm**).

### Describe alternatives you've considered
If it is too much work to update all images at once, please support the images contained in `docker-compose.yml` first：

- edgexfoundry/docker-app-service-configurable:1.3.0
- edgexfoundry/docker-support-scheduler-go:1.3.0
- edgexfoundry/docker-support-notifications-go:1.3.0
- edgexfoundry/docker-device-virtual-go:1.3.0
- edgexfoundry/docker-core-metadata-go:1.3.0
- edgexfoundry/docker-core-command-go:1.3.0
- edgexfoundry/docker-core-data-go:1.3.0
- edgexfoundry/docker-edgex-consul:1.3.0

**Comment by JamesKButcher** [comment]
Discussed during Core Working Group call (3rd Feb):

One of the only pieces of information we obtain relating to docker downloads is the number of Intel vs ARM downloads that are made, so we don't want to lose that. However...

@farshidtz suggested it may be possible to define a multiarch parent image that refers to the specific Intel and ARM images. So our main compose files could refer to the multiarch, yet the actual downloads that are done are Intel or ARM.  So we'd have a simplified compose file and still continue to receive the Intel and ARM download stats.

@farshidtz also volunteered to research this further and see if this is possible. Thanks Farshid! Please comment here if you conclude anything here...

**Comment by farshidtz** [comment]
I gave this another try and can confirm that pulling the multiarch image created as described above only affects the stats of the multiarch image and not the underlying arch-specific ones.

I suggest either of the following:

1. Add multiarch images to dockerhub even though the project loses track of pull numbers per architecture. Is this information so essential to justify the added docker-compose files, documentation complexity, and deployment inflexibility?
2. Move images to Github Container Registry and separate amd64/arm64 by tag instead of image name. Github keeps track of pulls by tags. See below.
3. Consumers can work around this limitation by adding multiarch docker manifests based on existing images into their own private accounts (as explained in my previous comment). That should satisfy @qclc's use case but will affects the project pull stats.

---
Here, I have a pushed a docker manifest for two existing tags as follows:
```
docker manifest create ghcr.io/farshidtz/device-mqtt:2.1.0 \
               --amend ghcr.io/farshidtz/device-mqtt-amd64:2.1.0 \
               --amend ghcr.io/farshidtz/device-mqtt-arm64:2.1.0
```
Full image pulls are accounted for per tag:

![image](https://user-images.githubusercontent.com/11150423/155155853-1198dce2-0484-482c-aa6a-81acd96817b8.png)

This shown 20 amd64 pulls, 15 arm64 pull, and total 91 pulls, where for 56 cases, the underlying layers were cached and only the manifest was pulled.

**Comment by JamesKButcher** [comment]
Closing ticket as discussed in Core WG call today
