### ISSUE TITLE
security-bootstrapper listenTcp doesn't respond properly to SIGTERM

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/edgex-go#4087]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]
security-secretstore-setup

### Is this a regression?
No

### Description and Minimal Reproduction [**REQUIRED**]

Enter the container that is running this process

```
/edgex-init/security-bootstrapper --confdir=/edgex-init/res listenTcp --port=54322 --host=edgex-security-secretstore-setup
```

and send SIGTERM to it

```
kill -TERM (processid)
```

security-bootstrapper should exit immediately, but it doesn't.

This causes delays shutting down the framework.

## 🌍  Your Environment
**Deployment Environment:** Kubernetes  (should also be able to observe in Docker as well)
**EdgeX Version [**REQUIRED**]:** Jakarta Helm chart
**Anything else relevant?**

**Comment by drkfmorton** [comment]
After investigating this issue I have identified that service "security-bootstrapper -> edgex-security-secretstore-setup" is creating a SIGTERM notify listener and does shutdown gracefully. The service calls "go-mod-bootstrap\bootstrap.go:62" to create a SIGTERM notify. The reason the stopping of the application isn't immediate is because it uses "signal.stop" and cancels using the parent context. In the image you can see the process was killed using SIGTERM, as a new process was spawned afterwards. 

![image](https://user-images.githubusercontent.com/9958330/181057307-174327a0-7b9a-4e07-aa95-1c0230f34973.png)

**Comment by bnevis-i** [comment]
The original concern was that the security secretstore setup container had to be killed with SIGKILL instead of SIGTERM.  Given the info that SIGTERM is initiating the graceful shutdown, there is no work to be done here.
