### ISSUE TITLE
[Refactor] Move all the db related check to the infrastructure layer

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#4094]
# 🚀 Feature Request

### Relevant Package [**REQUIRED**]

 This feature request is for all

### Description [**REQUIRED**]
For some APIs, we need to check the object status in the database, and we wrote the logic in both application layer and infrastructure layer.  For example,
https://github.com/edgexfoundry/edgex-go/blob/66f7195aaa021911302e3f29534e7389e02a11e8/internal/core/metadata/application/device.go#L31-L42

Sometimes, they are duplicated
https://github.com/edgexfoundry/edgex-go/blob/66f7195aaa021911302e3f29534e7389e02a11e8/internal/core/metadata/application/device.go#L64-L73
https://github.com/edgexfoundry/edgex-go/blob/66f7195aaa021911302e3f29534e7389e02a11e8/internal/pkg/infrastructure/redis/device.go#L136-L142

### Describe the solution you'd like
Those db related checks should all be moved to the infrastructure layer for the following reasons:

1. The db connection can be reused
2. Those functions are transactional
3. For different database, they can be checked automatically.  For example, the duplicated id cannot be added to the tables in the normal relational database.  Thus, those should be infrastructure specific logic.

**Comment by FelixTing** [comment]
> https://github.com/edgexfoundry/edgex-go/blob/66f7195aaa021911302e3f29534e7389e02a11e8/internal/core/metadata/application/device.go#L64-L73
> 

In the application layer, calling DeviceByName is not only to check whether the device exists but also to obtain the device object for later use.

https://github.com/edgexfoundry/edgex-go/blob/b7de7b775397295cb69718a186a97b7526882c59/internal/core/metadata/application/device.go#L88-L90

I think we should leave it as it is. Otherwise we need to change the function signature of the DeleteDeviceByName function at infrastructure layer to return the deleted device.
