### ISSUE TITLE
Edgex on Raspberry Pi 3

### ISSUE THREAD

**Issue by akansal1** [edgexfoundry/edgex-go#424]
I am trying to run edgeX on raspberry pi via docker route, but not being able to do so. I wanted to know:

* If, it is possible to run it on Raspberry Pi 3 (OS raspbian) ?
* If Yes, then is there a guide that, I can refer ?

Thank you

**Comment by anonymouse64** [comment]
Unfortunately, to run on a Raspberry Pi 3, which is architecture armhf, you would have to build mongodb for ARM yourself on the Raspberry Pi (or cross compile it), which isn't supported officially. Because it's not officially supported, the project doesn't provide a docker build or a snap build that runs on ARM at the moment.
There are discussions to replace mongodb with something else, but it may or may get replaced with something else that does support ARM.

In the meantime if you're not comfortable compiling mongodb yourself, I'd suggest getting an arm64 board like the Dragonboard 410c and using that, as arm64 is a supported architecture.

**Comment by akansal1** [comment]
Understood, thanks
