### ISSUE TITLE
EdgeX with security device-virtual with consul

### ISSUE THREAD

**Issue by dipshirajput** [edgexfoundry/edgex-go#4240]
Hi @cloudxxx8 ,

I am running EdgeX with security where i am trying to run device-virtual with consul and facing the error as shown in screenshot.
core-data, core-metadata, consul are running correctly. 
please let me know for any suggestions. Thanks.
![dev-1](https://user-images.githubusercontent.com/52161957/204792533-0a99c0a9-ded6-4146-bcba-efb503e45531.png)

**Comment by cloudxxx8** [comment]
please provide the recreate steps
you can check the Consul GUI first to see whether the service registration IP is correct

**Comment by bnevis-i** [comment]
@dipshirajput 

Are you using EdgeX's Vault, or your own Vault.  There are some wierd things going on here:

`no token renewal since renewInterval is 0`

This message says that the secret store token isn't going to be renewed, either because it is not periodic (which means that once it expires, is in unrecoverably expired), or because it is already expired when you read it. Normally, it should read "30m0s" or thereabouts, which is half of the token TTL.

The other issue has to do with the registry access token, which is the proper length, but I'm wondering if it is working correctly -- is it valid, and does it have permission to query the consul service registry.  You have mapped the registry host to "myhost".  Are you sure  that is correct?  Are you exposing Consul to the outside network?  Is it running on the same machine?  Why not use "localhost" instead?

I don't know what exactly is wrong, but there is definitely something wierd going on with the secret store token and perhaps also consul secrets engine and related ACL mechanism.

**Comment by bnevis-i** [comment]
As this request is 6 months old, with no response, I am going to close this issue, presuming it has been resolved.
