### ISSUE TITLE
Retry Service Dependencies on Startup -- ExportClient

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#441]
This issue is for making changes to the export-client service so that it doesn't rely so much on an explicit start order when deployed to an environment. We should be able to start export-client independently of other services, and expect that it will start correctly. Upon startup, export-client should retry its connection attempts to other dependencies such as MongoDB and Consul rather than exit right away if those platforms aren't up yet. The overall retry window should be configurable.

An existing pattern for accomplishing this is already in place (see any core service)

**Comment by drasko** [comment]
@tsconn23 I did not like this approach - it is not the service logic where you want to put orchestration and deployment strategy. If service do not find an infrastructure prepared and ready it should die loudly. And orchestrator - for example `docker-compose` should be capable to restart the Docker container until it is up and running - here is an example of how this is handled in Mainflux: https://github.com/mainflux/mainflux/blob/master/docker/docker-compose.yml#L15

We can add demanded changes to align to other EdgeX services, but I would before to hear opinions of @nmarcetic, @anovakovic01 and @dusanb94.

**Comment by drasko** [comment]
Some references:
- https://blog.risingstack.com/designing-microservices-architecture-for-failure/
- https://www.infoworld.com/article/3254777/application-development/3-common-pitfalls-of-microservices-integrationand-how-to-avoid-them.html
- https://github.com/katopz/best-practices/blob/master/best-practices-for-building-a-microservice-architecture.md#connection-pools

> You should be careful with adding retry logic to your applications and clients, as a larger amount of retries can make things even worse or even prevent the application from recovering.

> In distributed system, a microservices system retry can trigger multiple other requests or retries and start a cascading effect. To minimize the impact of retries, you should limit the number of them and use an exponential backoff algorithm to continually increase the delay between retries until you reach the maximum limit.

>Fail Fast and Independently
>In a microservices architecture we want to prepare our services to fail fast and separately. To isolate issues on service level, we can use the bulkhead pattern. You can read more about bulkheads later in this blog post.

>We also want our components to fail fast as we don't want to wait for broken instances until they timeout. Nothing is more disappointing than a hanging request and an unresponsive UI. It's not just wasting resources but also screwing up the user experience. Our services are calling each other in a chain, so we should pay an extra attention to prevent hanging operations before these delays sum up.

> The first idea that would come to your mind would be applying fine grade timeouts for each service calls. The problem with this approach is that you cannot really know what's a good timeout value as there are certain situations when network glitches and other issues happen that only affect one-two operations. In this case, you probably don’t want to reject those requests if there’s only a few of them timeouts.

> We can say that achieving the fail fast paradigm in microservices by using timeouts is an anti-pattern and you should avoid it. Instead of timeouts, you can apply the circuit-breaker pattern that depends on the success / fail statistics of operations.

**Comment by tsconn23** [comment]
@drasko "If service do not find an infrastructure prepared and ready it should die loudly. And orchestrator - for example docker-compose should be capable to restart the Docker container until it is up and running"

OK, but this isn't the requirement I was given. The scenario as it was presented to me was more of a timing issue in that there had been problems where Go service containers came up more quickly than Mongo/Consul and services would exit right away without their upstream dependencies. I was asked to provide a bit of lee-way during the bootstrap process to account for a possible delay in order to eliminate the need to sequence container startup.

w/r/t the content you provided above, I agree with the points made. However, this sounds to me more like fail-fast patterns for service to service calls, which is certainly something we still need to address. I believe we have previously discussed the possibility of adopting something like GoKit for its Hystrix -like capability.

@jpwhitemn @tonyespy @SteveOss for visibility

**Comment by anonymouse64** [comment]
Just to comment on behalf of the snap here which doesn't use docker and instead runs services natively, something that's important for the snap to become more easily deployed with Delhi is to implement something like this.

In the snap, we currently just do like the docker file and include `sleep`'s in the startup script, which is ugly and undesirable. If the independent services were able to handle something like this, we could just make all the parts in the snap independent services which get started up in a random order by systemd.

I would also point out that in the snap we can order services to be run before/after other services, but we haven't done this yet, due to exactly the point @tsconn23 was making in that the service is executed, but not done "initializing" itself, and so from the standpoint of the orchestrator, i.e. systemd in the case of the snap, the dependent services can be launched, but they then fail because the original dependency wasn't done initialized itself quick enough.

One way to solve this that doesn't force the services to re-try themselves is to have the orchestrator start the service and then wait for a signal from the service to tell that it's ready. An example would be [systemd-notify](https://www.freedesktop.org/software/systemd/man/systemd-notify.html), but I don't know how that works with docker-compose (or if there's some other way to do the same thing in docker-compose) and would probably only be applicable to the snap.

**Comment by drasko** [comment]
> he service is executed, but not done "initializing" itself, and so from the standpoint of the orchestrator, i.e. systemd in the case of the snap, the dependent services can be launched, but they then fail because the original dependency wasn't done initializing itself quick enough.

I do not see problem in this - service will fail but will be restarted by an orchestrator over and over again until first service (prerequisite) has finished "initializing" itself and then second service will succeed.

Whatever orchestrator and/or watchdog timer you use this scenario should work, and is better and more safe than having cascading timeouts with unpredictable backoff IMHO.

**Comment by tonyespy** [comment]
@drasko Do you really think sleeps in a docker-compose file are a good idea?  ;)-

As @anonymouse64 pointed out, the edgex snap currently also has to rely on sleeps in a start shell script instead of the preferred approach of making all of the services in the snap daemons, which in turn would let systemd manage them.  If/when we make this change to the snap, an edgex instance would start automatically at system boot, and gain some measure of faul-tolerance as service crashes could be handled automatically by systemd.

Ian's suggestion of adding optional sd-notify support is also a really good idea. @anonymouse64 could you file an issue for this? You might want to mention that full software watchdog support is possible using sd-notify, and maybe that's controllable by a config setting as well?

The requirement that services must check that their own dependencies are available before becoming operational was decided on and incorporated in our project-wide [Service Name Design](https://wiki.edgexfoundry.org/download/attachments/7602423/ServiceNameDesign-v6.pdf?version=1&modificationDate=1523468903000&api=v2) (v6) document, which was finalized and listed in April on our [Architecture & Decisions](https://wiki.edgexfoundry.org/display/FA/Architecture+Issues+and+Decisions) wiki page.

**Comment by drasko** [comment]
@tonyespy sleeps and other timeouts os exactly what I would like to avoid. I proposed removing all timeouts on service starting. Just start services in correct order, an if one does not find it's dependency currntly (which will happen in rare occasions), let it crash and restart in a loop until it does. docker-compose.yaml manages this for you automatically with "restart on fail" directive.
