### ISSUE TITLE
[Common Config Bootstrapper] Apply env overrides to values only when loaded from file

### ISSUE THREAD

**Issue by lenny-intel** [edgexfoundry/edgex-go#4448]
As decide in 3/15/2023 Architects meeting, Config Provider will be the System of Record for services' values. 
This means that env overrides are only applied when configuration is loaded from file, including the common config file.
They are not applied to values loaded from Config Provider.
The overridden values are pushed into the Config Provider the first time the service starts or when the -o flag is used.

**Comment by lenny-intel** [comment]
On hold until overrides are applied and pushed into Config Provider and verify that it resolves this issue.

**Comment by cloudxxx8** [comment]
@farshidtz if we don't push the environment overrides to the Config Provider during the **first time** startup, the Config Provider would be seeded with the default config files only.  For example, the other service client host will be `localhost` instead of `core-metadata`, which is the correct host name in the docker network environment.  We leverage the environment variable overrides to adjust the config in the docker-compose files.  It won't work in docker environment if we don't push the initial values.

**Comment by farshidtz** [comment]
The Common Config ADR is being modified to formalize the decisions: https://github.com/edgexfoundry/edgex-docs/pull/1025
