### ISSUE TITLE
Status code should return 207 instead of 503 when post/patch devices with not running device-service

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4478]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: Metadata

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX by [compose file](https://github.com/edgexfoundry/edgex-compose/blob/d3abd814d7ee08bb719e32901cdf7f306f4b71a8/docker-compose-no-secty.yml)
2. Post device and the serviceName is not created, example as below
```
[
    {
      "device":{
         "origin":1471806386919,
         "name":"Test-Device",
         "description":"Test-Device",
         "adminState":"UNLOCKED",
         "operatingState":"UP",
         "protocols":{
            "other":{
               "Address":"simple01",
               "Port":"300"
            }
         },
         "labels":[
            "device-sample"
         ],
         "location":"{lat:45.45,long:47.80}",
         "serviceName":"device-test",
         "profileName":"Random-UnsignedInteger-Device"
      },
      "apiVersion":"v2"
   }
]
```

## 🔥 Exception or Error
<pre><code>

Status code returns 503 with message "HTTP request timeout"
</code></pre>
Expect to return 207 on outside level with 503 status code inside 

## 🌍  Your Environment
**Deployment Environment:** Ubuntu / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by cloudxxx8** [comment]
@lenny-intel I discussed this issue with @jinlinGuan .  If we call an in-existed device service for device validation, we will always get timeout, and it will become core-metadata timeout for the client, because the timeout of device service call and core-metadata rest request call is the same.
https://github.com/edgexfoundry/edgex-go/blob/d6c81549b4558d5b86ba0b804c244a1077168aa0/internal/core/metadata/application/notify.go#L26-L31

We should check the device service existence before calling the device validation.  If the device service doesn't exist, add Device API should return 400 bad request wrapped by 207.
