### ISSUE TITLE
Got error "Unable to parse JWT for call ..." on core-command when get command by kuiper rule with security enabled

### ISSUE THREAD

**Issue by cherrycl** [edgexfoundry/edgex-go#4508]
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: core-command, rules-engine

### Is this a regression?

 Yes

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX with [compose file](https://github.com/edgexfoundry/edgex-compose/blob/8a22ffe3ee580c257e50e40c2b53eff48da465fe/docker-compose.yml) 
2. Create stream by rules-engine
```
POST https://locahost:8443/rules-engine/streams
{
    "sql": "create stream edgexsource() WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"
}
```
3. Create rules by rules-engine
```
POST https://locahost:8443/rules-engine/rules
{
   "id":"rest-rule-0",
   "sql":"SELECT * FROM edgexsource WHERE Uint8>=0",
   "actions":[
      {
         "rest":{
            "url":"http://edgex-core-command:59882/api/v2/device/name/Random-Integer-Device/Int16",
            "method":"PUT",
            "dataTemplate":"{\"Int16\":\"123\"}",
            "sendSingle":false
         }
      }
   ]
}

```
## 🔥 Exception or Error
Found the following error on core-command and rules-engine services.
<pre><code>
core-command
level=ERROR ts=2023-04-11T09:14:11.431321449Z app=core-command source=auth_middleware.go:68 msg="Unable to parse JWT for call to '/api/v2/device/name/Random-Integer-Device/Int16'; unauthorized"

rules-engine
time="2023-04-11 09:14:31" level=warning msg="sink collect error: io error: http error Unauthorized\n" file="node/sink_node.go:183" rule=rest-rule-0
</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu22 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

**Comment by lenny-intel** [comment]
This is always going to be an issue as eKuiper will never have the JWT. We could try going through the API Gateway, but again, eKuiper will not have the gateway token.

@bnevis-i , thoughts?

**Comment by bnevis-i** [comment]
> This is always going to be an issue as eKuiper will never have the JWT. We could try going through the API Gateway, but again, eKuiper will not have the gateway token.
> 
> @bnevis-i , thoughts?

1. If Kuiper was invoked via a REST API call, that API might have a JWT on its request that could be forwarded back to EdgeX (requires changes in Kuiper)
2. Could modify Kuiper like we did for support-scheduler and make it JWT-aware somehow. (requires changes to Kuiper)
3. If invoking an EdgeX service, e.g. core-command, disable JWT validation for that service. (workaround; env var override in the docker-compose)

**Comment by lenny-intel** [comment]
@bnevis-i 
> 1. If Kuiper was invoked via a REST API call, that API might have a JWT on its request that could be forwarded back to EdgeX (requires changes in Kuiper)

Kuiper is invoked via MessageBus.
 
> 2. Could modify Kuiper like we did for support-scheduler and make it JWT-aware somehow. (requires changes to Kuiper)

Yea, I wonder if their REST action spec in the rule can take a JWT. But it would be in plain text since eKuiper doesn't have access to our SecretStore. :-(

> 3. If invoking an EdgeX service, e.g. core-command, disable JWT validation for that service. (workaround; env var override in the docker-compose)

Is this built in already? I wouldn't think this is a good thing as it does end around the secure endpoints

**Comment by bnevis-i** [comment]
> @bnevis-i
> 
> > 1. If Kuiper was invoked via a REST API call, that API might have a JWT on its request that could be forwarded back to EdgeX (requires changes in Kuiper)
> 
> Kuiper is invoked via MessageBus.
> 
> > 2. Could modify Kuiper like we did for support-scheduler and make it JWT-aware somehow. (requires changes to Kuiper)
> 
> Yea, I wonder if their REST action spec in the rule can take a JWT. But it would be in plain text since eKuiper doesn't have access to our SecretStore. :-(

Would need the ability to invoke an external module to provide it.  JWT's are bearer tokens and they need to be fresh.

> 
> > 3. If invoking an EdgeX service, e.g. core-command, disable JWT validation for that service. (workaround; env var override in the docker-compose)
> 
> Is this built in already? I wouldn't think this is a good thing as it does end around the secure endpoints

https://github.com/edgexfoundry/go-mod-bootstrap/blob/main/bootstrap/handlers/auth_middleware.go#L94

```
EDGEX_DISABLE_JWT_VALIDATION=true|y|Y|1
```

**Comment by lenny-intel** [comment]
> EDGEX_DISABLE_JWT_VALIDATION=true|y|Y|1

@bnevis-i, This needs to be added to the docs here: https://docs.edgexfoundry.org/3.0/microservices/configuration/CommonEnvironmentVariables/#standard-environment-variables

I think the other security Envs are also missing from this section.

**Comment by bnevis-i** [comment]
> > EDGEX_DISABLE_JWT_VALIDATION=true|y|Y|1
> 
> @bnevis-i, This needs to be added to the docs here: https://docs.edgexfoundry.org/3.0/microservices/configuration/CommonEnvironmentVariables/#standard-environment-variables


Docs update here:
https://github.com/edgexfoundry/edgex-docs/pull/1021

**Comment by bnevis-i** [comment]
5. Add an OAuth2 hook to the eKuiper rules (perhaps inject a private server into the eKuiper container that is accessible over localhost)

See https://ekuiper.org/docs/en/latest/guide/sources/builtin/http_pull.html#global-http-pull-configurations

**Comment by cloudxxx8** [comment]
According to the discussion in Core WG meeting on April 11 2023, we decided to skip Kuiper tests until we fix this issue.

**Comment by bnevis-i** [comment]
6. Modify the eKuiper EdgeX plugin

**Comment by bnevis-i** [comment]
So I've been thinking about this issue.  Here is where I currently sit:

### EDGEX_DISABLE_JWT_VALIDATION

Still seems to be the most expedient way.

### Message bus option

As in https://ekuiper.org/docs/en/latest/edgex/edgex_rule_engine_command.html#option-2-use-messaging but looking at that it doesn't appear as if there is a way to authenticate to the external message bus.  The example seems to imply that the message bus will just take any client that connects to it, which isn't right.

### OAuth method

As in https://ekuiper.org/docs/en/latest/guide/sources/builtin/http_pull.html#global-http-pull-configurations.  I performed a small prototype where I created an HTTP server that returned a JWT, and fed it into the request as prescribed, and it worked just fine.  However, in the example, the authentication credential is right there in the configuration.

In the simplest case, I could inject a small token service inside the eKuiper container.  Because it was "inside" it would be trusted.  However, because we also need to support snap-based deployments, creating such a service would be a back door when it listened on the host's localhost interface.  Thus, that solution is docker specific.

For something that would work with snaps, we would have to make it an internal (authenticated) API.  However, since eKuiper itself isn't authenticated, any client could just connect to eKuiper, read the rules config, and get whatever secret was there.  Thus, regardless of the authentication method (API key, client_id/client_secret, vault username/password, etc), because eKuiper itself is not secure, we're just creating a backdoor and thus authenticating ekuper would be security theatre.

### Custom EdgeX plugin

Having a way to for eKuiper to securely drop something into the EdgeX message bus seems to best way. After all, eKuiper can already authenticate in secure mode.  But none of the http nor mqtt rule examples really show how this integration as it exists today would work for a rule action.
