### ISSUE TITLE
DeviceProfile upload issue on booleans

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#46]
When uploading device profiles, the LSB value of "true" or "false" causes errors (it is not interpreted as a boolean).  Setting it to true or false results in a null value for LSB.  There may be other properties that are not getting loaded correctly.

**Comment by tsconn23** [comment]
@jpwhitemn I tracked this down to the capitalization of the LSB field itself in the device profile. If the field in the YAML is capitalized, it will not map to the field as the mapping metadata in our application is looking for "lsb". All fields when we do mapping are lower-cased, which is why the other properties work.
