### ISSUE TITLE
Test failure -- Metadata/provisionwatcher AssertionError

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/edgex-go#481]
Test failure reported as follows:
```
12:31:05 [info] ======================== Start run metaData test - provisionwatcher ========================

12:31:14   #  failure         detail                                                                         
12:31:14                                                                                                     
12:31:14  1.  AssertionError  Response time is less than 400                                                 
12:31:14                      expected false to be truthy                                                    
12:31:14                      at assertion:1 in test-script                                                  
12:31:14                      inside "provisionwatcher / 307 http://localhost:48081/api/v1/provisionwatcher
```

Full Jenkins log here:
https://jenkins.edgexfoundry.org/view/blackbox-testing/job/blackbox-testing-centos7-blackbox-4c-2g-california/61/consoleFull

**Comment by weichou1229** [comment]
@tsconn23 

In below picture, script assert response time is less than 400 and test result is 312ms. Assertion should be passed, but it didn’t.
![image](https://user-images.githubusercontent.com/11187505/44143008-9fe45816-a0b4-11e8-85cf-3998f659c233.png)


Because the script is inconsistent at https://github.com/edgexfoundry/blackbox-testing/blob/master/bin/postman-test/collections/core-metadata.postman_collection.json#L2576,

> tests[\"Response time is less than \"+data.responseTime] = responseTime < 200;

Actually it’s test responseTime<200.

I had created a PR https://github.com/edgexfoundry/blackbox-testing/pull/68.
