### ISSUE TITLE
Command call not being logged after following API Walkthrough

### ISSUE THREAD

**Issue by mhall119** [edgexfoundry/edgex-go#491]
Following the API calls in this walkthrough document, the PUT command is supposed to return a 503: Service Unavailable error (which is correct, as we're mocking the device in the walkthrough). But in reality it returns a 502: Bad Gateway error.

https://github.com/mhall119/edgex-go/blob/new-walkthrough/docs/walk-through/Ch-WalkthroughCommands.rst#execute-a-command

The command following this is a GET to the logging service which is supposed to have recorded the command being called (and failing) but no such information is shown.

These new docs are a refactor of the older ones on https://docs.edgexfoundry.org/Ch-ExamplesAPIDemo.html but the substance and sequence of the API calls is the same.

**Comment by jpwhitemn** [comment]
I just went through the walkthrough and confirmed that the code change did occur to return a 502 versus original 503 error response in command. According to HTTP documentation, 503 is suppose to suggest a "temporary state" on service unavailable so these were changed to 502 errors in some refactoring recently. So the system is working correctly, but the Walkthrough documentation should be update to say return 502 (not 503). I do see the Error coming from Command when I look at the Command service log (docker-compose logs -f --tail=100 command), and I also see the log entries make it into the database. However, when I query the log service via the Log API, the log entries aren't showing up. I think we have an issue with some query capability in logging. I am going to check with @feclare on the query to see if I can get some help on logging API/queires (the blackbox tests for this are passing, so I am not sure if I am querying correctly). I am going to close out the issue however since the logging issue is unrelated to this document change.
