### ISSUE TITLE
Addressable object should be extended

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/edgex-go#551]
So far, the design of Addressable is more HTTP friendly.  We encountered several issues about the insufficient fields of Addressable on different protocols.  For example:

1. There is no field for Modbus RTU, so the current Modbus Device Service (Java) borrow the address and path field.
https://wiki.edgexfoundry.org/display/FA/Modbus+-+Adding+a+device+to+EdgeX
2. There is no field to put key and cert for the connection with higher security requirement.

We had better to add some fields for the common security related requirement, such as key, cert, or vault.  Also, we could add a generic object field for flexible extension of other protocols.

**Comment by davidmsh** [comment]
This is coming from my work for AWS export distro support. AWS (as with Google Core IoT, sometime MQTT) requires cert/key pair for connection but we do not have such properties in Addressable today. Current workaround is to define a export distro wide of cert/key in configuration.toml. The downside is obviously that we can only have one set of cert/key within an instance of export distro. I ever try to reuse current properties username and password for certificate and private key, only found that Google IoT core make user both cert/key and username/password, so we can reuse username/password. This probably true for reusing other properties since you will never know it will cause such conflict in the future or not. So here comes the issue that we should probably extend addressable object to suit those requirements.
@jduranf @feclare @drasko your thought ?

**Comment by jpwhitemn** [comment]
Cloud - refactor on Addressable is something we have always meant to come back to.  I don't think this happens in Delhi (impact too wide and deep).  Could happen for Edinburgh (a target we should set), but also will require more conversation in the Core WG - so as we don't have to make additional changes to Addressable in the future (to address other needs, Clouds, protocols, etc.)  Leave in @tsconn23 to cover in WG agenda as needed and put in roadmap after discussed.

**Comment by cloudxxx8** [comment]
@jpwhitemn Yes, we understand it won't happen in Delhi.  We just filed this issue for record and my team member is writing a proposal for this.  We could discuss in WG and Edinburgh.

**Comment by davidmsh** [comment]
hi @jpwhitemn @tsconn23 I have prepared a write-up here [https://docs.google.com/document/d/1LawSpfUZ52FiVOkq0zISF9wRpcU-cxWpLDGgd1V-D2U/edit?usp=sharing](url) for the proposal to extend Addressable in the future. Feel free to comment and let me know when do you want to discuss it in WS call.

**Comment by jduranf** [comment]
Duplicated with #831. Please reopen if I'm wrong.
