### ISSUE TITLE
ExportClient exits with zero on failure

### ISSUE THREAD

**Issue by nfode** [edgexfoundry/edgex-go#638]
I am trying to deploy EdgeX with Docker Swarm. 
Docker swarm provides  the possibility to deploy a docker-compose file with [docker stack deploy](https://docs.docker.com/engine/reference/commandline/stack_deploy/). 
The problem is now that docker swarm ignores `depends_on` and therefore the ExportClient fails because of problems to connect to consul or not connecting to the database. 

Docker Swarm has a [restart_policy](https://docs.docker.com/compose/compose-file/#restart_policy) to avoid the problem of failed containers, but `restart_policy` only works if the container exists with a non zero exit code ([more info](https://docs.docker.com/config/containers/start-containers-automatically/)), which the export client not does. 

I can understand that the export client exists with 0 after the timeout is reached since it is somehow a "normal" behaviour, but would not a none zero code be better? I am happy to learn what led to this decision. 

And I am right that the only solution to avoid the problem is to set the timeout to a high number?

Thanks in advance!

**Comment by tsconn23** [comment]
Can you confirm whether you're using one of the published docker-compose files or if you're building images from the master branch?

https://github.com/edgexfoundry/developer-scripts/tree/master/compose-files

If using one of these, which one?

**Comment by tsconn23** [comment]
FYI for community knowledge -- specifying restart_policy in docker-compose.yml
https://docs.docker.com/compose/compose-file/#deploy

**Comment by nfode** [comment]
I am using the [docker-compose.yml](https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose.yml) from the developer scripts repo, with the change that the export-client and export-distro are modified to export to another platform and are based on commit [bd1091f36a3b16c206bcaf00cc8778e341bfd802](https://github.com/edgexfoundry/edgex-go/commit/bd1091f36a3b16c206bcaf00cc8778e341bfd802). 

After increasing the export-client timeout the startup now works. What I am now worried about is what if a start the stack deploy on a slower machine, then I still can not use the restart_policy.

It seems like in general the export client never exit with a non zero code on failure? I had trouble with the old consul microservice since the export-client configuration changed and it also failed with a zero exit code.

**Comment by rsdmike** [comment]
Looking at a couple services, it looks like  `main.go` simply `returns` when there is a failure (i.e during service bootstrap) instead of calling `os.Exit()` passing the appropriate exit code. Perhaps this is something that should be looked at a little closer across all services? 

Example:
https://github.com/edgexfoundry/edgex-go/blob/259da289a9b65e406b8be93641a50bcfadd05a82/cmd/core-data/main.go#L53

**Comment by jpwhitemn** [comment]
Agree Michael - consistency is better.  I'd ask Trevor to put this on the agenda for the next Core WG and we can then work it across DS and Appl WG from there.

    On Tuesday, January 8, 2019, 12:13:41 PM CST, Mike <notifications@github.com> wrote:  
 
 
Looking at a couple services, it looks like main.go simply returns when there is a failure (i.e during service bootstrap) instead of calling os.Exit() passing the appropriate exit code. Perhaps this is something that should be looked at a little closer across all services?

Example:
https://github.com/edgexfoundry/edgex-go/blob/259da289a9b65e406b8be93641a50bcfadd05a82/cmd/core-data/main.go#L53

**Comment by tsconn23** [comment]
Question -- When we say "appropriate exit code" what specific value would that be? Calling os.exit() instead of return isn't that controversial so I think we can just come up with a decision here.

Adding @anonymouse64 for visibility and to see if there's a value preferable for the Snaps.

**Comment by nfode** [comment]
Docker Swarm has the restart policy on-failure which is describes as:
> Restart the container if it exits due to an error, which manifests as a non-zero exit code.

Based on [this list](http://www.tldp.org/LDP/abs/html/exitcodes.html) exiting with code 1 on error should be sufficient.

**Comment by tsconn23** [comment]
OK, if that doesn't cause heartburn for anyone on the thread, returning 1 it is.

**Comment by tsconn23** [comment]
Decision made applicable to all edgex services. Closing this issue and replacing with #1017.
