### ISSUE TITLE
schedule time field between API document and code implementation are inconsistent 

### ISSUE THREAD

**Issue by yanghua** [edgexfoundry/edgex-go#76]
hi @jpwhitemn and @drasko I'm testing the schedule microservice I have done. But I find the time fields' type (start/end) of `Schedule` model are inconsistent in two places. 
The [API document](https://wiki.edgexfoundry.org/display/FA/APIs--Supporting+Services--Scheduling) says using _ISO 8601_.
However, the current [golang implementation](https://github.com/edgexfoundry/edgex-go/blob/master/core/metadata/rest_scheduleevent.go#L44) parses there fields as _millisecond string_.

So which one is right?

**Comment by drasko** [comment]
@jpwhitemn opinion?

**Comment by drasko** [comment]
@jpwhitemn ping

**Comment by jpwhitemn** [comment]
@drasko - thanks for the ping.  Missed this one.  @yanghua - there does appear to be an inconsistency.  The Java code was using ISO 8601 formats (thus the API documentation).  The Go versions have appeared to abandoned that.  Most of the scheduling is done by frequency (versus start/end) which is why it probably hasn't been detected.  If we can, we should return to the original API documented version.

**Comment by yanghua** [comment]
Have made sure the issue exists, so when support schedule module been reviewed and merged, I would fix it's time problem. Now closing it...

**Comment by jduranf** [comment]
@yanghua any idea when the support schedule module will be merged?

**Comment by yanghua** [comment]
hi @jduranf it seems we need to wait until core service refactor completely.

**Comment by jduranf** [comment]
ok, thank you!
