### ISSUE TITLE
Start Consul so that configuration is preserved (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#827]
provide the means to start Consul so that the configuration information is preserved and config-seed does not repopulate (or overwrite) the configuration already in Consul.  This will allow the setting of configuration by the SMA.

**Comment by tsconn23** [comment]
So we have a challenge here w/r/t persisting information in Consul. The reason is that the docker image provided by Consul starts the service with the "-dev" cmd line parameter. Per [this comment](https://github.com/hashicorp/docker-consul/blob/2da194710e10e02277cd6b4fb38fb1d1f3ec2fc7/0.X/Dockerfile#L75) in the docker file, that causes the service to store everything in RAM only. This would mean that we'd have to probably create our own edgex-consul image if we want persistence. I think it's hashicorp's intent to provide the Consul image for dev purposes only and not production.

**Comment by anonymouse64** [comment]
FWIW, the snap doesn't have this problem as we don't call consul with the
-dev flag. If the docker deployment starts using specific command line
flags to launch consul we should make sure the snap is kept in sync.

**Comment by jpwhitemn** [comment]
This work is complete
