### ISSUE TITLE
Delete of device causes cascade delete of related device data (Fuji Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#828]
The issue of device ownership or management of devices will be corrected in the Edinburgh release.  Metadata will be considered the source of device knowledge for all of EdgeX and with the Edinburgh release, any deleting a device in metadata requires removing all associated metadata information in metadata as well (provision watcher, etc.).  Additionally, a blacklist of devices (managed in and by Core Metadata) will be added and any time a device is deleted, the device will be added to the blacklist so that the device does not automatically get provisioned again when auto provisioning of the device is triggered by a device service.
Closely associated to #826

**Comment by tsconn23** [comment]
There are two pieces to this and we may split this issue out into two.
1.) Ancillary device data cleanup -- profile watchers, events tied to device name, others
2.) Device list blacklist implementation (#826)

**Comment by tonyespy** [comment]
@tsconn23 I thought the consensus was to close this out? When we discussed this in Edinburgh, the rule was that anyone deleting devices from Core Metadata is responsible for cleaning up related objects in Core Metadata. I believe the only such object today is a ProvisionWatcher, but as we decided to punt on dynamic device discovery for Edinburgh, that's not really something we need to worry about.

As for Events and/or Readings in Core Data which reference a deleted device, I think Core Data should just report back an error if asked to validate that the device exists, but otherwise it should just report the events/readings as is if queried...

**Comment by tsconn23** [comment]
Closing per Tony's input. Device provisioning / blacklist is handled elsewhere. Deleting a device will cleanup its related commands already. It will also prevent any ingestion of events tied to that device (assuming the appropriate configuration flag is enabled)
