### ISSUE TITLE
Refactor DS Addressable and embedded as needed (Edinburgh Roadmap Item)

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/edgex-go#831]
The Addressable, used in multiple areas of EdgeX to identify a service or data destination such as a REST endpoint or MQTT topic, will be relooked and potentially modified to better support the broader needs of project. Should also deal with issue #551

**Comment by iain-anderson** [comment]
At the Device WG is was felt that rather than redefine Addressable for all of Edgex we would replace it in the definition of Device, and leave it to other groups to decide on the best course of action where Addressable is in use elsewhere.
We propose that the "address" field in a device becomes typed as name-value pair (map[string]string in Go, edgex_nvpairs* in C) rather than Addressable.
A mandatory element named "schema" will indicate what class of address is being described. Each device service will then define one or more schemas which it supports, these definitions indicating the names and meanings of all mandatory and optional elements of the address.

**Comment by tsconn23** [comment]
I agree with @iain-anderson. The discussion thus far in the Device Service WG doesn't necessarily entail any changes at all to the Addressable in the other services, only at the device service layer. We can leave the issue open in case that changes but based on where the discussion is now, I don't see any work to be done from a core/support/export perspective.

**Comment by jduranf** [comment]
@tsconn23 in export, the certificates used by MQTT or AWS are stored in the configuration file, but I think they should be stored in the addressable

**Comment by tsconn23** [comment]
@jduranf What if we stored them in Vault with names or keys in the Addressable?

**Comment by jduranf** [comment]
@tsconn23 In my opinion, this information should be provided by the client when registering a new export service. All export service information is provided by the client, why the cert/key are in configuration? Using the configuration to store this information have some disadvantage, like only allows one export service of the same type or, if Consul is disabled, the configuration only is refreshed after restart the service.

**Comment by tsconn23** [comment]
Initial part of the discussion is duplicated with https://github.com/edgexfoundry/edgex-go/issues/1101. If certs/keys need to be added on the export side, recommend opening an issue when the new app-functions-sdk repo is created. Closing this one.
