### ISSUE TITLE
Add AutoEvents (Subscriptions) to device model

### ISSUE THREAD

**Issue by iain-anderson** [edgexfoundry/edgex-go#946]
The purpose of this change is to provide a new mechanism for device services to autonomously generate events, and to be able to take advantage of devices which can push new readings rather than relying on polling.

We propose that a "subscriptions" field is added to "device". This will contain 0..n subscriptions which are defined as { resource, interval, onChange }.
resource : the name of the resource in the device profile which describes the event to generate.
interval : for devices which must be polled, the time between queries. For devices which can push, the minimum interval between generated events (ie, a rate limit).
onChange : boolean. If true, only generate events when readings change.

**Comment by tonyespy** [comment]
A few comments on this approach:

 * This provides less functionality than the existing `Schedule/ScheduleEvent` model:
   *  A `ScheduleEvent` specifies an endpoint `Addressable.Path` that can be called vs. a resource name (by which I think you mean a device resource?). A `ScheduleEvent` can call a device resource or resource (command).
   * A `ScheduleEvent` also has an optional `Addressable.Method` field and an optional `Parameters` field allowing PUT commands to be scheduled. We could just say that scheduling PUT commands must be done via the Scheduler service, and punt on supporting this via the internal SDK scheduler, but we're still removing functionality which exists today.
   * I prefer **frequency** vs. **interval**, as this keeps the terminology similar to a `Schedule` object. I'm also not sure we should overload this field in order to rate-limit a device which can push. I think it probably deserves its own field called **limit** or **rate-limit**.
   * **onChange** can only be supported if we implement a readings cache (not sure if we agreed to implement one for Edinburgh? If so, we should make sure there's an issue filed).

My original idea for this was to leverage device profiles similar to what @cloudxxx8 did in his original device-virtual device service. The idea would be to add a new `ScheduleProperty` to each device resource, so a device resource could have a **value**, **unit**, and **schedule** properties. There are problems with this approach too:

 * it requires the device service to have its own persistent store
 * like your proposal, it doesn't allow scheduling of resource commands, only device resources
 * it means all devices inherit the same frequency, which could lead to a Core Data meltdown unless some we built in some kind random +/- delta added

So, I think your approach, with some tweaks to address some of the points of raised is probably the best approach, however we should probably discuss more in the new year...

**Comment by iain-anderson** [comment]
With regard to the above,

I'm not sure what you mean in the discussion of endpoints. The ScheduleEvent
targets a command by specifying its path, and the proposed mechanism targets
a resource (resource operation) by name: the resource should have a 1-to-1
mapping to a command.

Agreed that we can't do PUT in the proposed scheme. We think that the scheduling
service is a good and useful way of doing things and we don't aim to duplicate all
of its functionality. We'd like a separate capability in the device service
firstly to avoid heavy overheads for very frequent device reads and secondly
to leverage the ability of some device types (eg OPC-UA) to generate
scheduled/on-change readings themselves.

Frequency vs Interval - I take your point on terminology, although I also had in
mind to have a different specification (probably number of seconds as a decimal)
rather than the ISO8601 periods used in ScheduleEvents. How about MinFrequency
and MaxFrequency for the polling interval and rate limit?

I think we'll want to do the readings cache for Edinburgh. I'll file an issue.

**Comment by cloudxxx8** [comment]
@iain-anderson 
In current device profile design, the resource is not 1-to-1 mapping to a command.  One command can contain one array of get resource operation and one array of set resource operation. Users could define one command to read multiple resource, for example:
```
  name: "GetHVACValues"
  get:
  - { index: "1", operation: "get", object: "Switch", parameter: "Switch", property: "value" ,mappings: { "true":"OFF","false":"ON"}}
  - { index: "2", operation: "get", object: "OperationMode", parameter: "OperationMode", property: "value",mappings: { "0":"Cool","1":"Heat","2":"Auto","3":"Dry","4":"HAUX","5":"Fan","6":"HH","8":"VAM Auto","9":"VAM Bypass","10":"VAM Heat","11":"VAM Normal"} }
  - { index: "3", operation: "get", object: "FanSpeed", parameter: "FanSpeed", property: "value",mappings: { "0":"Low","1":"Med","2":"High","3":"Auto","4":"Top","5":"Very Lo","7":"VAM Super Hi","8":"VAM Lo FreshUp","9":"VAMHiFreshUp"} }
  - { index: "4", operation: "get", object: "RoomTemperature", parameter: "RoomTemperature", property: "value" }
  - { index: "5", operation: "get", object: "Temperature", parameter: "Temperature", property: "value" }
```
https://github.com/edgexfoundry/device-modbus-go/blob/master/cmd/res/example/modbus.test.device.profile.yml

We did encounter this kind of requirement from some users.

**Comment by iain-anderson** [comment]
@cloudxxx8 That's a resource operation that maps to multiple device resources, no? That shouldn't be a problem for us.

**Comment by cloudxxx8** [comment]
we should move this issue to go-mod-core-contracts
I've created one:
https://github.com/edgexfoundry/go-mod-core-contracts/issues/14
@iain-anderson or @tsconn23 please close this one if you agree.  thanks
