### ISSUE TITLE
Switch to redis as the database provider for the snap

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/edgex-go#959]
Once all of the relevant services that currently use mongo are able to use redis instead, we should switch to use redis in the snap so that we can build/run the snap on arm 32-bit platforms such as the Raspberry Pi.

@tonyespy apparently has started work on this, so assigning to him...

**Comment by anonymouse64** [comment]
As per my discussion today with @tonyespy we agreed to first add redis into the snap so we can experiment with it and then try to make the decision regarding switching to it as the default afterwards.

**Comment by anonymouse64** [comment]
We will consider whether to change for Fuji as we've hit the limit on Edinburgh changes

**Comment by anonymouse64** [comment]
Unassigning myself to let Tony decide on the default that should be used for the snap

**Comment by anonymouse64** [comment]
Let's do this for Geneva

**Comment by tonyespy** [comment]
This was already handled in this PR:

https://github.com/edgexfoundry/edgex-go/pull/2426

However it's not yet possible to switch back and forth between mongo and redis in the snap yet due to the config seed changes. As such, I'm leaving this open for now as there's a little more work to left remaining.

**Comment by tonyespy** [comment]
Logic to switch back and forth was added in https://github.com/edgexfoundry/edgex-go/pull/2534, so closing this out.
